### ISSUE TITLE
Need for testimonials about using VS Code & Z Open Editor

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#100]
## Testimonials

Hi, 

This may not be the purpose of the GitHub site to make this request, but I have not identified other ways to do so.
If my request is a problem for the administrators of the site, I authorize them to mean it in response to this message, and to close this issue.

We are in the process of defining our new COBOL development workshop, which should replace our current solution based on a COBOL code generator (IBM VisualAge Pacbase, in use for us since 1988, still active, but no longer maintained).

We are convinced of the qualities of the VS Code product and the Z Open Editor extension, and that we are making the right choice by choosing these solutions. However, the highest authorities of our company ask us to justify our choices and to validate them with major market compagnies.

These solutions are recent and not widely used, at least in France, and we have not succeeded at this time in finding users testimonials who have already implemented these solutions and already use them on a daily basis.

I am therefore asking the users of this GitHub site who could give us their testimony in the use of the VS Code and Z Open Editor solutions in a more advanced context than ours:
* what feeling on the part of the users (developers),
* what productivity obtained by developers compared to another earlier solution,
* what difficulties may have been encountered in setting up the solution,
* what additional developments were necessary to finalize the solution,
* what are the potential risks, on the products, and on their implementation, on the impact on users,
* etc.

Some information about our context:
* between 600 and 700 developers, 50% in service with a significant turnover,
* between 300 and 400 active developers per day on COBOL coding activities,
* around 30,000 COBOL programs active in production, (note: without any COPYBOOK because it does not make sense with the use of a code generator ... we have work to do on adapting this legacy to maintain it in a traditional way),
* around 1,800 applications, each application to be managed in its Git repository,
* COBOL (V6) /  Endevor / CICS / Db2 / MQ technical background

Answers can be provided on this GitHub site, if the administrators authorize it, or by personal messaging.

Thanking in advance the people who will be able to answer my request.

**Comment by phaumer** [comment]
Thanks. We would definitely be interested in responses to these questions as well.
