### ISSUE TITLE
Question - Java SDK prerequisites details

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#102]
It is indicated that a Java JDK is necessary to have all the functionalities of Z Open Editor:

`Note, in all cases, you need to download and configure a full JDK and not just a Client Runtime version of Java. The language servers will not fully work with only a Client Runtime version.
`

We only have a Java JRE, and it does not seem planned on our site to deploy a Java JDK on the workstations.

What features are impacted when a Java JRE is installed instead of a Java JDK?

In addition, our company blocked any upgrade of the Java JRE for licensing issues.
There are no plans to switch to OpenJDK.
We are currently in Oracle Java version 1.8.0_102.
We draw your attention to this Java version problem which could become problematic for us if you decide to switch to a Java version requiring either a licensed version or to switch to OpenJDK.

**Comment by phaumer** [comment]
Yes, the Java situation is tricky and complex and I cannot make any statements about which versions we are going to support until when as there are many dependencies we have that will have an influence on it.

The good news is that we eliminated the dependency to the JDK already in the previous release unofficially and will update our docs soon together with new code for checking and reporting on the Java environment being used. So with Oracle Java 8 JREs you are good for now.

**Comment by FALLAI-Denis** [comment]
Thanks @phaumer 
This issue can be closed unless you want to keep it visible.
