### ISSUE TITLE
Using z/Open editor to edit a local CBL file with an associated local CPY file - possible? 

### ISSUE THREAD

**Issue by davidkjackson54** [IBM/zopeneditor-about#103]
Not sure if this is outside the scope of z/Open Editor or not.
I wish to download some COBOL members with their associated copybooks using zowe and Z/OSMF REST api's.
I have z/Open Editor Settings to find local Copybooks with file names ending in .cpy etc.
I then want to use the z/Open Editor to edit those .CBL files. 
However the COPY statements are remaining as underlined and 'Not Found'. Both the CBL and the copybooks are in the same local directory of my choice.   

My intention was to put the edited files back up to the mainframe again using zowe with z/OSMF rest api's at a later time.

Is this outside the scope of z/Open Editor to be used in this manner? 
I basically want to use z/Open Editor as my preferred choice of local COBOL, ASM language  and JCL editor but need to be able to mange local .cpy  files. That is the only thing causing an issue.

**Comment by phaumer** [comment]
Hello David. Did you define a property group in your settings or zapp file to specify that the copybooks are in the same directory? It can be as simple as this if there are in the top-level workspace directory.

```yaml
name: myApp
property-groups:
  - name: currentDir
    type: local
    syslib:
      - "."
```

See https://ibm.github.io/zopeneditor-about/Docs/setting_propertygroup.html and https://ibm.github.io/zopeneditor-about/Docs/zapp.html.  

We just started discussion that we should provide some defaults perhaps if no properties groups can be found, such as current and all parallel directories with performance warnings if the search space is tool large. What do people think?

**Comment by FALLAI-Denis** [comment]
Also, be carrefull about dsname of pds from wich cobol and copy are retrieved from host (by Zowe Explorer or by Zowe CLI ?). 
Local file must be associated to rigth type for Z Open Editor can search for and find copybooks. 
I suggest to activate debug log on ZOE in verbose mode to see how copybooks are searched.

**Comment by davidkjackson54** [comment]
Peter, You re correct in that I need to set the propertygroup for local.

**Comment by davidkjackson54** [comment]
Hi Peteer,
I am struggling to get the correct syntax for this . It should be simple.!
I want to set the the local SYSLIB to be all directories under a specific
named directory /myFolder. I am not using a workspace - just a folderand
the folder is open..
I have tried :
"./myFolder"
"./myFolder/*"
"./myFolder/*.*"
"./myFolder/*.**"

The only one that works for me is "."

Can you clarify what the format should be to accomplish this?

**Comment by phaumer** [comment]
@davidkjackson54 when opening with File > Open Folder you open a single-root workspace in VS Code. The property group's syslib is then relative to that folder. On Windows all variants such as "myFolder", "./myFolder", or ".\\myFolder" plus the glob pattern you used should work. The most common reasons why it does not work then is (a) the property groups are not specified correctly (b) there is more than one property group and yours is overridden by one in a file with higher precenndence.

To analyze this switch logging to DEBUG and inspect the log file in the VS Code Output panel. You are looking for lines like these that tell you which property groups are being considered using their names:

```log
[2020-12-06 15:56:49.313 - DEBUG] ** ZLanguagesResourceResolver.documentRequested: The COBOL language server requested the following include file: "CUSTCOPY". **
[2020-12-06 15:56:49.314 - DEBUG] ** ZLanguagesResourceResolver.findIncludeFiles: Started looking for "CUSTCOPY" in 3 property groups: [cobol-local, zowe-mvs, zowe-mvs2]. Will search in that order. **
```

**Comment by FALLAI-Denis** [comment]
syslib can be a relative (to root workspace) or an absolute path: 
https://ibm.github.io/zopeneditor-about/Docs/setting_propertygroup.html#setting-ibm-z-open-editor-property-groups-using-glob-patterns-relative-path-and-absolute-path-local-files-only

If you open a file and not a folder, perhaps there is no root workspace, so try to give an absolute path for syslib.

**Comment by phaumer** [comment]
@davidkjackson54 closing this for now. Please, reopen if you find more issue. Also feel free to send the the log file again as previously.
