### ISSUE TITLE
Question: purpose of the "version" property in zapp.yaml

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#104]
Hi,

I wonder about the purpose of the "version" property in the zapp.yaml files:
- is it to manage the operation of the zapp.yaml file, for example to manage changes in the structure of the file?
- is it to document the versioning of the Application managed through the zapp.yaml file?

In a Git context, the zapp.yaml file being in principle a tracked file, I don't see how to manage an evolving notion like the version of the Application: the push and pull of Git will overwrite the information. Unless you manage Git branches by version and never merge versions between them, (upgrades, or postponement of maintenance "Vn" to "Vn + 1").
In a zapp.yaml file it should only contain technical information that is relatively stable over time.

Thanks.

**Comment by phaumer** [comment]
@FALLAI-Denis currently the version property is not used and can be used for pure documentation purposes describing the version of the application under edit. 

The role model for this property is package.json files for npm or pom.xml files in Maven. They describe an artifact typically with a name and version number. As we are also envisioning that we could support references between zapp files, similar to how npm or Maven reference dependent packages, such as the application referencing reusable modules. Those modules could be managed in another folder in a multi-root workspace in VS Code or in a repository such as Artifactory. Some ideas for how this could fit into a larger pipeline have been outlined by my colleagues in this [paper](https://www.ibm.com/support/pages/packaging-and-deployment-strategies-open-and-modern-cicd-pipeline-focussing-mainframe-software-development). We want to explore some of these ideas with zapp perhaps in the future.

In respect to Git I would see this orthogonal or independent, similarly as npm or maven projects use the human readable version number for published versions and have a notion of snapshot versions for intermediate builds. Git does not have versions, but commit hashes, which could indeed be used as a replacement to a version ID as well. In that case the version property in zapp could be optional as well as complementary. However, we do want to integrate well with Git, but do not want to prescribe it.
