### ISSUE TITLE
z Open Editor has stopped downloading copybooks.

### ISSUE THREAD

**Issue by oakmount66** [IBM/zopeneditor-about#105]
After upgrading to 1.1.2 z Open Editor has stopped downloading copybooks.
With DEBUG logging we can see, that z Open Editor wish to look in "zopeneditor.propertygroups" for the books, first local-files and then mvs-members. But in the log you can see, that it never looks in mvs-members.

Copy from debug log.

![image](https://user-images.githubusercontent.com/60236192/101896105-c294ac80-3ba8-11eb-9031-eee8c43646c0.png)

Then I tried to switch around and place MVS-members first and now it looks in mvs-members but not in local-files.

![image](https://user-images.githubusercontent.com/60236192/101895692-29659600-3ba8-11eb-86db-b35f528daede.png)
.
.
.
.
![image](https://user-images.githubusercontent.com/60236192/101895783-45693780-3ba8-11eb-8274-7d939cbf9962.png)

We also tried to switch back to z Open Editor 1.1.1 and now it's working fine again.

Best regards, Lars

**Comment by AlexKotsc** [comment]
Also; the warning generated asks you to switch to "DEBUG" log level, which is already enabled

`The COBOL language server requested the include file "module", which was not found. Check your Zowe CLI profile and property groups settings or switch to the "DEBUG" log level for more information.`

**Comment by gplambert** [comment]
We have a fix identified, will respond back here when we have a fix shipped.

**Comment by phaumer** [comment]
@oakmount66 thanks for reporting the issue. I just uploaded v1.1.3 with a fix. Could you verify?

**Comment by oakmount66** [comment]
Thanks Peter. It's working fine now.
