### ISSUE TITLE
Cooperation with IBM Db2 for z/OS Developer extension

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#106]
## Description of the enhancement requested

IBM offers an extension to develop and especially test SQL statements through the IBM Db2 for z/OS Developer extension.

[IBM Db2 for z/OS Developer Extension](https://github.com/IBM/db2forzosdeveloperextension-about)

Regarding the test part of SQL commands, would it be possible for IBM Z Open Editor to cooperate with IBM Db2 for z/OS Developer?

Use case:
- writing an SQL query in a program (COBOL)
- selection of the SQL query in the source code of the program
- execution request through IBM Db2 for z/OS Developer (after having rid the SQL code of "artifacts" specific to the host language, namely for COBOL removal of line numbers, of the identification area and of the "EXEC SQL"and "END-EXEC" delimiters)

**Comment by phaumer** [comment]
Thanks for the suggestion. We are already working closely with that team. Let's just track this item in their repo for now.
