### ISSUE TITLE
Using z/OSMF profile with APIML SSO option for include resolution

### ISSUE THREAD

**Issue by TimMSbg** [IBM/zopeneditor-about#107]
Hi,
we have one z/OSMF profile with APIML basePath

 name:     xxx (default)
  contents:
    basePath: api/v1

With this profile there is no chance to resolve pli includes within defined property groups.

When I define another z/OSMF profile that communicates directly with z/OSMF (with userid and pw) and I set this profile as defaultCLIProfile all includes will be resolved.

 "zopeneditor.zowe": {
        "defaultCliProfile": "xxx2",
    },

Is there any chance, that this will work with the first profile (with APIML SSO)?

Thanks and regards
Tim

**Comment by JillieBeanSim** [comment]
Hey @TimMSbg with the base profile (default) is the only included field the basePath? Also, is this base path included in the zosmf service profile that is to be merged with the base profile?
Finally are you using the secure credential store with the profiles?

**Comment by phaumer** [comment]
Thanks for reporting this @TimMSbg. We have this on our list to add, as we are [refactoring more code the Zowe Explorer API ](https://github.com/zowe/vscode-extension-for-zowe/issues/837).

**Comment by TimMSbg** [comment]
> Hey @TimMSbg with the base profile (default) is the only included field the basePath? Also, is this base path included in the zosmf service profile that is to be merged with the base profile, that zosmf profile added as the defaultCLIProfile, and is the property group for remote resolving?
> Finally are you using the secure credential store with the profiles?

Hello JillieBeanSim
do you need any of the information as phaumer mentioned that this is on your todo list?
Thanks
Tim

**Comment by JillieBeanSim** [comment]
Hey @TimMSbg no I don't believe I will need any info, thanks for commenting back.

**Comment by phaumer** [comment]
Fixed in v1.2.0. @TimMSbg let us know if this works for you now.

**Comment by TimMSbg** [comment]
Hello Peter,

greate work. The fix works perfectly for me.

Thank you!!!
