### ISSUE TITLE
How do I use the RSE implementation of TSO commands with the Zowe "z/OS TSO Package" ( https://www.npmjs.com/package/@zowe/zos-tso-for-zowe-sdk )?

### ISSUE THREAD

**Issue by travatine** [IBM/zopeneditor-about#109]
Hi,

I would like to use the "z/OS TSO Package" with an RSE server, is that supported?

Thanks

**Comment by gplambert** [comment]
This is a question for the Zowe team and I see you have asked it on their github issues page.

**Comment by phaumer** [comment]
@travatine you do not really need this TSO package unless you want to support both RSE API and z/OSMF. The RSE API installation package provides its own type library that you need to use it as an alternative SDK to execute commands via a NodeJS client. 

As I had not looked at this new packaging of the Zowe CLI myself I was curious to use them both and created this small example that extended the Zowe example with RSE: <https://github.com/phaumer/zowe-cli-tso-rse-sample>. Let me know if that is what you were looking for.

**Comment by travatine** [comment]
Hi @phaumer ,

Thanks for the sample code, its just what I'm looking for!

The reason I'm so interested in all this is that IBM asked me to make the "Fault Analyzer for VS Code Extension" work with both "zosMF" and / or "RSE" connections; so users can leverage whatever they host component they have installed / configured.

Thanks
