### ISSUE TITLE
Adding HLASM and REXX language support would most definitely enhance Developer Experience on the Mainframe

### ISSUE THREAD

**Issue by AneesBidhani** [IBM/zopeneditor-about#11]
Dear team,

Your work and efforts are highly appreciated by the wider community of mainframe developers. 
This is more of a suggestion rather than an issue and it is intended to kindly request the addition of support of languages such as High-Level Assembler (HLASM) including Macros as well as REXX scripting language. 

Enhancing Z Open Editor with more mainframe-specific languages would most definitely improve Developer Experience and decrease lead times on development and testing and allow faster deliver of mainframe quality code.

Thank you very much!
Best regards,
Anees Bidhani - DevOps Evangelist

**Comment by phaumer** [comment]
HLASM support was added in v1.0.0 that is available here now for IDz EE customers as well as soon available for free here as well: https://developer.ibm.com/mainframe/products/downloads/

It will also make it the VS Code Marketplace at some point soon.
