### ISSUE TITLE
Z Open Editor is putting both a squiggly and a sold underline under a copybook.

### ISSUE THREAD

**Issue by davidkjackson54** [IBM/zopeneditor-about#114]
I have an assembler program with a simple copybook that I am using to test.
The copybook (.hlasm) exists in the same local folder on my desktop as the .asm file itself.

When I edit the .asm file it is showing both a squiggly and a solid underline under the copy member. 
![pic1](https://user-images.githubusercontent.com/46171060/108748908-fd458a00-74f3-11eb-9a32-3e849a27c038.jpg)

If I hover over the image it shows the copy member but also reports that it isn't found !
![pic2](https://user-images.githubusercontent.com/46171060/108749015-1d754900-74f4-11eb-8add-bb6b3da5ec73.jpg)

**Comment by phaumer** [comment]
This could be related to https://github.com/IBM/zopeneditor-about/issues/81, which we think is a sync or timeout problem with the LSP client. When you have multiple tabs open and switch between them, i.e. go to another tab and back. Does the squiggle go away?

**Comment by davidkjackson54** [comment]
@phaumer 

H Peter,
Here is the scenario.

Starting fresh, I selected an element in the Explorer tree, which opened a tab with a solid line under the copybook.  
I then selected a component element in another section of the tree, which opened a new tab with a squiggle under the copybook.
I switched back to the first package.  Still solid.
I switched back to the second element.  Squiggle had changed to squiggle+solid.

I restarted VSCode and the copybook started with no lines under it.  Switching back and forth added the solid line.  No squiggle at any point.

I restarted again.  This time, I had squiggly that changed to squiggly+solid by opening a new tab and switching back.
Closing that tab and then selecting the element again opens a new tab with just a solid line under then copybook.


There may be a timing issue making it difficult to get consistent results.  
I opened one tab with no lines and waited an age.  
I opened a second tab with no lines and waited an age.
I then switched back and forth between the 2 tabs repeatedly.  Eventually, a solid line appeared in both tabs.  I did nothing but switch tabs.

I hope this helps..
David

**Comment by phaumer** [comment]
@davidkjackson54 I am trying to reproduce this on Mac as well as a slow Windows VM, but I can only see the problem reported in Issue #81, not the red squiggles.  If you can still reproduce it, could you send us again the log file: switching the Logger into DEBUG mode, redo the steps and send the file?  Fell free to send via email as in the past.

**Comment by phaumer** [comment]
We did some performance improvements and refinements for the loading code in v1.2.5 that fixes these cases for us. When you type an include file name very slowly then the red squiggle will appear as it will try to find the file while you type. Once the name is complete and the file found there should be no more red squiggles. The issue in which no underline is shown is still present and the workaround is to switch tabs or start editing.
