### ISSUE TITLE
Disable performance warnings

### ISSUE THREAD

**Issue by davidkjackson54** [IBM/zopeneditor-about#115]
Performance warning: Your specified Property Groups with a GLOB pattern that returns more than 20 directories to search though. For performance reasons, please revise the search pattern to match less.

This has started to appear as a constant irritation today.
My property groups are defined like this:  I have a Explorer extension that places files locally under the d:/myFolder. These files are later deleted during the session.
So this constant popping up of this message is really irritating.  Can this be suppressed instead of constantly appearing? 
 
```
"zopeneditor.propertygroups": [
        {
            "name": "local-cobol-files", 
            "type": "local",
            "language": "cobol",
            "syslib": [ 
                "d:/myFolder/**"
            ],
        },
        {
            "name": "local-asm-files", 
            "type": "local",
            "language": "hlasm",
            "syslib": [ 
                "d:/myFolder/**"
              ],
        },
       
        {
        "name": "mvs-members",
        "type": "mvs",
        "syslib": [
            "DJACKSO.TEST.COBOL",
            "DJACKSO.TEST.ASM",
        ],
      }
    ],

```

**Comment by phaumer** [comment]
@davidkjackson54 we can file this as an enhancement to have a user setting to disable warnings like these.
But are you also saying that we need to support more than 20 folders? How many do you need in your cases?

**Comment by davidkjackson54** [comment]
My VSCode extension creates a file structure of files downloaded from the
mainframe which are editted locally by z/Open Editor.  However the files
that are downloaded also include zFS file locations and these are also
brought down into the file structure. It is the addition of these zFS
files (mostly Java) that is causing a greater depth in the file structure
even though z/Open Editor has no interest in those Java files.  It's isn't
horizontal folders under d;/myFolder but rather how deep the folder
structure goes.   I do not need to differentiate between z/OS files or zFS
in the Explorer.

David

**Comment by phaumer** [comment]
Our editor would find files faster though if you specify more concrete pathnames in the property groups. You can also use glob wildcards such as "myFolder/**/COBOL"

**Comment by davidkjackson54** [comment]
Hi Peter
My folder structure is based around our product / U820ALL is our ZMF
system, MARK is an application and tafpoc.java is a component. Only the
component suffix relates to the langauge
and not by language so an example might be :
[image: image.png]

or this for a COBOL example: again U820ALL is the ZMF system, Packages is
simply a title and STEV001571 is a package and CBLDB201 is the component
that contains the /CBL and a copy member.
[image: image.png]

It would take some significant changes as I do not know the language when I
am at the System level; etc  or even at the Package level.
My Explorer tree structure looks like this: for the above CBLDB201 example
[image: image.png]

**Comment by davidkjackson54** [comment]
Peter
I have looked into this and it is not going to be possible for me to
redesign the directory structure. The language is way down in the structure
path and we have our many systems at the head of the directory structure
each with their own directory.

From our point of view, not constantly seeing that popup message would
reduce the number of calls we are likely get over this.  Most of my users
think this is coming from our Explorer when in fact it is from z/Open
Editor.

David

**Comment by phaumer** [comment]
@davidkjackson54 ok, we will consider providing options to configure these warnings.

**Comment by davidkjackson54** [comment]
Thank you.

**Comment by davidkjackson54** [comment]
Peter, just to provide some context here. My Explorer retrieves source components from the mainframe down to the local machines plus any required copybooks. The source component and its copybooks if any are then saved in a local folder prefixed by the source member name.  So the local location is dynamic and based on the source member name.
I then load the source and present it to VSCode which in turns hands it off to the Language engine - IBM z/Open Editor in this instance.   
So in this case, the only 'searching' involved is  z/Open Editor having to find the copybook member. 
I know where that is but I cannot notify z/Open Editor as to where to find it directly?

**Comment by phaumer** [comment]
We removed the dialog and replaced it with a log message in v1.2.5, @davidkjackson54
