### ISSUE TITLE
file.associations wildcard pattern

### ISSUE THREAD

**Issue by dkelosky** [IBM/zopeneditor-about#116]
## Development environment used

- Z Open Editor version:
- Editor Platform
  - [x] Visual Studio Code
  - [ ] CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version:
- Operating System (on which VS Code runs such as Windows 10 2004, otherwise name and version of platform such as OpenShift v4.3):
- Java Version (when using VS Code or Theia, extecute `java -version` and paste the details here):
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/knownissues.html) how to get them): yes/no

## Problem Description

Detailed steps for reproducing the problem:

IBM z Open editor highlights any file that matches `.ASM*` as an HLASM file, even listings, and I cannot stop this from happening. 

### Observed behavior

It looks like IBM Z Open Editor is unconditionally setting file associations in my settings.json:
```json
        "*.COBOL*": "cobol",
        "*.COB*": "cobol",
        "*.COBCOPY*": "cobol",
        "*.COPYBOOK*": "cobol",
        "*.COPY*": "cobol",
        "*.PL1*": "pl1",
        "*.PLI*": "pl1",
        "*.INC*": "pl1",
        "*.INCLUDE*": "pl1",
        "*.JCL*": "jcl",
        "*.ASSEMBLE*": "hlasm",
        "*.ASM*": "hlasm",
        "*.HLASM*": "hlasm",
        "*.HLA*": "hlasm",
        "*.MACRO*": "hlasm",
        "*.MACLIB*": "hlasm",
```

### Expected behavior

I think there are two problems.  
- If I delete these and relaunch VS Code, these settings are automatically added back.  
- Secondly, I'm not sure if each of these should end in wild card.  `        "*.ASM*": "hlasm",` matches `main.asm.listing` for example, but this is not a HLASM file, it should be text only.

**Comment by phaumer** [comment]
Hello @dkelosky. See this doc page for some background on why the entries get added back: <https://ibm.github.io/zopeneditor-about/Docs/setting_fileassociations.html#removing-file-associations> 

Our goal was an easy getting started experience that assumes common defaults, but we do want to make it configurable.  To get rid of the `*.ASM*` mapping you can do the following:
1. Open User Settings > IBM Z Open Editor
2. Remove .ASM from the list called `Datasets: Hlasm Datasets`
3. Remove .ASM from the list `Hlasm: Include File Extensions`
4. Then remove *.ASM* from the files.associations and it will not be added back

Let me know if this works for you then I will close the issue.

**Comment by dkelosky** [comment]
Thank you, I missed this part in the doc.  Given that there is a way around this, closing the issue makes sense.
