### ISSUE TITLE
Support for z/VM NAMES files, GML/BOOKMASTER files, and PL/X

### ISSUE THREAD

**Issue by vmdave9** [IBM/zopeneditor-about#117]
Support in VS Code for z/VM - CMS NAMES files, DCF-GML and Bookmaster files and for PL/X files
The title says it all.......and I already have the .json textmate files that I would be happy to contribute to the project. I just don't know how to make those into a installable package.

I can be reached at djones@itconline.com
Thank you very much.
DJ

**Comment by phaumer** [comment]
Thanks a lot for the request. Right now we have no plans on expanding the scope of our extension for supporting these files and languages.
