### ISSUE TITLE
Bug: Can't load USS file list

### ISSUE THREAD

**Issue by Rappel87** [IBM/zopeneditor-about#12]
Hello,

I am using the VSCode Plugin Zowe with Version 0.26.0 and Zowe CLI 2.31.2.
When I try to load the filelist of my USS home dir `/u/orth` I get the following error:

![grafik](https://user-images.githubusercontent.com/9461700/67751900-3f5ed880-fa32-11e9-8d40-62ac8f640c76.png)

The problem is a file in the directory containing non-printable characters as filename. I used the TSO program ISHELL to access the directory and delteted the file in question. Now, I can load the file list again. 

An expected behaviour would be a correct error message or an informational message plus showing all files exluding the ones which could not be parsed.

**Comment by Rappel87** [comment]
Yes, that is correct.

**Comment by JillieBeanSim** [comment]
Ok, I have forwarded this issue to zowe/vscode-extension-for-zowe and tagged you

https://github.com/zowe/vscode-extension-for-zowe/issues/286

**Comment by phaumer** [comment]
Thanks a lot @JillieBeanSim. Let's track this item in the Zowe repo.
