### ISSUE TITLE
Fork for IBM COBOL for Linux on x86?

### ISSUE THREAD

**Issue by GitMensch** [IBM/zopeneditor-about#120]
Will there be an IBM provided fork of this for the Linux environment supporting [IBM COBOL for Linux on x86](https://www.ibm.com/products/cobol-compiler-linux-x86)?

**Comment by phaumer** [comment]
@Thanks @GitMensch for your interest, but sorry, this repo is for feedback on the Z Open Editor as currently distributed. We cannot discuss plans here. The best way to do that is to engage IBM's offering management, sales, or RFE communities.
