### ISSUE TITLE
COBOL: copy file not found - may I missing something?

### ISSUE THREAD

**Issue by ssamayoa** [IBM/zopeneditor-about#122]
## Development environment used

- Z Open Editor version:
- Editor Platform
  - [x] Visual Studio Code
  - [ ] CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version: 1.55.2
- Operating System: Windows 10 20H2 19042.928
- Java Version (when using VS Code or Theia, extecute `java -version` and paste the details here):
java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/knownissues.html) how to get them): no
- NOTE: No ZOS connection, local files only.

## Problem Description

Detailed steps for reproducing the problem:

COPY file in the same folder as the source program is not found with message:
Unable to find copybook xxxxx

Exact sentence:
       COPY INQSET1. 

### Observed behavior

I tried the following:
- Change case of copybook's extension (.cpy to .CPY)
- Add ".CPY" (uppercase) in "Cobol: include File Extension"
- Remove copybook extension

On all cases issuing "Pause the COBOL server language" then reopening the source file, making some modification then save but no luck.

### Expected behavior
Copybooks being recognized.

**Comment by phaumer** [comment]
@ssamayoa I do not see you are mentioning your property group. Even if the file is in the same folder you still need to specify a property group with workspace relative or absolute location. 

If you have a property group you can use these instructions to check the log files for error messages and warning resolving your copybooks: https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html

Let me know if that helped.

**Comment by ssamayoa** [comment]
@phaumer 
Resolved!
I should RTFD!
Many thanks!
