### ISSUE TITLE
PLI parser various issues

### ISSUE THREAD

**Issue by kraabrsg** [IBM/zopeneditor-about#128]
## Development environment used

- Z Open Editor version:
- Editor Platform
  - [X] Visual Studio Code (VSCODIUM 1.57.1)
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version:
- Windows 10 Enterprise 20H2
- Java Version: java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached : no

Vscodium details: (z open editor version 1.2.1 / nodej.js 14.16.0 / Electron 12.0.7 / chrome 89.0.4389.128 )

## Problem Description

Open a PL1 source code file 

**Workspace settings:**
                                       {
                                                            "name":  "PLI",
                                                            "compilerOptions":  "NOT(^), OR(!), MARGINS(2,100)",
                                                            "language":  "pl1"
                                                        }
                                                    ],
                     "[pl1]":  {
                                   "editor.rulers":  [
                                                         0,
                                                         1,
                                                         100
                                                     ]
                               }

### Observed behavior

1.) Moved to: https://github.com/IBM/zopeneditor-about/issues/135

2.) see picture "issue1.jpg" -> last line: 
`
returns(bin fixed(15));
`
![issue1](https://user-images.githubusercontent.com/86772851/124114439-dcc2a900-da6c-11eb-9248-e32ea21d5142.jpg)

3.)Moved to: https://github.com/IBM/zopeneditor-about/issues/136

4.)see screenshot and "#" in the copybook name is displayed as "%23" -> last line:
`
       _putFLen,                          /* comment */    
      _putNk)                            /* comment */;  
`
stops parsing at "_FL"
![issue3](https://user-images.githubusercontent.com/86772851/124114802-4c389880-da6d-11eb-948c-ba3cf8892387.jpg)

5.) Moved to: https://github.com/IBM/zopeneditor-about/issues/135

### Expected behavior
 see screenshots and descriptions
-

Thank you!

**Comment by gplambert** [comment]
Can you provide some more context to issues 2-5?  I am trying to recreate the problems but need to know exactly how you were able to encounter them.

Issues 2 and 4 - are you hovering over very large (>10k) includes?  Is the hover truncating the content?
I can recreate the issue of the # in the include name being displayed as %23 in the hover

Issue 3 - I'm not clear on what's happening here, can you advise on how to recreate it?

Issue 5 - Again, can you advise on how to recreate?  What does the line immediately preceding the comment line look like?  Is there a parsing issue on the previous line?

**Comment by kraabrsg** [comment]
Hi @gplambert thanks for commenting back on this.
**Issue 2 and 4:**
yes it is truncating the include on hover, exactly like the screenshot
there were other errors, but i could get rid of them by changing the commentline "fes ... " -> "fds" 

**before:**
![issue2_before](https://user-images.githubusercontent.com/86772851/124422260-54d9e900-dd63-11eb-8de9-68fd2684c539.jpg)
**after:**
![issue2_after](https://user-images.githubusercontent.com/86772851/124422282-5a373380-dd63-11eb-86f0-454e3a2a62c5.jpg)

the errors seems to be not really predictable, now another error is shown:
`
Include file 'XXXXXXX%23' contains the following error: Misplaced construct
`

the include is fb 80 and 750 lines (here the end, where the first error was shown)
![issue2_followup](https://user-images.githubusercontent.com/86772851/124422505-ada98180-dd63-11eb-8ccf-391fcc716b09.jpg)

**issue 3:** 
i can't really provide any further info, it seems to appear randomly, in comments and everywhere

**issue 5:**
unfortunatly it is not reproducable every time, in this case the line before was empty. (it seems to be not a problem when you could get rid of the false warnings when inserting a comment, see "before and after")


Thanks!

**Comment by phaumer** [comment]
These issues seem unrelated to each other. It would be better to file them separately so an issue can be closed once addressed.

**Comment by kraabrsg** [comment]
Thanks @phaumer for getting back on this, i opened two new issues, to seperate them, and these are referenced in my first post.

**Comment by phaumer** [comment]
@kraabrsg We fixed the issue with the special characters in v1.2.6 now available on the Marketplace. Let us know if it works for you as well.

**Comment by kraabrsg** [comment]
@phaumer the character "#" now shows up correctly (instead of "%23"), thanks!
