### ISSUE TITLE
Problems with comments and comment length 

### ISSUE THREAD

**Issue by kraabrsg** [IBM/zopeneditor-about#135]
## Development environment used

- Z Open Editor version:
- Editor Platform
  - [X] Visual Studio Code (VSCODIUM 1.57.1)
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version:
- Windows 10 Enterprise 20H2
- Java Version: java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached : no

Vscodium details: (z open editor version 1.2.1 / nodej.js 14.16.0 / Electron 12.0.7 / chrome 89.0.4389.128 )

## Problem Description

Open a PL1 source code file 

**Workspace settings:**
                                       {
                                                            "name":  "PLI",
                                                            "compilerOptions":  "NOT(^), OR(!), MARGINS(2,100)",
                                                            "language":  "pl1"
                                                        }
                                                    ],
                     "[pl1]":  {
                                   "editor.rulers":  [
                                                         0,
                                                         1,
                                                         100
                                                     ]
                               }

### Observed behavior
1.)
![issue4](https://user-images.githubusercontent.com/86772851/124700371-ecb70e80-deec-11eb-9229-657cffef23b9.jpg)

unfortunatly it is not reproducable every time, in this case the line before was empty. (it seems to be not a problem when you could get rid of the false warnings when inserting a comment, see "before and after")

2.)
When a comment ending "*/" is placed at position 99 and 100, and after this line is an INCLUDE, this copybook is not resolved (when comment ending is placed < 99 it is working)

**Comment by kraabrsg** [comment]
a working dummy example for showcase.
![grafik](https://user-images.githubusercontent.com/86772851/125057712-d4d8b980-e0a9-11eb-8adc-8cbe6e0730cc.png)
![grafik](https://user-images.githubusercontent.com/86772851/125057746-dace9a80-e0a9-11eb-9b3b-efa8acfac62e.png)

This is the pli file:
[linktest2.txt](https://github.com/IBM/zopeneditor-about/files/6790373/linktest2.txt)

the copybook on the host(referenced in propertygroups):
[test001#.txt](https://github.com/IBM/zopeneditor-about/files/6790382/test001.txt)

**Comment by gplambert** [comment]
@kraabrsg - thanks for these examples, I was able to recreate the random link issue with them.  This will aid us in researching the issue.

**Comment by phaumer** [comment]
@kraabrsg We fixed this issue in v1.2.6 now available on the Marketplace. Let us know if it works for you as well.

**Comment by kraabrsg** [comment]
Thanks @phaumer for the update, unfortunatly it seems no to be fixed fully...

Steps to reproduce:
1.) i added another copybook for testing, because i noted severall warnings (could also be partly related to the testshow)
   i noted that the copybook on the host is not updated when opening the pli file, so i restarted vscodium (now on Version 1.59.1).
2.) 
![grafik](https://user-images.githubusercontent.com/86772851/130188115-b3d270a8-9754-4d23-9b50-bc97b7970aef.png)
The error seems like exactly before fixing (except the name is correct: "#" instead of "%23")
3.)adding an empty line after include mytable leads to:
![grafik](https://user-images.githubusercontent.com/86772851/130188265-5c5e94f0-8dc0-4644-8362-d494ab0c4cfc.png)
4.) now ambigous reference errors shows up
![grafik](https://user-images.githubusercontent.com/86772851/130188322-61d0ba00-2a34-4d95-bb8b-9c02b3401214.png)

The copybook MYTABLE is a stripped down anonymized db2 table we use, just the names are changed
[mytable.txt](https://github.com/IBM/zopeneditor-about/files/7019502/mytable.txt)
[linktest3.txt](https://github.com/IBM/zopeneditor-about/files/7019503/linktest3.txt)

Thanks for the efforts.

**Comment by phaumer** [comment]
Fixed in Z Open Editor v3.2.0
