### ISSUE TITLE
Revocation of the mvs user during the COPYBOOK search for type "mvs" property-group for invalid password

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#142]
## Development environment used

- Z Open Editor version: 1.2.5
- Editor Platform
  - [X] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version: 1.58.2
- Operating System: Windows 10 PRO x64 "1909"
- Java Version: java version "1.8.0_102" / Java(TM) SE Runtime Environment (build 1.8.0_102-b14) / Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached: no

## Problem Description

After changing the password of the mvs user under TSO/ISPF, using Z Open Editor with a COBOL source containing COPY directives caused the revocation of the user mvs because the password at profile level had not been changed (storing the password in the profile).

No particular anomaly was reported (or not seen) in the notifications in VS Code, except that the COPYBOOK was not found.

### Observed behavior

User revoked on mvs.

### Expected behavior

When mvs user (profil) authentication fails, a notification should be clearly displayed at the editor level, and no mvs access attempts should be triggered again, even when opening another source code (editing another program).
A dialog box for modifying the password of the active profile should be displayed.
Any new attempt to access mvs must be conditional on a modification of the password of the active profile.

**Comment by kraabrsg** [comment]
+1 for that!

**Comment by FALLAI-Denis** [comment]
Hi,

Hello,

The subject becomes very critical for us. 

We have started a pilot phase in using VS Code / Z Open Editor / Zowe CLI / z/OSMF (not RSE).

We created Zowe CLI profiles with user / password stored in the profiles (in clear text, because the SCS plugin does not want to install for us since version 4.1.5: Python runtime problem).

When the z/OS password is changed (under ISPF interface), users do not think of changing it in their Zowe CLI profiles. This subsequently triggers revocations when using Z Open Editor (search for COPYBOOKs on z / OS).

These multiple revocations give a very bad image of the solution to our pilot users, who could oppose us blocking the generalization of the solution to all users.
This also generates problems for the security team who must reactivate user accounts, sometimes several times in the same day for the same user.

While waiting for a solution, would you have any recommendations on the implementation of the Zowe CLI profiles used by Z Open Editor to avoid these repeated revocations?


Questions :
- is Z Open Editor compatible with the use of "base profiles" (unique management of credentials)? (and all VS Code extensions should be compatible with "base profiles", not sure of that...)
- is Z Open Editor compatible with profiles (base or service) without memorized credentials (in particular without memorized password)?

Thank you for the help you can give us.

**Comment by kraabrsg** [comment]
Hi @FALLAI-Denis 
we also have problems like these.

We will use passticket with APIML in the future. Installing all server components on the Mainframe was quite difficult, according to the system devs. In the future you can use a docker image to offload quite a lot of Server Mainframe components to a linux machine. (this would be our rough Roadmap).

We did quite a lot with powershell for automating tasks, using a multiroot workspace. We triggering a task on "open folder", which allows a check of installed versions of cli / plugings / extensions/ powershells at startup, and update them.
One work around would be to issue a rest call, if this fails at startup you could assume the password is not guilty and present a warning message to the user (or even shutdown vscodium)...
Or present an input mask and update the zos password for the profiles...  


Hope this helps...

**Comment by FALLAI-Denis** [comment]
Thanks @kraabrsg 

We also did an evaluation of Zowe Server.
The complexity of the architecture also posed a problem for our system team. In addition, we did not find any interest in using Zowe Server in our context and we decided not to implement it. Zowe CLI, and VS Code extensions like Z Open Editor and Zowe Explorer communicate directly with z/OSMF, (we also did not choose RSE after instructing a comparison bench, and with IBM support In this study).

I'm not sure using APIML fixes the user revocation issue, and I'm not sure if using a passticket is compatible with Z Open Editor, but since we are not using Zowe Server, APIML cannot be used in our case.

I am interested in your VS Code startup operating context validation solution.
Could you detail it a little more? For example in the "Discussions" area on this site?

For us, it would be a question of validating the Zowe CLI profile used by Z Open Editor which is either the profile declared in the parameters of the user or of the workspace (Git repository), otherwise the Zowe CLI profile declared by default.
As this Zowe CLI profile can depend on the Workspace, it should be validated when opening a Workspace rather than starting VS Code.

**Comment by kraabrsg** [comment]
Hi @FALLAI-Denis 
see https://github.com/IBM/zopeneditor-about/discussions/169

**Comment by JillieBeanSim** [comment]
> Questions :
> 
> * is Z Open Editor compatible with the use of "base profiles" (unique management of credentials)? (and all VS Code extensions should be compatible with "base profiles", not sure of that...)
> * is Z Open Editor compatible with profiles (base or service) without memorized credentials (in particular without memorized password)?

Hey @FALLAI-Denis for question 1, Z Open Editor is compatible with the use of "base" profiles. For question 2, we do not have that support as of yet, but it does sound like a great enhancement to have.  Thank you for the discussion and feedback.

**Comment by kkrein** [comment]
Ich bin derzeit nicht im Büro.
Während meiner Abwesenheit bitte bei Postkorb SCM-Admin melden!

Die Rückmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [IBM/zopeneditor-about] Revocation of the mvs user during the COPYBOOK
search for type "mvs" property-group for invalid password (#142)

____________________________________________________________________________________________
Gesendet (c) GRZ/RSG Linz 2021 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angeführten Absender via E-Mail
dient ausschließlich Informationszwecken. Rechtsgeschäftliche Erklärungen
dürfen über dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------

**Comment by phaumer** [comment]
We fixed this in v1.4.1. You now get prompted to provide your password or abort all operations.

**Comment by kkrein** [comment]
Ich bin derzeit nicht im Büro. Ich kehre zurück am  06.12.2021.
Während meiner Abwesenheit bitte bei Postkorb SCM-Admin melden!

Die Rückmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [IBM/zopeneditor-about] Revocation of the mvs user during the COPYBOOK
search for type "mvs" property-group for invalid password (#142)

____________________________________________________________________________________________
Gesendet (c) GRZ/RSG Linz 2021 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angeführten Absender via E-Mail
dient ausschließlich Informationszwecken. Rechtsgeschäftliche Erklärungen
dürfen über dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------
