### ISSUE TITLE
zopeneditor.zowe must be a Workspace setting

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#143]
## Development environment used

- Z Open Editor version: 1.2.5
- Editor Platform
  - [X] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version: 1.58.2
- Operating System: Windows 10 1909 Pro x64
- Java Version: java version "1.8.0_102" / Java(TM) SE Runtime Environment (build 1.8.0_102-b14) / Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version: 6.32.2
  - Node.js version: v12.13.0
- Logs attached: no

## Problem Description

Z Open Editor must access a remote z/OS system to find COPYBOOKs and INCLUDEs.
This requires a Zowe CLI profile for connection to the remote system.

Today the Zowe CLI profile is declared by the "zopeneditor.zowe" parameter in the User's "settings.json" file.

However, the search for COPYBOOKs and INCLUDEs is specific to the Application, and therefore specific to the Workspace.

In our context, we are working with 5 z/OS partitions, with a distribution of the Applications on these 5 z/OS partitions (an Application is on one and only one partition).
The Zowe CLI profile cannot be managed at User level: it is essential to manage it at Workspace level, (with the consequence that all Users must declare the same Zowe CLI profile name to access the remote z/OS system , which we implemented by imposing that the profile be named like the partition).

We therefore ask for an evolution to leave the choice of management of the zopeneditor.zowe parameter either at User level or at Workspace level.

The identification of the profile to use could / should also be carried by the file zapp.yaml, confer #95.

**Comment by phaumer** [comment]
Allowing this setting for workspaces as well seems reasonable. We will evaluate this to see if this is possible.

For the ZAPP issue: We will reevaluate all these question when we adopt team profiles. However, one design decision we made in the past was to keep zapp independent of the technology that is used to interact with z/OS, i.e. do not reference Zowe concepts from it, because we want to use ZAPP also for other non-Zowe use cases such as native RSE. That is why we made this a VS Code setting only.

**Comment by FALLAI-Denis** [comment]
As indicated in issue #95, the evolutions of Zowe CLI V7 on profile management will not solve the problem of choosing the Zowe profile to use in relation to the context of the current Application, (the context of the Workspace, which corresponds to the Git repository opened when working with Git).

The zapp.yaml file could contain the information to use to access a remote resource, without creating a strong dependency with Zowe CLI.
To do this, it would be necessary to be able to specify in a property-group the protocol to be used, the reference to the remote system, and possibly credential information.
At the zapp.yaml level it is just declarative and has no impact. It is then the host system which decides how to use this declarative informations in zapp.yaml: for VS Code this can correspond to the use of a Zowe CLI profile, for another host system (IDz, ZOD ...) this will be another interpretation.

In issue #95, I proposed to use the `system` property (present in the JSON validation schema but not documented) to carry the information to access the remote system:
`zosmf-profile://profile_name`
`zftp-profile://profile_name`
`rse-profile://profile_name`
It can also be:
`http://url_to_server`
`ftp://prefix_to-ressource`
`ssh://url_to_server`

**Comment by phaumer** [comment]
Hello. We made the setting available for workspace settings in 1.2.6 now available on the Marketplace.
