### ISSUE TITLE
Report Writer support is missing

### ISSUE THREAD

**Issue by egkareem** [IBM/zopeneditor-about#145]
Thank you for the product.
I noticed that the Report Writer for COBOL feature is missing. I could not locate any reference to this in the limitations documentation: [https://ibm.github.io/zopeneditor-about/Docs/knownissues.html#cobol](url)
It would be nice to at least not make the editor think the the code represents an error. Maybe choosing some color to indicate that the feature is not supported.

**Comment by FALLAI-Denis** [comment]
Hi,

I am currently studying textmate grammars and VS Code language extension. 
I saw that it was possible to define extensions to manage languages which make it possible to extend an already defined language: they are "injectors".

Report Writer defines an extension to the COBOL language and I think this should be handled with an injector type language extension, complementary to Z Open Editor, so that the specifics of Report Writer does not impact the support of the COBOL language by itself, (for those who do not use Report Writer).

**Comment by egkareem** [comment]
I assume that this may get implemented in the future. Anyway, thank you.

**Comment by phaumer** [comment]
Thanks for submitting this issue. We have to see if there is enough demand for this. We did get the request to be more agnostic for other pre-compiler content as well and that might be a first goal to achieve.

**Comment by FALLAI-Denis** [comment]
For my part, I did some experiments.

Z Open Editor has two COBOL source language processing mechanisms:
* a COBOL language server
* a COBOL TextMate grammar : `./cobol-textmate/cobol.json`

I don't know the relationship between TextMate grammar and Language Server. The use of COBOL grammar always seems active, even in the presence of the COBOL language server.

By analyzing the COBOL TextMate grammar, I saw that it supported elements specific to the Report Writer syntax.

By default, the COBOL language server is active, but it does not fully manage the syntaxes related to Report Writer, and in particular does not know how to identify the role of Report Writer elements in the COBOL program as a whole. This is what generates all the problems in the editor:

![image](https://user-images.githubusercontent.com/63861965/129870535-bbd96956-a8da-4bb3-bf6f-a206cee05b92.png)

![image](https://user-images.githubusercontent.com/63861965/129869962-88d5ecf4-f163-4f53-844a-761b90b39e00.png)

If we deactivate the COBOL language server, (`Ctrl + Shift + P` / `Pause the COBOL language server`), then only the TextMate grammar is used. In this case, the Report Writer elements seems to be well recognized:

![image](https://user-images.githubusercontent.com/63861965/129870624-a8f01da7-4797-46a4-932f-63fa07a5357b.png)

On the other hand, when the COBOL language server is deactivated, all the facilities that depend on it are lost:
* search for the definition of a data element
* search for uses of a data element
* renaming of an identifier
* ... 

What I can suggest to you is to work on your COBOL Report Writer sources by disabling the COBOL language server to avoid reporting problems. 

While there is a command to suspend the COBOL language server, I have not found a command to re-enable it ... it seems that it is enough to close the source file and then reopen it to re-enable the language server COBOL at its level (this seems to be a mechanism attached to the source being edited).

The COBOL language server is developed in Java, and runs in an Eclipse context, code sharing with IDz / ZOD, confer `./language-server/plugins`. Some of these plugins would have to be supplemented / rewritten to include Report Writer elements.

You might be better off getting Report Writer taken into account in Z Open Editor, a free of charge solution, by posting an RFE on the [IBM RFE Community](https://www.ibm.com/developerworks/rfe/) at the level of `IBM Developer for z/OS, including Enterprise Edition`, charged solution, which will benefit in waterfall to Z Open Editor.

For information, RFE regarding Report Writer:
* [87995 - Support Cobol Report Writer syntax in RDz](https://www.ibm.com/developerworks/rfe/execute?use_case=viewRfe&CR_ID=87995), product: _IBM Developer for z/OS, including Enterprise Edition_, status: **Declined**
* [70792 - Support Cobol Report Writer syntax in RDz](https://www.ibm.com/developerworks/rfe/execute?use_case=viewRfe&CR_ID=70792), product: _IBM Developer for z/OS, including Enterprise Edition_, status: **Declined**
* [146921 - Support for Cobol Report Writer statements](https://www.ibm.com/developerworks/rfe/execute?use_case=viewRfe&CR_ID=146921), product: _Application Discovery and Delivery Intelligence_, status: Uncommitted Candidate

**Comment by egkareem** [comment]
Thank you very much for the detailed answer.

**Comment by egkareem** [comment]
Thank you.

________________________________
