### ISSUE TITLE
extension zopeneditor from IBM has conflicting functionality

### ISSUE THREAD

**Issue by izzyizorizzyaint** [IBM/zopeneditor-about#147]
## Development environment used

- Z Open Editor version:
- Editor Platform
  - [x] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version:
- Operating System (on which VS Code runs such as Windows 10 2004, otherwise name and version of platform such as OpenShift v4.3):
- Java Version (when using VS Code or Theia, execute `java -version` and paste the details here):
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html) how to get them): yes/no

## Problem Description

Detailed steps for reproducing the problem:

1. First step

### Observed behavior

-

### Expected behavior

-

**Comment by phaumer** [comment]
@izzyizorizzyaint it looks like you did not finish writing this issue? I will close it for now. Feel free to reopen it with more content.
