### ISSUE TITLE
Outline view wrong/inconsistent for HLASM Programs

### ISSUE THREAD

**Issue by cybersorcerer** [IBM/zopeneditor-about#148]
Hi Guys,

the outline view for HLASM programs is not working as expected. Have a look at the screenshot of a very old assembler program below:

IBM Z Open Editor 1.2.6
VS Code 1.59.1

Label SETTIME is part of the OUTLINE view but ALL others are not. There are  much more than the two addtional labels shown here, before SETTIME and after SETTIME. DSECTS seem to work, EQU don't. I don't know what the code is searching here and what makes it stop searching. 

![sc4](https://user-images.githubusercontent.com/33680802/130181186-33b58e17-0751-4538-812e-da3c8cd8e866.png)

Instruction statements must consist of one to four entries in the statement field.

They are: 

- name entry
- An operation entry
- An operand entry
- A remarks entry

Here is a shot of a more recent hlasm program with SPM's etc. Func is a macro written by my self that does some housekeeping all my "functions" are called by a macro named CallFunc. None of those name entries are in the outline view, but they should be in there. I know this is not a bug but an enhancement but anyway, i suggest you allow for some regular expressions as part of the extentions settings to allow the user to define what should be shown in the outline view.

![sc5](https://user-images.githubusercontent.com/33680802/130183927-6e405baf-c23e-4957-9ed4-2ea7275dbff0.png)

greetings 

Ronny

**Comment by phaumer** [comment]
We improved this in v1.4.1. See the [Know issues](https://ibm.github.io/zopeneditor-about/Docs/knownissues.html#hlasm) list for what is left. Let's open new issues for other important items to fix.

**Comment by kkrein** [comment]
Ich bin derzeit nicht im Büro. Ich kehre zurück am  06.12.2021.
Während meiner Abwesenheit bitte bei Postkorb SCM-Admin melden!

Die Rückmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [IBM/zopeneditor-about] Outline view wrong/inconsistent for HLASM
Programs (#148)

____________________________________________________________________________________________
Gesendet (c) GRZ/RSG Linz 2021 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angeführten Absender via E-Mail
dient ausschließlich Informationszwecken. Rechtsgeschäftliche Erklärungen
dürfen über dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------

**Comment by cybersorcerer** [comment]
@phaumer Hi Peter this does look much better now. Thanks! 
> We improved this in v1.4.1. See the [Know issues](https://ibm.github.io/zopeneditor-about/Docs/knownissues.html#hlasm) list for what is left. Let's open new issues for other important items to fix.
