### ISSUE TITLE
Provide REXX language support

### ISSUE THREAD

**Issue by bearou** [IBM/zopeneditor-about#15]
Is this the place for a tiny improvement request ?
Hi... I have been using this extension for a few weeks now, for COBOL only. It's great!
However, my workday is 2/3 Rexx, so I wonder how big a task it would be to include this language as well!? 
Brgds Claus

**Comment by bearou** [comment]
Duplicate of #11

**Comment by kokosnuss** [comment]
Would love to have a modern REXX IDE!

**Comment by phaumer** [comment]
We added REXX support in version 1.2.0 available now. @bearou and @kokosnuss let us know what you think.

**Comment by bearou** [comment]
Thank you ever so much! This is exactly what I was dreaming about. We will give you more feedback the coming weeks, when we get to know it a little better.
