### ISSUE TITLE
COBOL - Missing most of DEBUG-ITEM variables in COBOL Language Server

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#156]
## Development environment used

- Z Open Editor version: 1.2.6
- Editor Platform
  - [X] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version: 1.60.0
- Operating System: Windows 10 
- Java Version: any
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached: no

## Problem Description

![image](https://user-images.githubusercontent.com/63861965/132093078-483fad4b-1646-4739-996f-295973054eda.png)

### Observed behavior

The COBOL Language Server does not recognize most of the variables of the DEBUG-ITEM special register.

These variables are well recognized by the COBOL grammar of the textmate cobol.json file.

### Expected behavior

Full support of the DEBUG-ITEM special register by the COBOL Language Server.

**Comment by FALLAI-Denis** [comment]
For information, I also validate all special registers defined by IBM Enterprise Cobol 6.3:
* missing `JNIENVPTR` both in textmate grammar and in COBOL Language Server
* missing `JSON-STATUS` only in textmate grammar

**Comment by phaumer** [comment]
Added to Z Open Editor v2.0.0
