### ISSUE TITLE
COBOL - Toggle line comment not working for non-blank lines

### ISSUE THREAD

**Issue by ian-burnett** [IBM/zopeneditor-about#157]
## Development environment used

- Z Open Editor version: 1.2.6
- Editor Platform
  - [X] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version: 1.60.0
- Operating System: Windows 10 Enterprise 21H1
- Java Version: Java(TM) SE Runtime Environment (build 8.0.6.7 - pwa6480sr6fp7-20200312_01(SR6 FP7))
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached: no

## Problem Description

Detailed steps for reproducing the problem:

1. Create a basic COBOL file and open for editing
2. Position the cursor on the line beginning "01"
3. Use either the command "Toggle line comment" or keyboard shortcut Ctrl + / to toggle the line comment

Sample basic program: 

```cobol
       identification division.
       program-id.    mytest.

       data division.
       working-storage section.

      *    Return code
       01  rc pic s9(9) binary.
```

### Observed behavior

- Line is incorrectly indented and not marked as a comment (asterisk starts in column 13):

```cobol
            *  01  rc pic s9(9) binary.
```

- Executing the "toggle" again makes things worse:

```cobol
                  * *  01  rc pic s9(9) binary.
```

### Expected behavior

- Asterisk or slash should be toggled in column 7
- Indentation of code should remain unchanged

See also [Comment lines](https://www.ibm.com/docs/en/cobol-zos/6.3?topic=b-comment-lines) in the COBOL documentation.

**Comment by phaumer** [comment]
Added that in v1.4.1

**Comment by ian-burnett** [comment]
Works for me thanks!

**Comment by kkrein** [comment]
Ich bin derzeit nicht im Büro. Ich kehre zurück am  06.12.2021.
Während meiner Abwesenheit bitte bei Postkorb SCM-Admin melden!

Die Rückmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [IBM/zopeneditor-about] COBOL - Toggle line comment not working for
non-blank lines (#157)

____________________________________________________________________________________________
Gesendet (c) GRZ/RSG Linz 2021 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angeführten Absender via E-Mail
dient ausschließlich Informationszwecken. Rechtsgeschäftliche Erklärungen
dürfen über dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------

**Comment by davidkcoblentz** [comment]
Yes, works great even if the selected lines have some comments already.  Great Work!!

Thank you,
***@***.***
