### ISSUE TITLE
COBOL - Language Server excessive CPU and memory consumption

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#158]
## Development environment used

- Z Open Editor version: 1.2.6
- Editor Platform
  - [X] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version: 1.60.0
- Operating System: Windows 10 "1909" Pro x64
- Java Version: Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached: yes

[zopeneditor-20210912-103757.log](https://github.com/IBM/zopeneditor-about/files/7153591/zopeneditor-20210912-103757.log)

## Problem Description / Observed behavior

For some unidentified, but frequent, reason, the process assigned to the COBOL Language Server consumes a lot of CPU (loop?) and a lot of memory.

This problem is probably related to the difficulties of ZOE in handling conditional compilation as well as the use of PERFORM THRU on COBOL Sections.

![image](https://user-images.githubusercontent.com/63861965/133069513-6b9fe4e3-08a4-4481-b9da-56a106f92dd8.png)

Reloading the VS Code window, `Ctrl+R`, stops (temporarily) the CPU and memory consumptions.

![image](https://user-images.githubusercontent.com/63861965/133069979-33b79337-427b-495b-91fc-262c4a0360bd.png)

### Expected behavior

The COBOL Language Server should stop by itself, issuing an alert, after a certain analysis time.

**Comment by phaumer** [comment]
We believe we were able to fix these problem in v2.0.0, by refining event handling in the language server. Could you try this again and let us know?
