### ISSUE TITLE
Unable to add breakpoint in cobol file

### ISSUE THREAD

**Issue by tomcec** [IBM/zopeneditor-about#159]
## Development environment used

- Z Open Editor version: 1.2.6
- Editor Platform
  - [x] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version: 1.55.2
- Operating System (on which VS Code runs such as Windows 10 2004, otherwise name and version of platform such as OpenShift v4.3): Windows 10
- Java Version (when using VS Code or Theia, execute `java -version` and paste the details here):
java version "1.8.0_301"
Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
Java HotSpot(TM) Client VM (build 25.301-b09, mixed mode, sharing)
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html) how to get them): no

## Problem Description
Unable to add breakpoints in cobol file when Debugger for Mainframe extension is installed. After disabling IBM Z Open Editor, adding breakpoints works well.

Detailed steps for reproducing the problem:

1. Install extensions Debugger for Mainframe and IBM Z Open Editor
2. Try to add breakpoint in cobol file

### Observed behavior
Unable to add breakpoint

-

### Expected behavior
Able to add breakpoint

-

**Comment by phaumer** [comment]
@tomcec thanks for trying our editor. The extension you mentioned is from a different company. We support our editor with IBM's Debugger (https://www.ibm.com/products/debug-for-zos) for VS Code as well as CodeReady Workspaces and the IBM Wazi Developer offering.

**Comment by spgennard** [comment]
fyi - the two extensions can't work together as the "IBM Z Open Editor" uses a language id of 'cobol' but the Broadcom debugger for mainframe extension uses the uppercase 'COBOL' as the language id.   You can see this checking the "features it contributes" (activation event onLangauge:COBOL).
