### ISSUE TITLE
Allow specifying a custom file extension for copybook lookup

### ISSUE THREAD

**Issue by phaumer** [IBM/zopeneditor-about#16]
The editor currently only works with local copybook files with the extension .cpy. 
Make this extension configurable, i.e. allow specifying an array of different potential extensions.

**Comment by phaumer** [comment]
@Morridt I filed this issue here as discussed today.

**Comment by przemekherok** [comment]
Hi Peter,

regarding the case #23, changing the extension didn't solve the problem

![image](https://user-images.githubusercontent.com/43341440/69781330-17d46a80-11ae-11ea-998d-e38014b13224.png)

**Comment by phaumer** [comment]
@przemekherok looking at your screen shot again I see that the .vscode directory with the property groups is in a sub-directory. Are you using VS Code multi-root workspaces? Did you see the instructions for those here: copying the property groups into the .code-workspace file)? https://ibm.github.io/zopeneditor-about/Docs/setting_propertygroup.html#setting-ibm-z-open-editor-property-groups-in-multi-root-workspaces

If this is a single root workspace then you need to open the workspace one level down so that the .vscode directory is at the top-level. Only then will the settings be read.

**Comment by FALLAI-Denis** [comment]
Perhaps not only « one » extension but « many » extensions (a list = a property of type array in settings.json) for cobol copybooks / PL/I includes / hlasm copys + macros.

**Comment by phaumer** [comment]
@Morridt this has now been done for v1.0.3. Let us know if this works for you.
