### ISSUE TITLE
Cannot switch to non Z Open Editor LSP languages

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#164]
## Development environment used

- Z Open Editor version: 1.2.7
- Editor Platform
  - [X] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version: 1.60.2
- Operating System: Windows 10 1909 x64
- Java Version: java version "1.8.0_102"
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html) how to get them): no

## Problem Description

1. With Zowe Explorer, access to`<userid>.COBOL.JCL` and open a member wich is a JCL
2. Member is edited with Z Open Editor
2. Rules `files.associations` defined for Zowe Explorer assign `COBOL` Language Mode to JCL...
3. Z Open Editor start "COBOL Language Server".
4. Change "Language Mode" to `JCL`
5. Z Open Editor still use "COBOL Language Server".

### Observed behavior

All text in JCL is in error due to "COBOL Language Server".

### Expected behavior

When the Language Mode is changed at editor level, Z Open Editor should stop the active Language Server and start (or not) a new Language Server suitable for the new Language Mode.

**Comment by phaumer** [comment]
@FALLAI-Denis The `zopeneditor.datasets.cobolDatasets` setting is just a convenience, but not required by VS Code to start the language server. You could remove all values from `zopeneditor.datasets.cobolDatasets` and set the `files.associations` setting with the wildcard settings you like to use.

**Comment by FALLAI-Denis** [comment]
@phaumer I do not understand your answer, can you detail it?

Whatever the mechanism used, an editor is associated with a language, and Z Open Editor automatically starts the associated Language Server defined for this language.
The language determined when opening the source text in the editor may have been incorrectly determined, and therefore the Language Server started may not be appropriate, which generates a large number of anomalies during the analysis, and makes the language use of editor not possible.
VS Code allows you to change the Language Mode to correct a bad determination. This must reinitialize Z Open Editor at the level of the editor concerned, and therefore stop the current Language Server, and possibly start another appropriate for the new language selected.

There will always be cases where the Language Mode is incorrectly determined, and Z Open Editor has to support the change of Language Mode and adapt to the new selected language.

Note that the initial problem comes from Zowe Explorer and not from Z Open Editor: in this case the files do not have an extension (example ".cbl"), and it is Zowe Explorer which associates a language in relation to in the name of the data set name.
Example :
- either the data set name: user.cobol.jcl
- the correspondence rule defined for Zowe Explorer determines that it is a PDS of "cobol"
- but in fact it is a PDS of "jcl"
The same problem would occur with an "anonymous" PDS that could contain members of any type of language.

**Comment by phaumer** [comment]
@FALLAI-Denis sorry for the slow reply. 

I thought this item was only about setting the association in the first place and not about switching languages. The issue here is also related to the fact that we actually do not have a language server for JCL, so switching languages does only switch syntax highlighting in the client, but does not switch off the COBOL LSP association to the open document. And your suspicion is correct, we do not process the `onDidCloseTextDocument` event as we should. This is not a problem when switching from COBOL to PL/I, for example, as the PL/I association does overwrite the COBOL one in that case. However, I agree with you that we need to allow switching to any of the other VS Code languages (and our JCL syntax highlighting) as well. So I reopen this as a defect. Thanks for clarifying the issue.

**Comment by phaumer** [comment]
Fixed in v1.4.1.

**Comment by kkrein** [comment]
Ich bin derzeit nicht im Büro. Ich kehre zurück am  06.12.2021.
Während meiner Abwesenheit bitte bei Postkorb SCM-Admin melden!

Die Rückmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [IBM/zopeneditor-about] Cannot switch to non Z Open Editor LSP
languages (#164)

____________________________________________________________________________________________
Gesendet (c) GRZ/RSG Linz 2021 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angeführten Absender via E-Mail
dient ausschließlich Informationszwecken. Rechtsgeschäftliche Erklärungen
dürfen über dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------
