### ISSUE TITLE
All languages - Display the name of the active Zowe CLI profile in status bar

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#165]
## Description of the enhancement requested

Z Open Editor works with a Zowe CLI profile to access mainframe resources (COPYBOOK / INCLUDE).

This profile is either the RSE or z/OSMF Zowe CLI profile declared as the default profile, or the profile explicitly declared in the `zopeneditor.zowe` parameter.

We would like the Zowe profile used by Z Open Editor to be displayed in the status bar, in the form "type: name", whether it is an explicitly declared profile, or the default implicit profile.

**Comment by phaumer** [comment]
That is a great idea that we should consider adding.

**Comment by FALLAI-Denis** [comment]
![image](https://user-images.githubusercontent.com/63861965/174033413-b81989a9-5c43-45d2-a426-44eab1edc6eb.png)

And can be masked optionally:

![image](https://user-images.githubusercontent.com/63861965/174034000-e53b00ff-f9dc-4f5b-bfe7-82198103377c.png)

Great !
Thanks a lot !
