### ISSUE TITLE
Datasets setting missing for Rexx highlighting

### ISSUE THREAD

**Issue by Cieronpowell** [IBM/zopeneditor-about#172]
All other language support has a setting option zopeneditor.datasets.* 
Which enables you to set the LLQ of datasets to highlight.

E.g. 
zopeneditor.datasets.jclDatasets might contain ".JCL" or ".CNTL"

This option is not available for Rex, highlighting is only available in .REXX datasets or to be turned on manually.

This is a bug and should be consistent across all languages.

## Development environment used

- Z Open Editor version:
- Editor Platform
  - [/] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version:
1.53.0
- Operating System (on which VS Code runs such as Windows 10 2004, otherwise name and version of platform such as OpenShift v4.3):
Windows 
- Java Version (when using VS Code or Theia, execute `java -version` and paste the details here): 1.8.0_241
- [/] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html) how to get them): no

**Comment by gplambert** [comment]
Thank you for your interest and use of our editor.  As our REXX editor functionality is new, it does not yet have all the functionality of the other languages, however, we are working to enhance REXX editing to more closely align with the other languages.

**Comment by bknaysi** [comment]
To provide an update, we expect to add remote file associations for REXX into the editor soon. The behavior will be similar to the other languages, as you mentioned above.

**Comment by FALLAI-Denis** [comment]
New in version 2.1.0:

![image](https://user-images.githubusercontent.com/63861965/174429415-ae212043-9e5f-4855-9307-d60f5b48b977.png)

**Comment by bradleyknaysi** [comment]
@Cieronpowell - As Denis points out, your requested enhancement is now available!

**Comment by bknaysi** [comment]
@Cieronpowell - As Denis points out, your requested enhancement is now available!
