### ISSUE TITLE
JCL - Offer a "submit JCL" command from the editor

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#173]
## Description of the enhancement requested

When Z Open Editor is used to edit a JCL type file (language mode is JCL), a "Submit JCL" option should be offered in the contextual menu associated with the editor (right click).

Activating this choice should trigger a call to the zowe jobs submit localfile function (or its RSE equivalent), in SDK mode for performance reasons.
The Zowe / RSE profile to be used to carry out the action is the one currently active (cf. #165).

Before submitting the job, Z Open Editor must ensure that the file being edited is saved, (unless Z Open Editor is able to submit the job from the version being modified).

The job submission must be done without waiting for its activation or its end of execution, but Z Open Editor should retrieve the jobib returned during the submission, and display a notification with a clickable link allowing to consult the report in the Zowe Explorer extension for VS Code.

The Zowe Explorer extension for VS Code offers a function to submit a JCL, but it can only be used from the list of files or members from the tree view.
When working in a workspace, which is a Git repository, there is no direct way to submit a JCL for execution on the z/OS machine.
This is a feature that we are missing.

**Comment by JillieBeanSim** [comment]
Hey @FALLAI-Denis I was looking through the issues here and wanted to mention that Zowe Explorer has a command pallet option for submitting local JCL `Zowe Explorer: Submit JCL` that will submit the text file in the active editor as a job, prompting you for the profile to use for the submission.

**Comment by FALLAI-Denis** [comment]
Hi @JillieBeanSim,

Thanks for the information.
However, being able to trigger the submission of a JCL from a context menu (right click) seems to us to be much more user-friendly.
Perhaps there is not much missing to make the link between a context menu and the command already in place?

**Comment by FALLAI-Denis** [comment]
Hi,

This functionality is now supported by Zowe Explorer.
