### ISSUE TITLE
COBOL - Syntax Highlighting - Reference Modification (1:3)

### ISSUE THREAD

**Issue by davidkcoblentz** [IBM/zopeneditor-about#177]
### Development environment used
Version: 1.61.1 (user setup)
Commit: c13f1abb110fc756f9b3a6f16670df9cd9d4cf63
Date: 2021-10-14T01:19:42.089Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.17763

IBM Z Open Editor extension:
V1.2.7

### Problem Description
Part of COBOL syntax allows Reference Modification.  Reference modifiers let you easily refer to a substring of a data item. For example the syntax looks like this: 
DISPLAY 'Month: ' BIRTH-DATE (1:2)  <--Reference Modification

Example from IBM TSO Editor syntax highlighting:
![image](https://user-images.githubusercontent.com/80063515/137562646-3a2d3b10-70af-48f3-a7ac-7951ecead6bd.png)

Example from IBM Z Open Editor syntax highlighting:
![image](https://user-images.githubusercontent.com/80063515/137562731-c047322a-7176-4a4b-a0f0-73a637da5ee1.png)

### Observed Behavior
I noticed IBM Z Open Editor colors the first number as White and the second number after the colon is Green, a different color.  Shouldn't both numbers be the same color?

### Expected Behavior
I expected both Reference Modifier numbers within parenthesis to be colored the same.

**Comment by FALLAI-Denis** [comment]
Hi,

The colorization problem of the "position" part appears when the numerical value is immediately followed by the ":" character. If we insert a space before the ":" character, the colorization is ok :
![image](https://user-images.githubusercontent.com/63861965/137620096-9610a966-71e8-4911-bd0b-7200b491445c.png)

The problem stems from the textmate file for COBOL, and I think in particular that it is at the level of this regular expression:
```
      "match": "(\\-|\\+)?([0-9]+)(?=\\s|\\.$|,|\\))",
      "name": "constant.numeric.cobol"
```
A numeric integer constant must be followed by a space, a period, or a closing parenthesis. The ":" character is not expected.
The comma character is also missing.
If we modify it, (and reload Window):
```
      "match": "(\\-|\\+)?([0-9]+)(?=\\s|\\.$|,|\\)|\\:|\\,)",
      "name": "constant.numeric.cobol"
```
![image](https://user-images.githubusercontent.com/63861965/137620955-d8210596-6ffb-4f98-9c60-d70816b5782d.png)

Note: in the latest versions of VS Code you can activate the brakets colorization:
![BracketPairColorization](https://user-images.githubusercontent.com/63861965/137619530-3a7b3c73-5baf-4f53-a816-ded4ee7cac0d.png)

**Comment by FALLAI-Denis** [comment]
I think posting issue here is sufficient. 
IBM team will assign it a label: bug or enhancement.

**Comment by phaumer** [comment]
Thanks for the issue and suggestions.

**Comment by phaumer** [comment]
Fixed in v1.4.1

**Comment by kkrein** [comment]
Ich bin derzeit nicht im Büro. Ich kehre zurück am  06.12.2021.
Während meiner Abwesenheit bitte bei Postkorb SCM-Admin melden!

Die Rückmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [IBM/zopeneditor-about] COBOL - Syntax Highlighting - Reference
Modification (1:3) (#177)

____________________________________________________________________________________________
Gesendet (c) GRZ/RSG Linz 2021 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angeführten Absender via E-Mail
dient ausschließlich Informationszwecken. Rechtsgeschäftliche Erklärungen
dürfen über dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------

**Comment by kkrein** [comment]
Ich bin derzeit nicht im Büro. Ich kehre zurück am  06.12.2021.
Während meiner Abwesenheit bitte bei Postkorb SCM-Admin melden!

Die Rückmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [IBM/zopeneditor-about] COBOL - Syntax Highlighting - Reference
Modification (1:3) (#177)

____________________________________________________________________________________________
Gesendet (c) GRZ/RSG Linz 2021 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angeführten Absender via E-Mail
dient ausschließlich Informationszwecken. Rechtsgeschäftliche Erklärungen
dürfen über dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------

**Comment by davidkcoblentz** [comment]
Works great!!  Thank you for fixing that!!  I am always looking forward to using IBM Z Open Editor with VS Code! It’s awesome!

Thank you,
***@***.***
