### ISSUE TITLE
All languages - Removed dependency on Zowe Explorer

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#179]
## Description of the enhancement requested

We have an alternative solution to Zowe Explorer / Zowe CLI / RSE to access the z/OS mainframe provided by another vendor. This solution currently works under Eclipse.
We asked this vendor to port his solution currently under Eclipse for operation under VS Code.
This concerns its debugging, performance profiling and data manipulation products, as well as access to the z/OS mainframe which offers the same functionality as Zowe Explorer, including a 3270 emulator.

IBM Z Open Editor requires the use of Zowe Explorer to perform searches for COPYBOOKs / INCLUDEs.

We want this dependency to be removed, or at least to be one option among others, and therefore that IBM Z Open Editor offers an API or a service contract allowing you to use the solution of your choice to interface with the z/OS mainframe.

**Comment by phaumer** [comment]
Hello. This is not something that we have on our radar. We would have to find a business case for us for investing in such an API.
 
APIs for extensibility we do in open source in Zowe Explorer. Here [we provide APIs to extend Zowe Explorer](https://github.com/zowe/vscode-extension-for-zowe/blob/master/docs/README-Extending.md) with alternative data providers (e.g. ftp instead of z/OSMF), access to the Zowe CLI profiles cache, the ability to add views and commands, etc. However, it is all centered around Zowe.

**Comment by FALLAI-Denis** [comment]
Hi @phaumer, 

The business case is in the expression of the demand: we already have a long-standing solution (2006) which provides the same functionalities as z/OSMF or RSEd on the one hand, and that Zowe Explorer on the other hand. But today this solution only supports WEB or Eclipse interfaces. We asked our vendor to port it to VS Code.

In addition, there is the Nazaré program at IBM which specifies that the User must be free to assemble the tools of his choice, and that no tool must impose another.

I wonder about the dependence between Z Open Editor and Zowe Explorer...
In fact, Z Open Editor is sufficient on its own except to find the INCLUDEs / COPYBOOKs.
- for Workspace-local INCLUDEs / COPYBOOKs, is Zowe Explorer required?
- for remote INCLUDEs / COPYBOOKs (on z/OS system), Z Open Editor needs a mechanism to access external resources. In principle, this mechanism is provided more by Zowe CLI (z/OSMF or RSE) than by Zowe Explorer?

For the search for remote INCLUDEs / COPYBOOKs, what would therefore be needed is a pivot system between Z Open Editor and the remote system access mechanism, with a default implementation to use Zowe Explorer, but not imperative :
- the Z Open Editor extension is intended for an "anonymous" remote access API
- a third-party extension exposes this remote access API: this can be Zowe Explorer or another extension, which has to be developed by the User to interface with an existing system, (we could for example propose a mechanism based on pure FTP or on SSH to access the z/OS mainframe rather than going through Zowe Explorer).

**Comment by kkrein** [comment]
Ich bin derzeit nicht im Büro.
Während meiner Abwesenheit bitte bei Postkorb SCM-Admin melden!

Die Rückmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [IBM/zopeneditor-about] All languages - Remove dependency on Zowe
Explorer (Issue #179)

____________________________________________________________________________________________
Gesendet (c) GRZ/RSG Linz 2021 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angeführten Absender via E-Mail
dient ausschließlich Informationszwecken. Rechtsgeschäftliche Erklärungen
dürfen über dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------

**Comment by phaumer** [comment]
A key reason why we made Zowe Explorer a dependency was to allow Z Open Editor to extend Zowe Explorer with the RSE API protocol via the Zowe Explorer APIs, which is our recommended solution. A requirement to disable all Zowe Explorer dependencies and allow uninstalling Zowe Explorer is something we could look into (if feasible as currently we define the dependency as part of the package.json file that VS Code requires for activation in the right order etc.). 

Providing APIs for others to plugin to Z Open Editor we are currently not interested in providing outside of any formal business partnerships as that is something we are doing in Zowe as part of the IBM Zowe involvement.
