### ISSUE TITLE
COBOL - Improve text colorization for syntax highlighting by textmate grammar

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#182]
## Description of the enhancement requested

Currently the textmate grammar used for COBOL treats the source line globally. 

The consequence of this is to color the identification zone identically to the syntactic element which precedes this zone.
In the same way, the line number zone is interpreted (wrongly) according to its content: integer, text, keyword...

![image](https://user-images.githubusercontent.com/63861965/140025248-a6afd0bc-ba51-428f-8c23-ff9940f31aa1.png)

The COBOL texmate grammar should start by splitting the line into 3 parts:
- line number area, columns 1 to 6 in fixed format 80 columns, to be colored as such independently of its content,
- COBOL language area, columns 7 to 72 in fixed format 80 columns, to be colored by analysis of its content,
- identification area, column 73 to 80 in fixed format 80 columns, to be colored as such independently of its content.

The result might look like this (test on a partial COBOL grammar):

![image](https://user-images.githubusercontent.com/63861965/140026436-e1e35d4e-66ef-489e-ad07-bcdd10a1d777.png)

Already this would give better readability of the COBOL source code, and for example would make it possible to better identify a badly aligned identification label (shifted to the left of column 73).
But it would also make it possible to prepare a future switch to free format for COBOL source lines: no more line number area or identification area, or even to be compatible with the extended format of the IBM COBOL compiler for Linux, (fixed format 252 columns).

Thanks.

**Comment by kkrein** [comment]
Ich bin derzeit nicht im Büro.
Während meiner Abwesenheit bitte bei Postkorb SCM-Admin melden!

Die Rückmeldung bezieht sich auf ein Mail mit folgendem Thema:
[IBM/zopeneditor-about] COBOL - Improve text colorization for syntax
analysis by textmate grammar (Issue #182)

____________________________________________________________________________________________
Gesendet (c) GRZ/RSG Linz 2021 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angeführten Absender via E-Mail
dient ausschließlich Informationszwecken. Rechtsgeschäftliche Erklärungen
dürfen über dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------

**Comment by gecolbert** [comment]
This enhancement would be helpful to our development.  We use the line number area and the identification area to link program changes to our change management documentation (primitive meta data).  Having them colored differently would make the code easier to read.

**Comment by kkrein** [comment]
Ich bin derzeit nicht im Büro. Ich kehre zurück am  06.12.2021.
Während meiner Abwesenheit bitte bei Postkorb SCM-Admin melden!

Die Rückmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [IBM/zopeneditor-about] COBOL - Improve text colorization for syntax
highlighting by textmate grammar (Issue #182)

____________________________________________________________________________________________
Gesendet (c) GRZ/RSG Linz 2021 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angeführten Absender via E-Mail
dient ausschließlich Informationszwecken. Rechtsgeschäftliche Erklärungen
dürfen über dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------

**Comment by FALLAI-Denis** [comment]
Solved since ZOE 3.0.x
