### ISSUE TITLE
HLASM - highlighting issues if there is # or $ in macro name

### ISSUE THREAD

**Issue by JeffyOLOLO** [IBM/zopeneditor-about#185]
## Development environment used

- Z Open Editor version: 1.4.0
- Editor Platform
  - Visual Studio Code
- Editor Platform Version:
```
Version: 1.62.2 (user setup)
Commit: 3a6960b964327f0e3882ce18fcebd07ed191b316
Date: 2021-11-11T20:56:38.428Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042
```
- Operating System: Windows 10 20H2
- Java Version:
```
java version "1.8.0_301"
Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.301-b09, mixed mode)
```

## Problem Description

If macro name contains #, starting from that # name is highlighted as an operand. The same for $, except when it's the first symbol.

![image](https://user-images.githubusercontent.com/34167060/141971035-fdde1569-75b9-494e-98c6-f6034757dfc6.png)

**Comment by kkrein** [comment]
Ich bin derzeit nicht im Büro. Ich kehre zurück am  06.12.2021.
Während meiner Abwesenheit bitte bei Postkorb SCM-Admin melden!

Die Rückmeldung bezieht sich auf ein Mail mit folgendem Thema:
[IBM/zopeneditor-about] HLASM - highlighting issues if there is # or $ in
macro name (Issue #185)

____________________________________________________________________________________________
Gesendet (c) GRZ/RSG Linz 2021 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angeführten Absender via E-Mail
dient ausschließlich Informationszwecken. Rechtsgeschäftliche Erklärungen
dürfen über dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------

**Comment by FALLAI-Denis** [comment]
Hi,

Probably problem in texmate rule... # character not expected in 4th parts of regular expression:

![image](https://user-images.githubusercontent.com/63861965/141972531-2dcb0dec-0dfc-4a6e-9d87-c279c8d8f8dc.png)

Try with this modification:

![image](https://user-images.githubusercontent.com/63861965/141973052-63a6daae-af96-4014-bb18-7db5aeed243c.png)

![image](https://user-images.githubusercontent.com/63861965/141973474-2b849c12-3d57-4642-bf03-70cc3bd3ec65.png)

**Comment by kkrein** [comment]
Ich bin derzeit nicht im Büro. Ich kehre zurück am  06.12.2021.
Während meiner Abwesenheit bitte bei Postkorb SCM-Admin melden!

Die Rückmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [IBM/zopeneditor-about] HLASM - highlighting issues if there is # or $
in macro name (Issue #185)

____________________________________________________________________________________________
Gesendet (c) GRZ/RSG Linz 2021 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angeführten Absender via E-Mail
dient ausschließlich Informationszwecken. Rechtsgeschäftliche Erklärungen
dürfen über dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------

**Comment by phaumer** [comment]
We improved this in v1.4.1. See the [Know issues](https://ibm.github.io/zopeneditor-about/Docs/knownissues.html#hlasm) list for what is left. Let's open new issues for other important items to fix.

**Comment by JeffyOLOLO** [comment]
Hi, thanks, it works.
