### ISSUE TITLE
COBOL Unumbering sequence numbers Changes GIT Source Control Color Bar Indicators to Blue  

### ISSUE THREAD

**Issue by davidkcoblentz** [IBM/zopeneditor-about#188]
## Development environment used

- VS Code - Z Open Editor version:
- Version: 1.62.2 (user setup)
Commit: 3a6960b964327f0e3882ce18fcebd07ed191b316
Date: 2021-11-11T20:56:38.428Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.17763

### Active Extensions
Extension | Author (truncated) | Version
-- | -- | --
ISPW | BMC | 1.0.1
ccf | Bro | 0.4.0
solargraph | cas | 0.23.0
bracket-pair-colorizer | Coe | 1.0.61
code-runner | for | 0.11.6
zopeneditor | IBM | 1.4.0
gnucobol-debug | Ole | 2.31.37
ruby | reb | 0.28.1
vscode-ruby | win | 0.28.0
vscode-extension-for-zowe | Zow | 1.20.0

</body>
</html>

## Problem Description

Detailed steps for reproducing the problem:

1. Have a GIT local repository that is a associated with a server GIT repository. 
2. Open COBOL source that contains numbering or partial numbering
3. Add lines of code.  In the left margin a **green** vertical bar indicates added line(s)
4. Modify a couple of lines.  A **blue** vertical bar indicates modified lines. See example below.
5. Use the **Unnumber sequence numbers**. Previous green vertical bars are changed to blue which is incorrect. 

### Observed behavior
Before **Unnumber sequence numbers** the added lines are colored GREEN and the moified lines are colored BLUE but after the unnum they all turn blue but this does not seem accurate. 

Before Unnumber sequence numbers 
![image](https://user-images.githubusercontent.com/80063515/142510811-8965c8f6-58b9-4085-8cb2-fb7025bffbf0.png)

### Expected behavior
Added lines should stay GREEN and all other modified lines due to unnumbering should be BLUE. The added lines did not contain numbers to be unnumbered... only the original lines. It seems the Unnumbering marks blanks in 73-80 as modified even though it did not modify them.

After Unnumber sequence numbers
![image](https://user-images.githubusercontent.com/80063515/142511004-554e1b76-2100-4b38-84a1-d8c9034b0472.png)

**Comment by phaumer** [comment]
It might be removing trailing whitespaces. To avoid changes we recommend using the VS Code setting `https://github.com/IBM/zopeneditor-about/issues/188` so that accidental trailing white space removal or additions does not have a Git impact.

**Comment by kkrein** [comment]
Ich bin derzeit nicht im Büro. Ich kehre zurück am  06.12.2021.
Während meiner Abwesenheit bitte bei Postkorb SCM-Admin melden!

Die Rückmeldung bezieht sich auf ein Mail mit folgendem Thema:
[IBM/zopeneditor-about] COBOL Unumbering sequence numbers Changes GIT
Source Control Color Bar Indicators to Blue   (Issue #188)

____________________________________________________________________________________________
Gesendet (c) GRZ/RSG Linz 2021 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angeführten Absender via E-Mail
dient ausschließlich Informationszwecken. Rechtsgeschäftliche Erklärungen
dürfen über dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------

**Comment by kkrein** [comment]
Ich bin derzeit nicht im Büro. Ich kehre zurück am  06.12.2021.
Während meiner Abwesenheit bitte bei Postkorb SCM-Admin melden!

Die Rückmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [IBM/zopeneditor-about] COBOL Unumbering sequence numbers Changes GIT
Source Control Color Bar Indicators to Blue   (Issue #188)

____________________________________________________________________________________________
Gesendet (c) GRZ/RSG Linz 2021 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angeführten Absender via E-Mail
dient ausschließlich Informationszwecken. Rechtsgeschäftliche Erklärungen
dürfen über dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------

**Comment by davidkcoblentz** [comment]
Thank you!  Sorry, which setting are you referring to?  I currently have
![image](https://user-images.githubusercontent.com/80063515/142513651-56cb3684-1f8f-4ea9-8624-f54beddaa2f6.png)

**Comment by phaumer** [comment]
Sorry, about that. I pasted from the wrong clipboard: `"files.trimTrailingWhitespace": true,`

**Comment by davidkcoblentz** [comment]
Ok, great, thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by davidkcoblentz** [comment]
I made the settings change mentioned above but still the same issue. 

Here is what the source looks like before any changes and it shows no trailing blanks:
![image](https://user-images.githubusercontent.com/80063515/142554444-e7568877-52a9-4376-b872-8ffe058e8aba.png)

Here are some source changes like adding a line and changing a couple of lines:
![image](https://user-images.githubusercontent.com/80063515/142554953-8a78ca02-5791-4f45-9977-564469992268.png)

Here is after the Unnumbering sequence numbers from the right click menu
![image](https://user-images.githubusercontent.com/80063515/142555205-99b31927-5815-42b4-9321-31b0e4c8d216.png)

I noticed two questionable behaviors 

1. When I change a line and hit enter to go to an added line, the GIT color bar is colored blue on the changed lines but also on the newly added line.
2. When unnum is executed ALL source lines get the GIT blue change bar indicator.

This is the GIT compare view of the same source that shows the entire source is considered changed.
![image](https://user-images.githubusercontent.com/80063515/142556165-b7028c08-e05d-43d5-9431-540bea16f468.png)

**Comment by davidkcoblentz** [comment]
Hi Peter.  I noticed you closed this one (#188).  I made the settings changes you recommended and re-tested with the same results.  I added some re-test documentation that shows clearly that there are no trailing spaces.  I was wondering if you would be willing to reconsider this issue?

Thank you,
***@***.***

**Comment by phaumer** [comment]
@davidkcoblentz perhaps I am misunderstanding your requirements or expectations. Any change including whitespaces is a Git change. Git just treats the file as a text file and compares each character. Is our unnumber doing more changes than expected such as lines that did not have numbers should not have changed?

**Comment by davidkcoblentz** [comment]
Than you for reconsidering this issue!

I am not sure if VS Code, GIT or IBM Z Open Editor is affecting this issue.  I suspect Z Open Editor for the following reasons.

### 7 Steps to re-create issue
1. Must have a working local GIT repository associated with the current work space being used.
2. Open an existing COBOL program from a folder in the work space that contains numbers in all or some of the lines of code in positions 1-6 and/or 73-80.  Ensure that trailing blanks are removed in source.
2. Add a new line of code to the source and notice the GREEN bar in the left margin indicated by GIT that a line has been added.
3. Go down in the source code a couple of lines and change a line of code slightly.  Notice the BLUE bar in the left margin indicated by GIT that this line has been changed.
4. Now you have a GREEN bar indicating an added line and a BLUE bar on another line indicating a changed line. Should look something like this:
![image](https://user-images.githubusercontent.com/80063515/142708893-525d727c-efa4-4a75-b521-3e48431620dc.png)

5. Now right click in the source and use the **Unnumber sequence numbers** action on the right click sub-menu.
6. Notice that now **ALL** source lines of code have a BLUE bar in the left margin (even the previously ADDED line with the GREEN bar) indicating that regardless if they had numbering or not are now all considered changed lines instead of having one or more GREEN added lines. Now looks like this:
![image](https://user-images.githubusercontent.com/80063515/142708935-51c282a9-0580-4989-aa2d-4f081a8900af.png)


### Current Behavior
1. What I am seeing is I can manually add a line to a source COBOL program and it is immediately marked correctly by GIT as an added line indicated by a vertical GREEN bar in the left margin as seen in the screen shots above.
2. I can change a different line and it is immediately marked accurately by GIT as a changed line by a BLUE indicator bar in the left margin and not as an added line as seen in the screen shots above..
3. In the example screen shot above, most of the source code lines have numbers in the left and right number areas, but the lines that I added do not have any trailing blanks nor numbers at all in either number area and again the added lines are marked in the left margin accurately by a GREEN bar.
4. As soon as I click the **Unnumber sequence numbers** action on the right click menu it's as if Z Open Editor changes each and every source code line even if there are no numbers to remove therefore making GIT change all lines in the source to a BLUE bar indicating ALL source lines were changed even if there were no numbers to remove.

### Expected Behavior

1. I would expect the lines that I added to stay GREEN accurately indicating they are ADDED lines not CHANGED lines.
2. And only those lines with line numbers removed to be marked BLUE indicating they were changed due to unnumbering.

Hope this helps.

**Comment by davidkcoblentz** [comment]
Hmmm, I have done additional testing with this and it seems to be related to GIT and not Z Open Editor. I will test further and let you know.

**Comment by phaumer** [comment]
This is just how Git works. It does not compare to you last change. It compares to the last commit. As the lines before and after changed I assume it takes all the new lines inbetween as part of the change. If you want to track each step, then you need to commit the changes of adding a line before unnumbering. We did not write a single line of code for this. One thing I would consider a bug if somehow our editor would replace tabs with spaces or vice versa, but I do not see that.

**Comment by davidkcoblentz** [comment]
Thank you for the info.  We can close this issue.  I see how it works now.

**Comment by kkrein** [comment]
Ich bin derzeit nicht im Büro.
Während meiner Abwesenheit bitte bei Postkorb SCM-Admin melden!

Die Rückmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [IBM/zopeneditor-about] COBOL Unumbering sequence numbers Changes GIT
Source Control Color Bar Indicators to Blue   (Issue #188)

____________________________________________________________________________________________
Gesendet (c) GRZ/RSG Linz 2021 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angeführten Absender via E-Mail
dient ausschließlich Informationszwecken. Rechtsgeschäftliche Erklärungen
dürfen über dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------
