### ISSUE TITLE
[other platforms] allow COBOL free format

### ISSUE THREAD

**Issue by Ldspout** [IBM/zopeneditor-about#19]
Hi,

Would it be possible to adapt your great extension so it could parse the free format Cobol ?
Code can start at any position, lines can exceed 72 char long, aso : 
https://www.microfocus.com/documentation/visual-cobol/30pu9/VC_30PU9_Dev_Hub_WH/HRLHLHINTR01U008.html
If ok, I could use it to work for microfocus format ?
Thank you !

**Comment by phaumer** [comment]
Unfortunately, this is not something that we can focus on right now as we are targeting z/OS Enterprise developers.
