### ISSUE TITLE
HLASM Syntax Highlighting in Sequence Field

### ISSUE THREAD

**Issue by davidkcoblentz** [IBM/zopeneditor-about#192]
## Development environment used

Version: 1.62.3 (user setup)
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:11:14.551Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.17763

## Sequence Field Numbering is Highlighted Incorrectly

Detailed steps for reproducing the problem:

1. Open Assembler source member with sequence numbers on
2. Find or add a source line that has a operation field with no operands and a sequence number in columns 73-80
3. On other source lines with operands the sequence numbers are green and on the source line added the with no operands the sequence number is teal or light blue which is the color of an operand. 

### Observed behavior

If there is no opereand field the sequence number area is colored as if it is an operand instead of the sequence numbering color.
![image](https://user-images.githubusercontent.com/80063515/142957191-d0c94db7-e2cc-47e7-b7ee-02d6e409ed23.png)

### Expected behavior

Mainframe PDF Editor example
![image](https://user-images.githubusercontent.com/80063515/142958299-99614ee8-20f7-498a-8a29-01f5fa650d82.png)

**Comment by kkrein** [comment]
Ich bin derzeit nicht im Büro.
Während meiner Abwesenheit bitte bei Postkorb SCM-Admin melden!

Die Rückmeldung bezieht sich auf ein Mail mit folgendem Thema:
[IBM/zopeneditor-about] HLASM Syntax Highlighting in Sequence Field (Issue
#192)

____________________________________________________________________________________________
Gesendet (c) GRZ/RSG Linz 2021 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angeführten Absender via E-Mail
dient ausschließlich Informationszwecken. Rechtsgeschäftliche Erklärungen
dürfen über dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------

**Comment by phaumer** [comment]
Fixed in Z Open Editor v2.0.0
