### ISSUE TITLE
COBOL Syntax Highlighting in COBOL (1-6) and Standard (73-80) Sequence Fields

### ISSUE THREAD

**Issue by davidkcoblentz** [IBM/zopeneditor-about#193]
## Development environment used

Version: 1.62.3 (user setup)
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:11:14.551Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.17763
## Problem Description

Detailed steps for reproducing the problem:

1. Open COBOL source with numbering in both the COBOL sequence area (1-6) as well as numbering in the standard sequence area (73-80)
2. Add comment lines in the source if there are none while maintaining the sequence numbering fields (1-6 and 73-80)
3. Note the sequence numbers change color to the syntax comment color instead of staying the color they were on all other non-comment lines. 

### Observed behavior

Both Sequence fields in columns 1-6 and 73-80 change color based on if it is a comment line or other type of line. 
![image](https://user-images.githubusercontent.com/80063515/142959204-0a230a69-fbe9-460d-a2f9-a43186937df2.png)

### Expected behavior

I would expect that both sequence number fields would have the same highlighting color as each other **but be a unique color** from all other syntax highlighting colors as demonstrated below in the mainframe PDF Editor screen examples. Notice in the examples below how the sequence color is unique and not the same color as any other syntax highlighting used for the COBOL statements.
 
Example of the left half of the mainframe screen showing columns 1-6 of a COBOL source.  PDF Editor colors COBOL source in columns 1-6 consistently as a unique color regardless of comments or other contents of the COBOL source line.
![image](https://user-images.githubusercontent.com/80063515/142959448-8e671c4e-b09a-4a54-b726-09b1fabd65d9.png)

Example of the right half of the mainframe screen of the same lines above showing columns 73-80.  Again PDF Editor colors the standard numbers in columns 73-80 as the same unique color of the numbers in columns 1-6 but a different color from any other part of the source line contents. 
![image](https://user-images.githubusercontent.com/80063515/142960733-4c8c4a03-467b-4084-ae1b-663982cc0f94.png)

**Comment by kkrein** [comment]
Ich bin derzeit nicht im Büro.
Während meiner Abwesenheit bitte bei Postkorb SCM-Admin melden!

Die Rückmeldung bezieht sich auf ein Mail mit folgendem Thema:
[IBM/zopeneditor-about] COBOL Syntax Highlighting in COBOL (1-6) and
Standard (73-80) Sequence Fields (Issue #193)

____________________________________________________________________________________________
Gesendet (c) GRZ/RSG Linz 2021 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angeführten Absender via E-Mail
dient ausschließlich Informationszwecken. Rechtsgeschäftliche Erklärungen
dürfen über dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------

**Comment by FALLAI-Denis** [comment]
Same as #182 [COBOL - Improve text colorization for syntax highlighting by textmate grammar](https://github.com/IBM/zopeneditor-about/issues/182)?

**Comment by kkrein** [comment]
Ich bin derzeit nicht im Büro.
Während meiner Abwesenheit bitte bei Postkorb SCM-Admin melden!

Die Rückmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [IBM/zopeneditor-about] COBOL Syntax Highlighting in COBOL (1-6) and
Standard (73-80) Sequence Fields (Issue #193)

____________________________________________________________________________________________
Gesendet (c) GRZ/RSG Linz 2021 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angeführten Absender via E-Mail
dient ausschließlich Informationszwecken. Rechtsgeschäftliche Erklärungen
dürfen über dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------

**Comment by phaumer** [comment]
@davidkcoblentz on a related note: what is the use case for sequence numbers on the left and the right? Now that you work in VS Code would you still want to preserve these over time?

**Comment by davidkcoblentz** [comment]
Thanks for asking.  No, I am trying to get them all removed but it will take time and we have hundreds of source members that currently have numbers.  Granted most of them are fragmented but it would still be nice to get them colored correctly during research and times where I am reading the code but not necessarily changing the code. Plus we use 1-6 for tagging our changes with project ID’s so having a different color for those areas would really help the readability of the code.
Thank you,
***@***.***

**Comment by FALLAI-Denis** [comment]
Hi,

For our part, we use the sequence number and identification areas to store informations:
- sequence number area: marks set by our development aid tool (code injector)
- identification area: tracking of changes.

If these zones were to disappear in the future during the implementation of the free format of COBOL lines, we would then use a floating comment at the end of the line with a normalization corresponding to our needs.
But that doesn't seem to be the direction IBM is going if you believe what enables the IBM COBOL for Linux compiler, which doesn't offer a free format, but offers an extended format that maintains a sequence number field and an identification field.

**Comment by phaumer** [comment]
We made updates to consistently color the sequence numbers in version 3.0.0. Please, let us know what you think.

**Comment by davidkcoblentz** [comment]
Thank you for the update. When will V3.0.0 be available?

Thank you,
***@***.***

**Comment by phaumer** [comment]
It is out now.

**Comment by FALLAI-Denis** [comment]
👍

**Comment by davidkcoblentz** [comment]
Got it thanks! Can’t wait to kick the tires

Thank you,
***@***.***

**Comment by phaumer** [comment]
Yes, that is an open enhancement request that we should do. The quickest way is to do an F1 or cmd-shift-p to bring up the Command Palette and select `Developer: Reload Window`.

**Comment by davidkcoblentz** [comment]
Awesome thanks!!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
