### ISSUE TITLE
JAVA ERROR when editing pli code 

### ISSUE THREAD

**Issue by kraabrsg** [IBM/zopeneditor-about#195]
Hi,

While editing pli code, the editor was really slowish / laggy. 
After 1 or 2 h of coding, an error appears (vscodium notification that an error has occured, unfortunatly i did not take a screenshot) in the OUTPUT section of vscodium. see the logfile below.

## Development environment used

- Z Open Editor version:
- Editor Platform
  - [x] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version: 1.60.1
- Operating System (on which VS Code runs such as Windows 10 2004, otherwise name and version of platform such as OpenShift v4.3): WIN 10 Enterprise, 10.0.19042 Build 19042
- Java Version (when using VS Code or Theia, execute `java -version` and paste the details here):
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version: 6.32.1
  - Node.js version:V14.15.3
- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html) how to get them): yes

## Problem Description

Log file: (C:\Users\xxxxx\AppData\Roaming\VSCodium\logs\20211123T063231\exthost1\output_logging_20211123T093313)
[10-COBOL Language Server.log](https://github.com/IBM/zopeneditor-about/files/7586960/10-COBOL.Language.Server.log)

confusing is that is named COBOL, we use it for PLI... (this could be because of messing up settings.json entry: zopeneditor.propertygroups)

**Comment by kkrein** [comment]
Ich bin derzeit nicht im Büro.
Während meiner Abwesenheit bitte bei Postkorb SCM-Admin melden!

Die Rückmeldung bezieht sich auf ein Mail mit folgendem Thema:
[IBM/zopeneditor-about] JAVA ERROR when editing pli code  (Issue #195)

____________________________________________________________________________________________
Gesendet (c) GRZ/RSG Linz 2021 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angeführten Absender via E-Mail
dient ausschließlich Informationszwecken. Rechtsgeschäftliche Erklärungen
dürfen über dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------

**Comment by phaumer** [comment]
The attached log show that the PL/I language server crashed with an Out of Memory error. Despite the sluggishness did the language server behave correctly? Showing an outline view, offering code completion etc. Did you edit a very large program or many files at the same time? Did you laptop have enough memory available? You can configure the maximum amount of memory a language server can use as [described here](https://ibm.github.io/zopeneditor-about/Docs/getting_started.html#configuring-the-java-memory-allocation).

**Comment by kkrein** [comment]
Ich bin derzeit nicht im Büro.
Während meiner Abwesenheit bitte bei Postkorb SCM-Admin melden!

Die Rückmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [IBM/zopeneditor-about] JAVA ERROR when editing pli code  (Issue #195)

____________________________________________________________________________________________
Gesendet (c) GRZ/RSG Linz 2021 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angeführten Absender via E-Mail
dient ausschließlich Informationszwecken. Rechtsgeschäftliche Erklärungen
dürfen über dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------

**Comment by kraabrsg** [comment]
Hi, we used 2048 MB of RAM here. I did not notice any difference in behaviour. i had 2 pli programs with about 3,5k lines of code open (and 2,3 small powershell scripts). My laptop has 16 GB of RAM. It is the first time i noticed this error. What i found out was that we messed up the settings.json, meaning we missed this part.

`  
  "zopeneditor.propertygroups": [{
        "name": "CompilerOptions",
        "compilerOptions": "MARGINS(2,100) OR('!') NOT('^')",
        "language": "pl1"
        }
     ],
`

But that should not be related to this...

**Comment by phaumer** [comment]
Was this a one off or can you reproduce it with the same programs? We can do some extra memory leak profiling.

**Comment by kraabrsg** [comment]
It was really a one timer, can't reproduce it.

**Comment by phaumer** [comment]
Perhaps a case of fragmented memory? Let's reopened when it happens again.

**Comment by kraabrsg** [comment]
We have here again a problem with some kind of memory leak. Unfortunatly i could not find log files to narrow down the problem. How can i enable the profiling? Where to find java log files? We use jdk-11.0.2  (One file opened, which can be seen on the screenshot, z open editor Version 1.4.1, WIN 10)
`
"zopeneditor.JAVA_HOME": "C:\\xxxxx\\java\\jdk-11.0.2",
`

![grafik](https://user-images.githubusercontent.com/86772851/148178216-763ddbd4-72e1-40be-a9a0-64680b29f879.png)

After a restart of VSCODIUM everything ok again:

![grafik](https://user-images.githubusercontent.com/86772851/148178723-c8e0f532-95fc-4afe-bb69-23f5fc839d9a.png)


Thanks!
