### ISSUE TITLE
COBOL - Independence of search function COPYBOOKs and other Language Server functions

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#199]
## Description of the enhancement requested

Hi,

For the various reasons mentioned in discussion #184, [The language server is not a language compiler](https://github.com/IBM/zopeneditor-about/discussions/184), and in particular for issue #154, [Cobol Language Server - "Full red program" after LS analysis](https://github.com/IBM/zopeneditor-about/issues/154), we would like the "Search for COPYBOOKs" function to be made independent of the other functions of the Language Server.

This means either managing the search for COPYBOOKs in an independent process, so that it remains active when the Language Server is paused, or allowing certain functions of the Language Server to be paused, or not to be paused, but not all or none of the functions.

The Language Server problems in the current situation are very penalizing for our development teams who are evaluating the solution, and it is a subject that they often bring up to us.

**Comment by phaumer** [comment]
Fixed in Z Open Editor v3.2.0 by adding a new setting `zopeneditor.<language>.disableProblems`
