### ISSUE TITLE
Allow Receive of XMIT datasets

### ISSUE THREAD

**Issue by travatine** [IBM/zopeneditor-about#20]
Hi,

I frequently need to receive datasets in XMIT format;
Today I use ISPF / TSO to run the receive commands .
It'd be great if the same thing could be done from the VS Code UI.

Thanks!
Travis.

**Comment by phaumer** [comment]
Thanks for trying our extension. For the interactions to z/OS we do not write our own code, but currently utilize packages from the Zowe Open Source project such as the Zowe CLI (https://github.com/zowe/zowe-cli) and Zowe Explorer (https://github.com/zowe/vscode-extension-for-zowe).  Could you file these enhancements requests there, please, as they are different projects?
