### ISSUE TITLE
JSON.SCHEMAS 

### ISSUE THREAD

**Issue by kraabrsg** [IBM/zopeneditor-about#200]
## Development environment used

- Z Open Editor version:
- Editor Platform
  - [x] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version: 1.62.3
- Operating System (on which VS Code runs such as Windows 10 2004, otherwise name and version of platform such as OpenShift v4.3): WIN 10 Enterprise 10.0.19042 Build 19042
- Java Version (when using VS Code or Theia, execute `java -version` and paste the details here):
   java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)
(using : "zopeneditor.JAVA_HOME": "C:\\Entwicklung\\java\\jdk-11.0.2" in settings json)
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version: 6.32.1
  - Node.js version: 14.15.3
- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html) how to get them): no

## Problem Description
Not really a problem, but can it be avoided that the z open editor writes "json.schemas" to settings,json in the user directory at startup of vscode ? (we want to use the settings.json at workspace level to make a more portable version of our installation, have it in one place). Further as can be seen on the screenshot the encoding of ":" seems to be wrong -> if we would use that one day it may not work ???

![grafik](https://user-images.githubusercontent.com/86772851/145939138-f0096502-8338-4e88-b92e-6f8abbe9423d.png)

### Observed behavior

-

### Expected behavior

-

Thank you!

**Comment by phaumer** [comment]
Thanks @kraabrsg, but could you provide more details about how this will impact you? We considered these cases when we designed the feature:

- We wanted schema support for user working online as well as offline and not require users to configure this themselves.
- If this setting is already used for other schema entries that we will only add to it. 
- If you disable ZAPP with `"zopeneditor.zapp.enabled": false,` then this entry will not be added to your user settings.
- Workspace settings override user settings. So if you have json schemas defined there then that setting will be used.
- The URL is valid and generated by a VS Code API. We run all our tests on Windows and MacOS and had not any issues reported with it. Let us know if you ran into any issues and we will investigate.

**Comment by kraabrsg** [comment]
Hi @phaumer , ok, i first thought this is not a valid url. Working offline would be nice indeed, but it is not our first goal yet. i will close this one. Thank you!
