### ISSUE TITLE
INSERT Key with Toggle to OVERTYPE

### ISSUE THREAD

**Issue by davidkcoblentz** [IBM/zopeneditor-about#207]
### Environment
Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.17763
IBM Z Open Editor  v1.4.1

### Description of enhancement
Add feature to toggle the INSERT key from insert to OVERTYPE.  This is a big time saver for languages such as COBOL and Assembler with fixed column positioning and zones where code needs to be positioned. Most editors have this feature.

### These are Simple Examples but OVERTYPE can be used whenever aligning code
If I want to change columns 1-6 to change the tag number from PRDFIX to CT0001 on two lines. I realize these can be changed with the change function but there are many times when OVERTYPE would be desirable.
```
----+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8
PRDFIX*06/03/21 LM21-0096 SUDIP      RECOMPILED TO INCLUDE CHANGES TO  *
PRDFIX*                              THE COPYBOOK SDC001.              *
      ******************************************************************
```
INSERT is always on so it costs twice as many keystrokes to change the tags on these 2 lines. 6 keystrokes to add CT0001 and 6 to delete PRDFIX to align the comments properly since the comment * needs to be in column 7.
```
----+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8
CT0001PRDFIX*06/03/21 LM21-0096 SUDIP      RECOMPILED TO INCLUDE CHANGES TO  *
PRDFIX*                              THE COPYBOOK SDC001.              *
      ******************************************************************
```
-- or --  a similar example just to keep code aligned while coding without the extra keystrokes to line them back up. For example if I need to change the tags on these MOVE lines, OVERTYPE would be indispensable.
```
----+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8
              MOVE MOC-KEY-CHG-IND OF MELDATA TO
                   PV-KEY-CHG-IND  OF PV-PROGRAM-VARIABLES
MSR059        MOVE FOS-USERID      OF MELDATA TO
MSR059             PV-FOS-USERID   OF PV-PROGRAM-VARIABLES
MSR059        MOVE FOS-CLOSE-EMPNO OF MELDATA TO
MSR059             PV-FOS-CLS-EMPNO OF PV-PROGRAM-VARIABLES
              MOVE MOC-CAPABLE-STATIONS-FIELD TO PV-STATION-RQMTS
              PERFORM 3000-GET-STD-TEMPLATES THRU
                      3000-GET-STD-TEMPLATES-EXIT
```

**Comment by kkrein** [comment]
Ich bin derzeit nicht im Büro. Ich kehre zurück am  03.01.2022.
Während meiner Abwesenheit bitte bei Postkorb SCM-Admin melden!

Die Rückmeldung bezieht sich auf ein Mail mit folgendem Thema:
[IBM/zopeneditor-about] INSERT Key with Toggle to OVERTYPE (Issue #207)

____________________________________________________________________________________________
Gesendet (c) GRZ/RSG Linz 2021 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angeführten Absender via E-Mail
dient ausschließlich Informationszwecken. Rechtsgeschäftliche Erklärungen
dürfen über dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------

**Comment by spgennard** [comment]
Have you tried this extension?

https://marketplace.visualstudio.com/items?itemName=adammaras.overtype

**Comment by kkrein** [comment]
Ich bin derzeit nicht im Büro. Ich kehre zurück am  03.01.2022.
Während meiner Abwesenheit bitte bei Postkorb SCM-Admin melden!

Die Rückmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [IBM/zopeneditor-about] INSERT Key with Toggle to OVERTYPE (Issue #207)

____________________________________________________________________________________________
Gesendet (c) GRZ/RSG Linz 2021 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angeführten Absender via E-Mail
dient ausschließlich Informationszwecken. Rechtsgeschäftliche Erklärungen
dürfen über dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------

**Comment by davidkcoblentz** [comment]
Thanks for the suggestion @spgennard, Overtype extension works great!
