### ISSUE TITLE
Markdown preview of z/OS USS text file remembers a previous version of .md file and does not use current contents

### ISSUE THREAD

**Issue by pjfarleyiii** [IBM/zopeneditor-about#213]
## Development environment used

- Z Open Editor version: 1.4.1
- Editor Platform
  - [X ] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version:
- Operating System (on which VS Code runs such as Windows 10 2004, otherwise name and version of platform such as OpenShift v4.3): Windows 10 Pro 21H1 Build 19043.1466
- Java Version (when using VS Code or Theia, execute `java -version` and paste the details here):
java version "1.8.0_311"
Java(TM) SE Runtime Environment (build 1.8.0_311-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.311-b11, mixed mode)
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html) how to get them): yes/no
- Z Open Editor version: 1.4.1
- Editor platform: Visual Studio Code
- Editor platform version: 1.63.2
- Required minimal editor platform version: ^1.44.0
- Editor installation root directory: c:\Program Files\Microsoft VS Code\resources\app
- Editor installation id: 5864e6cac65133e4ea21287f1059ce9894a850abb5f61a41445631788e7de707
- Is a valid Java configured: true
  - Java: C:\Program Files\Java\jdk1.8.0_311\bin\java.exe
  - Java memory allocation: 512
- Key user settings:
  - Unreachable Code enabled: true
  - ZAPP files enabled: true
  - Enforce Case Sensitive Include File Names: false
  - ZAPP schema used: file:///c%3A/Users/Peter/.vscode/extensions/ibm.zopeneditor-1.4.1/resources/zapp-schema-0.0.2.json
  - IBM User Build enabled: true
  - Zowe CLI Secure Credentials enabled: false
  - Zowe CLI files profile user setting: Not defined.
  - Zowe CLI files profile used: zxplore
  - Zowe CLI SSH profile user setting: Not defined.
  - Zowe CLI SSH profile used: No profile found.
  - Zowe Explorer RSE API Mappings File setting: Not defined.
  - Zowe Temp-Dir value: Not defined.
  - COBOL Property Groups defined: 
  - COBOL include file extensions: .cpy,.copybook,.copy,.cobcopy
  - PL/I Property Groups defined: 
  - PL/I include file extensions: .inc,.include,.plinc,.pcx,.pci
  - HLASM Property Groups defined: 
  - HLASM include file extensions: .s,.assemble,.asm,.hlasm,.hla
  - VS Code Files Assocications: *.COBOL*:cobol,*.COB*:cobol,*.COBCOPY*:cobol,*.COPYBOOK*:cobol,*.COPY*:cobol,*.PL1*:pl1,*.PLI*:pl1,*.INC*:pl1,*.INCLUDE*:pl1,*.JCL*:jcl,*.ASM*:hlasm,*.ASSEMBLE*:hlasm,*.HLASM*:hlasm,*.HLA*:hlasm,*.FLYRFILE:html
- Zowe Explorer VS Code Extension version: 1.21.0
  - Successfully activated: true
  - Installation path: c:\Users\Peter\.vscode\extensions\zowe.vscode-extension-for-zowe-1.21.0
  - Log file location: c:\Users\Peter\.vscode\extensions\zowe.vscode-extension-for-zowe-1.21.0\logs
- Other VS Code extensions visible: vscode.bat(1.0.0),vscode.clojure(1.0.0),vscode.coffeescript(1.0.0),vscode.configuration-editing(1.0.0),vscode.cpp(1.0.0),vscode.csharp(1.0.0),vscode.css(1.0.0),vscode.css-language-features(1.0.0),vscode.dart(1.0.0),vscode.debug-auto-launch(1.0.0),vscode.debug-server-ready(1.0.0),vscode.diff(1.0.0),vscode.docker(1.0.0),vscode.emmet(1.0.0),vscode.extension-editing(1.0.0),vscode.fsharp(1.0.0),vscode.git(1.0.0),vscode.git-base(1.0.0),vscode.github(0.0.1),vscode.github-authentication(0.0.2),vscode.go(1.0.0),vscode.groovy(1.0.0),vscode.grunt(1.0.0),vscode.gulp(1.0.0),vscode.handlebars(1.0.0),vscode.hlsl(1.0.0),vscode.html(1.0.0),vscode.html-language-features(1.0.0),vscode.image-preview(1.0.0),vscode.ini(1.0.0),vscode.ipynb(1.0.0),vscode.jake(1.0.0),vscode.java(1.0.0),vscode.javascript(1.0.0),vscode.json(1.0.0),vscode.json-language-features(1.0.0),vscode.julia(1.0.0),vscode.less(1.0.0),vscode.log(1.0.0),vscode.lua(1.0.0),vscode.make(1.0.0),vscode.markdown(1.0.0),vscode.markdown-language-features(1.0.0),vscode.markdown-math(1.0.0),vscode.merge-conflict(1.0.0),vscode.microsoft-authentication(0.0.1),ms-vscode-remote.remote-wsl-recommender(0.0.12),ms-vscode.js-debug(1.62.0),ms-vscode.js-debug-companion(1.0.15),ms-vscode.references-view(0.0.81),ms-vscode.vscode-js-profile-table(0.0.18),vscode.npm(1.0.1),vscode.objective-c(1.0.0),vscode.perl(1.0.0),vscode.php(1.0.0),vscode.php-language-features(1.0.0),vscode.powershell(1.0.0),vscode.pug(1.0.0),vscode.python(1.0.0),vscode.r(1.0.0),vscode.razor(1.0.0),vscode.ruby(1.0.0),vscode.rust(1.0.0),vscode.scss(1.0.0),vscode.search-result(1.0.0),vscode.shaderlab(1.0.0),vscode.shellscript(1.0.0),vscode.simple-browser(1.0.0),vscode.sql(1.0.0),vscode.swift(1.0.0),vscode.theme-abyss(1.0.0),vscode.theme-defaults(1.0.0),vscode.theme-kimbie-dark(1.0.0),vscode.theme-monokai(1.0.0),vscode.theme-monokai-dimmed(1.0.0),vscode.theme-quietlight(1.0.0),vscode.theme-red(1.0.0),vscode.vscode-theme-seti(1.0.0),vscode.theme-solarized-dark(1.0.0),vscode.theme-solarized-light(1.0.0),vscode.theme-tomorrow-night-blue(1.0.0),vscode.typescript(1.0.0),vscode.typescript-language-features(1.0.0),vscode.vb(1.0.0),vscode.xml(1.0.0),vscode.yaml(1.0.0),george-alisson.html-preview-vscode(0.2.5),IBM.db2forzosdeveloperextension(1.3.3),IBM.zopeneditor(1.4.1),ms-azuretools.vscode-docker(1.18.0),ms-vscode-remote.remote-containers(0.209.6),Zowe.vscode-extension-for-zowe(1.21.0)
2022-01-18T23:42:55.713-0500 DEBUG: ZAPP: No zapp file was found. User and workspace settings will be used. Started watcher for when a zapp file does get created.
2022-01-18T23:42:55.767-0500 INFO : IBM Z Open Editor extension has (re)started.
2022-01-18T23:52:04.888-0500 INFO : A VS Code Settings change was detected that requires a restart of the Z Open Editor extension. All language servers will be stopped now and restarted on demand.
2022-01-18T23:52:04.988-0500 DEBUG: Received request to stop all language servers.
2022-01-18T23:52:04.989-0500 DEBUG: IBM Z Open Editor extension has been deactivated for a restart.
2022-01-18T23:52:04.989-0500 DEBUG: UsageReporter: Sending the following telemetry data: {"eventName":"deactivated","properties":{"editor":"Visual Studio Code"},"measurements":{"sinceActivated":549.285}}
## Problem Description

Detailed steps for reproducing the problem:

1. First step

1.a. Use zowe extension to select a USS text file coded with markdown syntax on z/OS system to edit and edit that file.
1.b. With cursor present in the edited file window, press Ctrl-Shift-V to preview the formatted markdown document
1.c. Markdown preview shows text from a prior (no longer available) version of the same file name.

Expected result:
Markdown preview of edited USS file with markdown syntax should show the current text of the file and not of some prior version.

**Comment by phaumer** [comment]
@pjfarleyiii thanks for trying our editor. The markdown capability is part of VS Code itself. We do not provide any specific capabilities for it with Z Open Editor nor Zowe Explorer. You would have to file an issue with Microsoft.

**Comment by pjfarleyiii** [comment]
Thanks for the answer.  I will pursue MS for an answer.  :)
