### ISSUE TITLE
Copy Member / Rename member

### ISSUE THREAD

**Issue by travatine** [IBM/zopeneditor-about#22]
Hi,

I can't see these options in UI am I missing them?

Thanks!

**Comment by phaumer** [comment]
Thanks for trying our extension. For the interactions to z/OS we do not write our own code, but currently utilize packages from the Zowe Open Source project such as the Zowe CLI (https://github.com/zowe/zowe-cli) and Zowe Explorer (https://github.com/zowe/vscode-extension-for-zowe).  Could you file these enhancements requests there, please, as they are different projects?
