### ISSUE TITLE
HLASM - Specific file extensions for copy and macro High Level Assembler source files

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#220]
## Description of the enhancement requested

Z Open Editor declares several possible extensions for High Level Assembler source files, but it makes no provision for distinguishing between program source files, simple include source files and macro source files.

We would like extensions to be proposed as defaults in Z Open Editor for simple include and macro source files, without this coming into conflict with the extensions already planned for COBOL and for PL/I (problem of the .inc extension already used).

For the coding syntax of reference to simple include, or a macro, there is not necessarily a difference (a simple include can be referenced like a macro), however we think that it is necessary to distinguish the two typologies of sources.

We propose :

- .inchlasm / .incasm / .ihlasm / .iasm for simple includes
- .machlasm / .macasm / .mhlasm / .masm for macros

**Comment by phaumer** [comment]
Thanks for the suggestions.

**Comment by FALLAI-Denis** [comment]
HLASM use COPY directive to reference simple include source file. 
So extension should refer to COPY instead of INCLUDE :
- copyhlasm, copyasm, chlasm, casm ...

**Comment by FALLAI-Denis** [comment]
![image](https://user-images.githubusercontent.com/63861965/174043931-67970068-0b4f-4e38-8cc6-be83db10dd7d.png)

Great !
Thanks a lot !
