### ISSUE TITLE
HLASM - Specific file extensions for Basic Mapping Support (BMS) source files

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#223]
## Description of the enhancement requested

The BMS files, Basic Mapping Support, which describe the screens in a CICS context are in fact Assembler files (composed of calls to specific Assembler macros).

They must be managed by Z Open Editor, but associated with an extension of their own.

We suggest adding the ".bms" extension to the "hlasm" language mode among the extensions recognized by default by Z Open Editor.

**Comment by kraabrsg** [comment]
+1 for that, we also have the need for it, alternatives like https://github.com/mainframed/ANSi2BMS were not tested yet...

**Comment by Andi82ka** [comment]
+1 Oh BMS would be great! We also have a lot of BMS sources.

**Comment by TimMSbg** [comment]
+1  from us, as we need this function too

**Comment by FALLAI-Denis** [comment]
![image](https://user-images.githubusercontent.com/63861965/174035476-2e6b82df-f326-4a9b-ad45-a8d50ab405f0.png)

Great !
Thanks a lot !
Just a few flaws with the textmate grammar on strings that I'll report in another issue.

---

No macro support?
![image](https://user-images.githubusercontent.com/63861965/174036279-33b2f64c-7f04-41b0-bc1c-48ee2bbb6e8d.png)

**Comment by sdaimwood** [comment]
Hi Denis, thanks for following up on this! Our goal for BMS with 2.1.0 was to get basic support out and then explore other functionality as requested by users in the future. So please create issues for any enhancements you'd like to see for BMS support.

Those syntax errors look to be similar to other errors we see on continuation lines, but as far as I can tell no issue currently exists to track this so would be a good one to report.

**Comment by FALLAI-Denis** [comment]
The issue concerns the recognition of character strings:

![image](https://user-images.githubusercontent.com/63861965/174072008-cba5e8c0-0094-4ff3-b405-508fa66526e3.png)

![image](https://user-images.githubusercontent.com/63861965/174072085-5b3efbb0-ea97-44ac-a85a-feff4d7f288e.png)

![image](https://user-images.githubusercontent.com/63861965/174072142-9dcd676e-8e84-4c3d-ae35-26cb8d9b439c.png)

**Comment by FALLAI-Denis** [comment]
I propose this solution which seems to give the expected result, at least for my use case:

```
    "continuation-line-rule": {
      "match": "^[ ]{15}((?:[^ \"']*(?:[\"'].*[\"'])?)+)([ ]+.*)?",
      "captures": {
        "1": {
          "name": "variable.parameter"
        },
        "2": {
          "name": "comment.line.zvmasm"
        }
      }
    },
```

I did not manage to make a backreference for the treatment of the character `"` or `'` closing corresponding to the character `"` or `'` opening.

![image](https://user-images.githubusercontent.com/63861965/174089004-8b05c98f-78cc-43ff-a80e-b6ba30b59d80.png)

**Comment by FALLAI-Denis** [comment]
Hi,

This issue only concerned the association of the `.bms` extension with the `HLASM` language mode.

I'm going to open another issue specific to the Assembler language textmate grammar because I seem to have several issues with this grammar.
