### ISSUE TITLE
profile name zxplore inactive

### ISSUE THREAD

**Issue by ahmedzacki** [IBM/zopeneditor-about#229]
I working on the ibm zxplore fundamentals and I am stuck with challenge 3, especially the JCL2 problem. it is not showing cc=0000 when I submit the job.

**Comment by phaumer** [comment]
Hello @ahmedzacki. Unfortunately, this is not the right place to report this issue as it seems specific to zXplore. Can you try here? https://ibmzxplore.influitive.com/forum/c/contact-support
