### ISSUE TITLE
Unable to find include file

### ISSUE THREAD

**Issue by przemekherok** [IBM/zopeneditor-about#23]
Hi,

I created a new workspace with just one PL1 program and INCLUDES folder. 
When I moved one include to the folder I'm still getting "Unable to find include file" message (see the picture)

![include_problem1](https://user-images.githubusercontent.com/43341440/69616887-a377bb00-1037-11ea-86ec-fa1ca9724d2b.jpg)

**My USER settings.json**

```
{
    "files.associations": {
      "*.COBOL*": "cobol",
      "*.COB*": "cobol",
      "*.COBCOPY*": "cobol",
      "*.COPYBOOK*": "cobol",
      "*.COPY*": "cobol",
      "*.PL1*": "pl1",
      "*.PLI*": "pl1",
      "*.INC*": "pl1",
      "*.INCLUDE*": "pl1",
      "*.JCL*": "jcl"
    },
    "zopeneditor.JAVA_HOME": "C:\\# TOOLS\\java 8",
    "zopeneditor.server.memoryAllocation": 1024
}

```
**My WORKSPACRE settings.json**

```
{
	"folders": [
		{
			"path": "C:\\# WORKSPACES\\Visual Studio\\zopeneditor-ACTIVE"
		}
	],
	"settings": {
		"zopeneditor.propertygroups": [
			{
				"name": "SAM-Copybooks",
				"type": "local",
				"syslib": [
					"COPYBOOK",
					"INCLUDES"
				]
			}
		]
	},
}

```
Am I missing something here?

**Comment by PrasangAPrajapati** [comment]
@przemekherok Hi,

I can see you have `.PLINC` extension for your INCLUDE files and as of now we only support `.inc` extension to be resolved for INCLUDE files.

**Comment by phaumer** [comment]
@przemekherok we are proposing to allow users to specify their own file extensions as outlined in Issue #16. I will resolve this as a duplicate to that item for now. Let me know if you have a different solution in mind and provide feedback to Issue #16.

**Comment by przemekherok** [comment]
Hi guys,

thanks for quick answer, but after changing the extension it still remain unreachable

![image](https://user-images.githubusercontent.com/43341440/69781232-c2985900-11ad-11ea-8d5a-932348652d67.png)
