### ISSUE TITLE
Possibility to ignore setting-lines in a source modul

### ISSUE THREAD

**Issue by Andi82ka** [IBM/zopeneditor-about#231]
We are working on z/VSE and use Z Open Editor just as smart Editor. Compiles are still done on VSE via CMS. Our compile routine requires some setting-lines at the beginning of the source-code member:

```
$$ICSU1$$ PHASE=UFZAPIC;LIB=SUBCLO;LIST=SOURCE;
$$ICSU2$$ CLE;CICS;                            
       IDENTIFICATION DIVISION.
       PROGRAM-ID. UFZAPIC.
       ENVIRONMENT DIVISION.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
      *
      * Debug Text
      *
       01 INFOTEXT.
          02 PGM-NAME                  PIC X(7)   VALUE 'UFZAPIC'.
          02 FILLER                    PIC X(02)  VALUE ': '.
          02 INFOTEXT-MSG              PIC X(60)  VALUE SPACE.
          02 INFOTEXT-NUM REDEFINES INFOTEXT-MSG.
             05 INFOTEXT-NUM-VAL       PIC -9(6).
             05 FILLER                 PIC X(53).
```

![grafik](https://user-images.githubusercontent.com/3204541/161258117-a6897152-9f4a-4bf5-b855-b117fc29a167.png)

But these lines are forcing an "unexpected token"-error and a lot of functionality of VSC is not working anymore. For example jump to definition and lot of autocomletes.

Is there a posibility to make Z Open Editor clever enough to ignore this lines?

**Comment by FALLAI-Denis** [comment]
Hi @Andi82ka 

These lines are not « COBOL compilant »…

i suggest you use comment lines « COBOL compilant » for your compilation directives. 

Another solution would be to use 2 files:
- 1st: pure COBOL source file
- 2nd: compilation source with compilation directives and a COPY to 1st file

Or see « basis » COBOL directive.

**Comment by phaumer** [comment]
@Andi82ka I would agree with @FALLAI-Denis that using a comment lines, if possible, would be the easiest solution. 

We do have requests to support preprocessors in the future as well, but those would also require to generate some valid COBOL that our editor can consume as well.

**Comment by FALLAI-Denis** [comment]
Hi @phaumer 

Does the COBOL language server process the REPLACE directive by modifying the source code before parsing?

**Comment by phaumer** [comment]
@FALLAI-Denis this is done in the parse tree. 

I am closing this issue as there was no other response from the submitter.
