### ISSUE TITLE
Ability to select only a part of text

### ISSUE THREAD

**Issue by mroy265** [IBM/zopeneditor-about#232]
I am new to Z Open editor and i want to know if there is an option to allow selection of only part of my text with "double click"

For exemple, if i have 
MOVE 'XYZABC' TO VAT-MY-XYZABC-VALUE
MOVE 'XYZDEF' TO VAT-MY-XYZDEF-VALUE

I want for exemple to copy those two lines
and change XYZABC and XYZDEF on both side of the move by ABCXYZ and DEFXYZ :)

That appear ridiculous but that's a simple context of what i need !

Actually, i have to delete 6 caracther and type the 6 new character.
it can be cool if i double click and that selection disapear when i begin to type.
as in any other editor :)

in fact, that method of editing is the default one of VSCode, that is a setting overrided by ibm z open editor.
so am i able to reset it to the default one of VSCode ? 

Thank you

**Comment by phaumer** [comment]
@mroy265 thanks for the question. Yes, we deliberately wanted the entire variable to be selected with a double-click and changed that for our COBOL language definition as the `-` is just a minus in other languages. 

However, there might be other ways to solve this by using [regular expression query-replace](https://dev.to/rfornal/vs-code-search-and-replace-regex-mn2) in VS Code. Also perhaps [multi-cursor selections](https://code.visualstudio.com/docs/editor/codebasics#_multiple-selections-multicursor) might be helpful here?

**Comment by phaumer** [comment]
Closing as there was no other response from the submitter.
