### ISSUE TITLE
Z open editor and zowe V2

### ISSUE THREAD

**Issue by kraabrsg** [IBM/zopeneditor-about#238]
## Development environment used

- Z Open Editor version:
- Editor Platform
  - [X] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version:
- Operating System (on which VS Code runs such as Windows 10 2004, otherwise name and version of platform such as OpenShift v4.3): Windows 10 Enterprise 10.0.19044 Build 19044
- Java Version (when using VS Code or Theia, execute `java -version` and paste the details here): JAVA_HOME is set to jdk 8
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version: 7.0.2
  - Node.js version: 16.14.2
- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html) how to get them): yes/no

## Problem Description

At startup
![grafik](https://user-images.githubusercontent.com/86772851/165750622-fca3274e-023f-40ba-a830-0577005bf94d.png)

Log set to DEBUG:
```
2022-04-28T14:05:16.594+0200 DEBUG: Zowe CLI Secure Credentials Plugin is active. Will initialize Z Open Editor to utilize it.
2022-04-28T14:05:16.605+0200 DEBUG: Zowe CLI Secure Credentials Plugin successfully activated for Z Open Editor.
2022-04-28T14:05:16.806+0200 WARN : The Zowe Explorer VS Code extension was not found or it failed to activate because of an error. Other reasons could be that you might have disabled it or are running an unsupported version. You will not be able to use Zowe Explorer with the IBM Remote System Explorer API (RSE API). The following error was found: "{}"
2022-04-28T14:05:17.156+0200 DEBUG: UsageReporter: Sending the following telemetry data: {"eventName":"activated","properties":{"editor":"Visual Studio Code"}}
2022-04-28T14:05:17.159+0200 DEBUG: UsageReporter: Sending the following telemetry data: {"eventName":"java/found","properties":{"editor":"Visual Studio Code","platform":"win32","java.majorversion":"1.8","java.vendor":"oracle"},"measurements":{"sinceActivated":0.003}}
2022-04-28T14:05:17.164+0200 DEBUG: JavaFinder: Used the "JAVA_HOME" environment variable to locate Java.
2022-04-28T14:05:17.760+0200 DEBUG: Z Open Editor environment summary:
- Z Open Editor version: 2.0.2
- Editor platform: Visual Studio Code
- Editor platform version: 1.66.0
- Required minimal editor platform version: ^1.53.2
- Editor installation root directory: c:\Entwicklung\_VSCDOE_TEST\ZOWE_PLI\resources\app
- Editor installation id: 60c996423c869f575fa4dd8886b167f8e6525788fbf5d7c1ffba8b0a0d0ed9ce
- Editor workspaces: c:\Entwicklung\_VSCDOE_TEST\_zowe_ws_v1_0\PR-BBS-556
- Is a valid Java configured: true
  - Java: C:\Entwicklung\java\jdk1.8.0\bin\java.exe
  - Java memory allocation: 512
  - Java startup user settings: Not defined.
- Key user settings:
  - Unreachable Code enabled: true
  - ZAPP files enabled: false
  - Enforce Case Sensitive Include File Names: false
  - ZAPP schema used: file:///c%3A/Entwicklung/_VSCDOE_TEST/ZOWE_PLI/data/extensions/ibm.zopeneditor-2.0.2/resources/zapp-schema-0.0.2.json
  - IBM User Build enabled: true
  - Zowe CLI API version used for profile management: 6
  - Zowe CLI Secure Credentials enabled: true
  - Zowe CLI profiles of types rse, zosmf or ssh found: 
  - Zowe CLI files profile name specified in VS Code user settings: Not defined.
  - Zowe CLI SSH profile name specified in VS Code user settings: Not defined.
  - Zowe CLI files profile used for remote include files: No profile found.
  - Zowe CLI SSH profile used: No profile found.
  - Zowe Explorer RSE API Mappings File setting: Not defined.
  - Zowe Temp-Dir value: Not defined.
  - COBOL Property Groups defined: mvs-members
  - COBOL include file extensions: .cpy,.copybook,.copy,.cobcopy
  - PL/I Property Groups defined: mvs-members,PLI
  - PL/I include file extensions: .inc,.include,.plinc,.pcx,.pci
  - HLASM Property Groups defined: mvs-members
  - HLASM include file extensions: .s,.assemble,.asm,.hlasm,.hla
  - VS Code Files Assocications: *.COBOL*:cobol,*.COB*:cobol,*.COBCOPY*:cobol,*.COPYBOOK*:cobol,*.COPY*:cobol,*.PL1*:pl1,*.PLI*:pl1,*.INC*:pl1,*.INCLUDE*:pl1,*.SOURCE*:pl1,*.JCL*:jcl,*.ASM*:hlasm,*.ASSEMBLE*:hlasm,*.HLASM*:hlasm,*.HLA*:hlasm,*.pli*:pl1
- Zowe Explorer VS Code Extension version: 2.0.0
  - Successfully activated: true
  - Installation path: c:\Entwicklung\_VSCDOE_TEST\ZOWE_PLI\data\extensions\zowe.vscode-extension-for-zowe-2.0.0
  - Log file location: c:\Entwicklung\_VSCDOE_TEST\ZOWE_PLI\data\extensions\zowe.vscode-extension-for-zowe-2.0.0\logs
- Other VS Code extensions visible: vscode.bat(1.0.0),vscode.clojure(1.0.0),vscode.coffeescript(1.0.0),vscode.configuration-editing(1.0.0),vscode.cpp(1.0.0),vscode.csharp(1.0.0),vscode.css(1.0.0),vscode.css-language-features(1.0.0),vscode.dart(1.0.0),vscode.debug-auto-launch(1.0.0),vscode.debug-server-ready(1.0.0),vscode.diff(1.0.0),vscode.docker(1.0.0),vscode.emmet(1.0.0),vscode.extension-editing(1.0.0),vscode.fsharp(1.0.0),vscode.git(1.0.0),vscode.git-base(1.0.0),vscode.github(0.0.1),vscode.github-authentication(0.0.2),vscode.go(1.0.0),vscode.groovy(1.0.0),vscode.grunt(1.0.0),vscode.gulp(1.0.0),vscode.handlebars(1.0.0),vscode.hlsl(1.0.0),vscode.html(1.0.0),vscode.html-language-features(1.0.0),vscode.image-preview(1.0.0),vscode.ini(1.0.0),vscode.ipynb(1.0.0),vscode.jake(1.0.0),vscode.java(1.0.0),vscode.javascript(1.0.0),vscode.json(1.0.0),vscode.json-language-features(1.0.0),vscode.julia(1.0.0),vscode.latex(1.0.0),vscode.less(1.0.0),vscode.log(1.0.0),vscode.lua(1.0.0),vscode.make(1.0.0),vscode.markdown(1.0.0),vscode.markdown-language-features(1.0.0),vscode.markdown-math(1.0.0),vscode.merge-conflict(1.0.0),vscode.microsoft-authentication(0.0.1),ms-vscode-remote.remote-wsl-recommender(0.0.15),ms-vscode.js-debug(1.66.1),ms-vscode.js-debug-companion(1.0.17),ms-vscode.references-view(0.0.89),ms-vscode.vscode-js-profile-table(1.0.0),vscode.builtin-notebook-renderers(1.0.0),vscode.npm(1.0.1),vscode.objective-c(1.0.0),vscode.perl(1.0.0),vscode.php(1.0.0),vscode.php-language-features(1.0.0),vscode.powershell(1.0.0),vscode.pug(1.0.0),vscode.python(1.0.0),vscode.r(1.0.0),vscode.razor(1.0.0),vscode.restructuredtext(1.0.0),vscode.ruby(1.0.0),vscode.rust(1.0.0),vscode.scss(1.0.0),vscode.search-result(1.0.0),vscode.shaderlab(1.0.0),vscode.shellscript(1.0.0),vscode.simple-browser(1.0.0),vscode.sql(1.0.0),vscode.swift(1.0.0),vscode.theme-abyss(1.0.0),vscode.theme-defaults(1.0.0),vscode.theme-kimbie-dark(1.0.0),vscode.theme-monokai(1.0.0),vscode.theme-monokai-dimmed(1.0.0),vscode.theme-quietlight(1.0.0),vscode.theme-red(1.0.0),vscode.vscode-theme-seti(1.0.0),vscode.theme-solarized-dark(1.0.0),vscode.theme-solarized-light(1.0.0),vscode.theme-tomorrow-night-blue(1.0.0),vscode.typescript(1.0.0),vscode.typescript-language-features(1.0.0),vscode.vb(1.0.0),vscode.xml(1.0.0),vscode.yaml(1.0.0),93akkord.output-link-to-file(0.0.17),dbaeumer.vscode-eslint(2.2.2),IBM.zopeneditor(2.0.2),Zowe.vscode-extension-for-zowe(2.0.0),rsg.rsghostdev(0.0.1)
2022-04-28T14:05:18.148+0200 INFO : IBM Z Open Editor extension has (re)started.
2022-04-28T14:09:02.854+0200 DEBUG: ZLanguageServer.buildServerOptions: Starting PL1 language server from "language-server".
2022-04-28T14:09:02.928+0200 DEBUG: ZLanguageServer: Will start a language server with command "C:\Entwicklung\java\jdk1.8.0\bin\java.exe -Declipse.application=com.ibm.wazi.lsp.pli.core.languageServer,-Dosgi.bundles.defaultStartLevel=4,-Declipse.product=com.ibm.wazi.lsp.pli.core.languageServerProduct,-Xmx512m,-jar,c:\Entwicklung\_VSCDOE_TEST\ZOWE_PLI\data\extensions\ibm.zopeneditor-2.0.2\language-server\plugins\org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar,-configuration,c:\Entwicklung\_VSCDOE_TEST\ZOWE_PLI\data\extensions\ibm.zopeneditor-2.0.2\language-server\pl1_config_win,-data,C:\Users\MYUSER\AppData\Local\Temp\_ws_1651147742928".
2022-04-28T14:09:02.932+0200 DEBUG: AbstractZLanguageClient.initializeLanguageClient: Started initializing a new PL1 language client with these initialization options: {"includeFileExtensions":[".inc",".include",".plinc",".pcx",".pci"],"compilerOptions":"NOT(^), OR(!), MARGINS(2,100)"}.
2022-04-28T14:09:05.186+0200 DEBUG: UsageReporter: Sending the following telemetry data: {"eventName":"document/didOpen","properties":{"editor":"Visual Studio Code","language":"pl1"},"measurements":{"sinceActivated":228.03}}
2022-04-28T14:09:05.315+0200 DEBUG: ZLanguagesResourceResolver.documentRequested: The PL1 language server requested the following include file: "MEMBER#". The ID for this request was assigned as "isz11m" There are 1 pending requests being processed.
2022-04-28T14:09:05.316+0200 DEBUG: ZLanguagesResourceResolver.findIncludeFiles(RequestId:isz11m): Started looking for "MEMBER#" in 2 property groups: [mvs-members, PLI]. Will search in that order.
2022-04-28T14:09:05.522+0200 ERROR: You specified an MVS Property Group in your Settings, but no valid Zowe Profile was found that could be used to load files from MVS. Create a Zowe Profile and try again.
2022-04-28T14:09:05.748+0200 DEBUG: ZLanguagesResourceResolver.findIncludeFiles(RequestId:isz11m): Looking for local or downloaded "MEMBER#" in [] using file extensions [".inc",".include",".plinc",".pcx",".pci"].
2022-04-28T14:09:05.749+0200 DEBUG: ZLanguagesResourceResolver.findIncludeFiles(RequestId:isz11m): Looking for local or downloaded "MEMBER#" in [] using file extensions [".inc",".include",".plinc",".pcx",".pci"].
2022-04-28T14:09:05.750+0200 DEBUG: ZLanguagesResourceResolver.findIncludeFiles(RequestId:isz11m): Did not find "MEMBER#"
2022-04-28T14:09:05.750+0200 DEBUG: UsageReporter: Sending the following telemetry data: {"eventName":"includes/found/failed","properties":{"editor":"Visual Studio Code","language":"pl1"},"measurements":{"sinceActivated":228.594}}
2022-04-28T14:09:05.752+0200 WARN : The PL1 language server requested the include file "MEMBER#", which was not found. enforceCaseSensitiveIncludeFileNames was set to false. Check your Zowe CLI profile and property group settings and, if you have not already done so, switch to the "DEBUG" log level for more information.
2022-04-28T14:09:05.753+0200 DEBUG: ZLanguagesResourceResolver.buildResponse(RequestId:isz11m): File "MEMBER#" was not found.
.....
```

  - Zowe CLI API version used for profile management: 6   -> **shouldn't this be Version 7 ?**
  - Zowe CLI Secure Credentials enabled: true
  - Zowe CLI profiles of types rse, zosmf or ssh found:     -> **no zosmf profile found... ?**

### Detailed steps for reproducing the problem:

Install zowe:
npm i -g @zowe/cli@zowe-v2-lts
zowe plugins install @zowe/cics-for-zowe-cli@zowe-v2-lts @zowe/db2-for-zowe-cli@zowe-v2-lts  @zowe/zos-ftp-for-zowe-cli@zowe-v2-lts
zowe config init --global-config 

replace the generated dummy files with predifined json files 

zowe config set --secure profiles.base.properties.user
zowe config set --secure profiles.base.properties.password

we wrote our own custom vscode extension, implementing zowe functions in combination with z open editor

### Observed behavior

zowe cli commands working like expected:
![grafik](https://user-images.githubusercontent.com/86772851/165753193-98c071bf-9b3a-400d-86fc-d331145b0c3a.png)

This seems somehow use a V1 installation of zowe ???

Thanks!

**Comment by phaumer** [comment]
@kraabrsg we have seen these errors when there was a problem with the config file, in particular the `defaults` were missing. These schema does not seem to enforce those fields. Do you have defaults defined?

**Comment by kraabrsg** [comment]
Hi @phaumer thanks for getting back on this.

Defaults are definend:

![grafik](https://user-images.githubusercontent.com/86772851/165886512-c60eca63-8716-4719-9d9f-02a51144215a.png)


I will start and install zowe from scratch, just to be sure, if it solves the problem i will report here back (my colleaugues has the same problem )

**Comment by phaumer** [comment]
@kraabrsg we are not able to reproduce the problem. My colleague and I created a German Windows VM (just in case) and followed all your steps above using your plugins only. The two cases in which Zowe Explorer activation failed (for which we should provide better errors messages in the future) are 

- when there were errors or defaults missing in the zowe.config.json file
- when I had a zowe.config.json file in other places, such as my top-level home dir, without the matching schema

Could you do the following if possible?

1. Uninstall Z Open Editor and your own extension and just use Zowe Explorer and see if that works on its own. We assume that it does not work and the problem is actually in Zowe Explorer. 
2. Delete the log files in C:\Users\user\.vscode\extensions\zowe.vscode-extension-for-zowe-2.0.0\logs
3. Delete your ~/.zowe folder (or zip and delete to preserve it) and recreate one using `init --global-config` with just dummy values such as example.com for the host that you could share with us.
4. Start VS Code with just Zowe Explorer and if the problem is reproduced attach here the zowe.config.json, zowe.schema.json, and the two log files from the vscode folder above.

**Comment by kraabrsg** [comment]
@phaumer thanks for getting back on this.

We are familiar with the two cases, and found these pitfalls too(found no "loose" zowe.config.json )...

1.) uninstall of our own extension and z open editor, after reload (and restart) the error does not show up anymore...
2.) done
3.) done and executed `zowe config init --global-config`
4.) i attached the log files and the zowe json files

Interestingly in the log files are errors, that no default profiles are set, that seems to reason why it is not working (but it should work that way, should i file this in the zowe cli repo ?)....

[zowe.zip](https://github.com/IBM/zopeneditor-about/files/8600964/zowe.zip)
[logs.zip](https://github.com/IBM/zopeneditor-about/files/8600965/logs.zip)

Thank you!

**Comment by phaumer** [comment]
@kraabrsg thanks so much. Using your files everything just works for me. I do not get the "no default profiles" message at all. It just finds them and things start up correctly.  

I wonder where the difference is to your setup. Could you open an issue in the Zowe Explorer repo?  I see a perhaps [similar issue filed there when using a mounted network drive](https://github.com/zowe/vscode-extension-for-zowe/issues/1773). I now suspect that there is a problem with CLI's Imperative searching in many and relative other folders for a config file. But in your case I know that your CLI works... Let's discuss with Zowe CLI people over at the Zowe repo.

**Comment by phaumer** [comment]
@kraabrsg we now adopted the changes we did in Zowe for using ZOWE_CLI_HOME for Z Open Editor as well. Let us know if this now works for your.

**Comment by kraabrsg** [comment]
Hi @phaumer  thanks for the update, unfortantly the error is not gone(zowe explorer: 2.0.2, z open editor: 2.0.3):

![grafik](https://user-images.githubusercontent.com/86772851/169746277-31860812-d496-4229-8e7b-98be7ac0055c.png)

**Comment by FALLAI-Denis** [comment]
Hi @kraabrsg,

I understand that you have upgraded to Zowe CLI V2.
You initialized the `zowe.cofig.json` file using the `zowe config init --global-config` command. 
I have already seen in other issues that this command generates errors in the `zowe.config.json` file, in particular by declaring the `codePage` property instead of the `encoding` property.

For my part, I also use Zowe CLI V2, but my` zowe.config.json` file was created by migrating Zowe CLI V1 profiles, (with many issues...).
I don't use a `base` profile.

To diagnose your problem, I suggest that you validate the profiles by means of Zowe CLI command to access files, jobs, etc.
The command  `zowe zosmf check status` doesn't validate much except connecting to the z/OSMF server.

If the Zowe CLI commands for files, jobs, etc., work without problems, then (temporarily) remove the `base` profile by reporting its properties in the service profiles.

Also see if there isn't a `zowe.config.json` or `zowe.config.user.json` file placed in the VS Code workspace because it takes precedence over the one declared in your home directory (actually Zowe does a merge of all `zowe.config.json` / `zowe.config.user.json` files that are "visible" from where Zowe CLI commands are run).
See [Property overrides with multiple config files](https://github.com/zowe/zowe-cli/issues/1425#issuecomment-1133156522)

**Comment by FALLAI-Denis** [comment]
Hi @kraabrsg,

Developing an extension at same level as Z Open Editor, or even lower level, may be a heavy task... and you may create a technical debt for your company by having to maintain it... but it's your choice and there must be good reasons for this.

You don't have a `.zowe` folder in your home directory... very strange, because with Zowe V2, you should find there at least:
* a `bin` subfolder containing the Zowe daemon binary
* a `plugins` subfolder with installed plugins
* a `settings` subfolder containing the imperative.json file declaring the active security manager
* a `web-help` subfolder containing help in html format (if generated)
* a `zowe` subfolder containing logs 

I also recommended increasing the memory size allocated to Java to 1024 instead of 512.

What happens if you try to issue a Zowe CLI command from a VS Code Terminal window?

An error message indicates that Zowe Explorer is not active in VS Code. Is this really the case?
Without Zowe Explorer, Z Open Editor cannot do anything compared to Zowe CLI, because it delegates all actions to it.

Is there anything in the `C:\Users\<user>\AppData\Roaming\Code\logs\<ts>\exthost1\exthost.log` log about Zowe Explorer or Zowe CLI?

My log file for Z Open Editor:
```
This log file is available at c:\Users\S0070188\AppData\Roaming\Code\logs\20220523T190334\exthost1\IBM.zopeneditor\zopeneditor-20220523-170406.log
Initialized IBM Z Open Editor logger on level "DEBUG".
2022-05-23T19:04:06.496+02:00 DEBUG: Zowe CLI Secure Credentials Plugin is active. Will initialize Z Open Editor to utilize it.
2022-05-23T19:04:06.502+02:00 DEBUG: Zowe CLI Secure Credentials Plugin successfully activated for Z Open Editor.
2022-05-23T19:04:08.904+02:00 INFO : Zowe Explorer was modified for IBM Remote System Explorer API (RSE API) support by IBM Z Open Editor.
2022-05-23T19:04:09.188+02:00 DEBUG: UsageReporter: Sending the following telemetry data: {"eventName":"activated","properties":{"editor":"Visual Studio Code"}}
2022-05-23T19:04:09.192+02:00 DEBUG: UsageReporter: Sending the following telemetry data: {"eventName":"java/found","properties":{"editor":"Visual Studio Code","platform":"win32","java.majorversion":"1.8","java.vendor":"oracle"},"measurements":{"sinceActivated":0.004}}
2022-05-23T19:04:09.200+02:00 DEBUG: JavaFinder: Used the "JAVA_HOME" environment variable to locate Java.
2022-05-23T19:04:09.500+02:00 DEBUG: Z Open Editor environment summary:
- Z Open Editor version: 2.0.3
- Editor platform: Visual Studio Code
- Editor platform version: 1.67.2
- Required minimal editor platform version: ^1.53.2
- Editor installation root directory: c:\ProgramData\Microsoft VS Code\resources\app
- Editor installation id: 4c50888f99c01e5c2ea04378fd891e904a9d963379129e49977589f9fafad091
- Editor workspaces: c:\Trv\DepotsGIT\ceab3-environn-osintrn-central-formation-cobol-module1
- Is a valid Java configured: true
  - Java: C:\Program Files\Java\jre8\bin\java.exe
  - Java memory allocation: 2048
  - Java startup user settings: Not defined.
- Key user settings:
  - Unreachable Code enabled: true
  - ZAPP files enabled: true
  - Enforce Case Sensitive Include File Names: false
  - ZAPP schema used: file:///c%3A/Users/S0070188/.vscode/extensions/ibm.zopeneditor-2.0.3/resources/zapp-schema-0.0.2.json
  - IBM User Build enabled: false
  - Zowe CLI API version used for profile management: 7
  - Zowe CLI Secure Credentials enabled: true
  - Zowe CLI profiles of types rse, zosmf or ssh found: GMVS(zosmf),EMVS(zosmf),EMVS-JENKINS(zosmf),GMVS-JENKINS(zosmf),SYSB(zosmf),SYSB-JENKINS(zosmf),TMVS(zosmf),TMVS-JENKINS(zosmf),GMVS-SSH(ssh),EMVS-SSH(ssh),SYSB-SSH(ssh),TMVS-SSH(ssh)
  - Zowe CLI files profile name specified in VS Code user settings: GMVS
  - Zowe CLI SSH profile name specified in VS Code user settings: GMVS-SSH
  - Zowe CLI files profile used for remote include files: GMVS
  - Zowe CLI SSH profile used: GMVS-SSH
  - Zowe Explorer RSE API Mappings File setting: Not defined.
  - Zowe Temp-Dir value: C:\Trv\DepotsGIT\Temp
  - COBOL Property Groups defined: 
  - COBOL include file extensions: .cpy,.copybook,.copy,.cobcopy
  - PL/I Property Groups defined: 
  - PL/I include file extensions: .inc,.include,.plinc,.pcx,.pci
  - HLASM Property Groups defined: 
  - HLASM include file extensions: .s,.assemble,.asm,.hlasm,.hla
  - VS Code Files Assocications: *.COBCOPY*:cobol,*.COBSRCE*:cobol,*.COPYBOOK*:cobol,*.COPYCOB*:cobol,*.COPY*:cobol,*.PL1*:pl1,*.PLI*:pl1,*.INC*:pl1,*.INCLUDE*:pl1,*.JCL*:jcl,*.CNTL*:jcl,*.ASM*:hlasm,*.ASSEMBLE*:hlasm,*.HLASM*:hlasm,*.HLA*:hlasm,*.COBOL*:cobol,*.COB*:cobol,*.SRCELIB*:cobol,*.COBCOPY:cobol,*.COPYBOOK:cobol,*.COPY:cobol,*.COPYLIB:cobol,*.JCL:jcl,*.CNTL:jcl,*.ASM:hlasm,*.HLASM:hlasm,*.COBOL:cobol,*.COB:cobol,*.build:yaml
- Zowe Explorer VS Code Extension version: 2.0.2
  - Successfully activated: true
  - Installation path: c:\Users\S0070188\.vscode\extensions\zowe.vscode-extension-for-zowe-2.0.2
  - Log file location: c:\Users\S0070188\.vscode\extensions\zowe.vscode-extension-for-zowe-2.0.2\logs
- Other VS Code extensions visible: vscode.bat(1.0.0),vscode.clojure(1.0.0),vscode.coffeescript(1.0.0),vscode.configuration-editing(1.0.0),vscode.cpp(1.0.0),vscode.csharp(1.0.0),vscode.css(1.0.0),vscode.css-language-features(1.0.0),vscode.dart(1.0.0),vscode.debug-auto-launch(1.0.0),vscode.debug-server-ready(1.0.0),vscode.diff(1.0.0),vscode.docker(1.0.0),vscode.emmet(1.0.0),vscode.extension-editing(1.0.0),vscode.fsharp(1.0.0),vscode.git(1.0.0),vscode.git-base(1.0.0),vscode.github(0.0.1),vscode.github-authentication(0.0.2),vscode.go(1.0.0),vscode.groovy(1.0.0),vscode.grunt(1.0.0),vscode.gulp(1.0.0),vscode.handlebars(1.0.0),vscode.hlsl(1.0.0),vscode.html(1.0.0),vscode.html-language-features(1.0.0),vscode.image-preview(1.0.0),vscode.ini(1.0.0),vscode.ipynb(1.0.0),vscode.jake(1.0.0),vscode.java(1.0.0),vscode.javascript(1.0.0),vscode.json(1.0.0),vscode.json-language-features(1.0.0),vscode.julia(1.0.0),vscode.latex(1.0.0),vscode.less(1.0.0),vscode.log(1.0.0),vscode.lua(1.0.0),vscode.make(1.0.0),vscode.markdown(1.0.0),vscode.markdown-language-features(1.0.0),vscode.markdown-math(1.0.0),vscode.merge-conflict(1.0.0),vscode.microsoft-authentication(0.0.1),ms-vscode-remote.remote-wsl-recommender(0.0.15),ms-vscode.js-debug(1.67.2),ms-vscode.js-debug-companion(1.0.18),ms-vscode.references-view(0.0.89),ms-vscode.vscode-js-profile-table(1.0.1),vscode.builtin-notebook-renderers(1.0.0),vscode.npm(1.0.1),vscode.objective-c(1.0.0),vscode.perl(1.0.0),vscode.php(1.0.0),vscode.php-language-features(1.0.0),vscode.powershell(1.0.0),vscode.pug(1.0.0),vscode.python(1.0.0),vscode.r(1.0.0),vscode.razor(1.0.0),vscode.restructuredtext(1.0.0),vscode.ruby(1.0.0),vscode.rust(1.0.0),vscode.scss(1.0.0),vscode.search-result(1.0.0),vscode.shaderlab(1.0.0),vscode.shellscript(1.0.0),vscode.simple-browser(1.0.0),vscode.sql(1.0.0),vscode.swift(1.0.0),vscode.theme-abyss(1.0.0),vscode.theme-defaults(1.0.0),vscode.theme-kimbie-dark(1.0.0),vscode.theme-monokai(1.0.0),vscode.theme-monokai-dimmed(1.0.0),vscode.theme-quietlight(1.0.0),vscode.theme-red(1.0.0),vscode.vscode-theme-seti(1.0.0),vscode.theme-solarized-dark(1.0.0),vscode.theme-solarized-light(1.0.0),vscode.theme-tomorrow-night-blue(1.0.0),vscode.typescript(1.0.0),vscode.typescript-language-features(1.0.0),vscode.vb(1.0.0),vscode.xml(1.0.0),vscode.yaml(1.0.0),andrejunges.Handlebars(0.4.1),atlassian.atlascode(2.10.12),BroadcomMFD.bridge-for-git-explorer(0.2.4),BroadcomMFD.ccf(1.0.1),BroadcomMFD.explorer-for-endevor(1.1.0),eamodio.gitlens(12.0.6),Greenbyte.handlebars-preview(1.4.0),hediet.vscode-drawio(1.6.4),hilleer.yaml-plus-json(1.10.0),humao.rest-client(0.24.6),IBM.db2forzosdeveloperextension(1.3.5),IBM.zopeneditor(2.0.3),ITCE-MathieuFay.itce-assistant-cobol(2.9.35),ITCE-MathieuFay.itce-banniere(1.0.1),ITCE-MathieuFay.itce-build-mainframe(1.1.0),ITCE-MathieuFay.itce-guide-git(1.2.1),JayShah.handlebars-vsce(1.0.0),jebbs.plantuml(2.17.2),juliencroain.markdown-viewer(1.0.0),juliencroain.private-extension-manager(1.4.9),Macro4.tracemaster(0.0.10),marp-team.marp-vscode(1.5.2),mechatroner.rainbow-csv(2.4.0),mhutchie.git-graph(1.30.0),MS-CEINTL.vscode-language-pack-fr(1.67.3),ms-vscode-remote.remote-ssh(0.80.0),ms-vscode-remote.remote-ssh-edit(0.80.0),ms-vscode.hexeditor(1.9.6),nhoizey.gremlins(0.26.0),redhat.vscode-commons(0.0.6),redhat.vscode-yaml(1.7.0),SonarSource.sonarlint-vscode(2.3.0),theumletteam.umlet(1.0.4),zaaack.markdown-editor(0.1.10),zokugun.cobol-folding(0.2.0),zokugun.explicit-folding(0.21.0),Zowe.vscode-extension-for-zowe(2.0.2)
2022-05-23T19:04:09.524+02:00 DEBUG: ZAPP: A valid zapp file was found in "c:\Trv\DepotsGIT\ceab3-environn-osintrn-central-formation-cobol-module1" and will be used instead of user settings.
2022-05-23T19:04:09.932+02:00 INFO : IBM Z Open Editor extension has (re)started.
```

Do you have a `c:\Users\<user>\.vscode\extensions\zowe.vscode-extension-for-zowe-2.0.2\logs` folder with `zowe.log` and `imperative.log` files?

**Comment by JillieBeanSim** [comment]
@kraabrsg sorry to hear you are having difficulties migrating to v2 of Zowe Explorer and Z Open Editor. I have a couple questions:
1. What version of node are you using?  Zowe CLI, Zowe Explorer and Z Open Editor have dropped support for node 12 with the v2 of Zowe release.
2.  Do you use nvm to handle node version management? If so I have noticed that if I change the version of node using nvm after the CLI is installed and try to update or uninstall it fails and I have to switch back to the original node version via nvm to uninstall.
Not having a `.zowe` folder in the home directory after installation of Zowe CLI is an indicator that something went wrong during installation.

**Comment by kraabrsg** [comment]
Hi @JillieBeanSim 
1.)V16,15,0
2.) no NVM
3.) we are just replacing the zowe.config.json file

As for the location, we have a seperate Folder(ZOWE_CLI_HOME path variable ) where the `zowe.config.json` and `zowe.schema.json` file is located.
![grafik](https://user-images.githubusercontent.com/86772851/170181593-b6714b68-062c-469f-8b71-516451412367.png)

`where zowe` points to the folder where the portable version of nodejs (npm) is located, that is a different one.

```
Installed plugins:

 -- pluginName: @zowe/cics-for-zowe-cli
 -- package: @zowe/cics-for-zowe-cli
 -- version: 5.0.0
 -- registry: https://registry.npmjs.org/

 -- pluginName: @zowe/db2-for-zowe-cli
 -- package: @zowe/db2-for-zowe-cli
 -- version: 5.0.0
 -- registry: https://registry.npmjs.org/

 -- pluginName: @zowe/zos-ftp-for-zowe-cli
 -- package: @zowe/zos-ftp-for-zowe-cli
 -- version: 2.0.0
 -- registry: https://registry.npmjs.org/
```

**Comment by FALLAI-Denis** [comment]
Hi @kraabrsg 

Do you have a `c:\Users\<user>\.vscode\extensions\zowe.vscode-extension-for-zowe-2.0.2\logs` folder or equivalent with a zowe.log and a imperative.log files?

**Comment by FALLAI-Denis** [comment]
Hi @kraabrsg 

pershaps same as https://github.com/zowe/vscode-extension-for-zowe/issues/1820

**Comment by JillieBeanSim** [comment]
Thanks @kraabrsg for all of the information, I will work on recreating using the Zowe CLI Home envVar and node 16. this helps a lot.

**Comment by JillieBeanSim** [comment]
we have a couple environment variable issues open in Zowe Explorer that are in the plan for this PI
https://github.com/zowe/vscode-extension-for-zowe/issues/1825
https://github.com/zowe/vscode-extension-for-zowe/issues/1747

**Comment by JillieBeanSim** [comment]
@kraabrsg has the issue been solved with the Zowe Explorer fixes for the issues mentioned above?

**Comment by kraabrsg** [comment]
Hi @JillieBeanSim we don't use Zowe Explorer, Z Open Editor and Zowe CLI anymore (just the SDK's), so i can't confirm.
