### ISSUE TITLE
User Build - Support configuration by zapp.yaml

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#239]
## Description of the enhancement requested

By analyzing the contents of the zap-schema-0.0.2.json file, it seems that the zapp.yaml file can handle the configuration(s) of user builds.

Is this fully operational? (There is no information about this in the Z Open Editor online documentation).

Can multiple user build configurations be declared in zapp.yaml?

**Comment by phaumer** [comment]
Yes, sorry about that. We had special content about it [here](https://www.ibm.com/docs/en/cloud-paks/z-modernization-stack/2022.1.1?topic=code-experimental-configure-your-applications-zapp-files), but it got lost in the editing processes. 

I added it now also [here in the editor docs](https://ibm.github.io/zopeneditor-about/Docs/zapp.html#a-zapp-file-example) to avoid the same editing problem in the future. It should appear back in the page above soon.

The main doc pages for user build are
- <https://www.ibm.com/docs/en/cloud-paks/z-modernization-stack/2022.1.1?topic=code-setting-up-user-build>
- <https://www.ibm.com/docs/en/cloud-paks/z-modernization-stack/2022.1.1?topic=code-building-cobol-pli-hlasm-programs-user-build>

**Comment by phaumer** [comment]
Currently, there can only be one profile for dbb in a zapp file. We do think that adding multiple and settings-based switching in the future would make sense, though.
