### ISSUE TITLE
COBOL - Misinterpreting comments in a COPY sentence

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#248]
## Development environment used

- Z Open Editor version: 2.0.3
- Editor Platform
  - [X] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version: 1.67.2
- Operating System: Windows 10 64 20H2
- Java Version: 1.8
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version: 
  - Node.js version:
- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html) how to get them): yes/no

## Problem Description

In a COPY directive, the COBOL Language Server interprets all lines, including comment lines, as being COBOL source code, and then reports errors on the comment lines since it is not COBOL.

![image](https://user-images.githubusercontent.com/63861965/171607776-93de5fe9-fb09-48a9-ac22-93e2d37d679f.png)

![image](https://user-images.githubusercontent.com/63861965/171607815-babca39c-2588-41bc-aa14-8d44aaee10a9.png)

**Comment by FALLAI-Denis** [comment]
Same problem with compilation directive interspersed in the COPY sentence: 

![image](https://user-images.githubusercontent.com/63861965/173223472-04adb718-1ffa-4b3e-a979-795da19ae736.png)

**Comment by FALLAI-Denis** [comment]
Related issue: #346

**Comment by phaumer** [comment]
Fixed in Z Open Editor v3.2.0
