### ISSUE TITLE
Mishandling of password change since Zowe CLI V2 for COPYBOOKs remote search in COBOL program

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#249]
## Development environment used

- Z Open Editor version: 2.1.0
- Editor Platform
  - [X] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version: 1.68
- Operating System: Windows 10 
- Java Version: 1.8
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version: 
  - Node.js version:
- Logs attached: no

## Problem Description

Detailed steps for reproducing the problem:

1. Change password on remote z/OS using 3270 emulator
2. Start VS Code
3. Open a COBOL file with COPY calls
4. Z Open Editor searches for COPYBOOKs stored on the remote z/OS system, (declarations made in zapp.yaml).
5. ZOE detect invalid password (status 401) and ask for new credentials : user (why ?) and password
6. New credentials are given
7. New credentials are saved
8. ZOE detect invalid password (status 401) and ask for new credentials : user (why ?) and password
9. New credentials are given
6. New credentials are saved
7. ad libidum...
8. user account is revoked on remote z/OS (too much wrong password)

To avoid this, after providing the new credentials and saving them, you must quit VS Code and restart it, and in this case the new credentials are taken into account by Z Open Editor.

The problem appeared with the upgrade to Zowe CLI V2.

We use the `zowe.config.json` file declaration in the Workspace (the Git Repository), plus a `zowe.config.json` file declaration in the user's home directory, (but the `zowe.config. json` from the Workspace is self-sufficient).

### Observed behavior

Z Open Editor seems to continue to use the old credentials, probably stored in memory, instead of the new ones that were entered.

RACF errors on invalid password in mvs log.

### Expected behavior

The new credentials provided, and saved, must be used by Z Open Editor (or Zowe Explorer?).

**Comment by sdaimwood** [comment]
> Does this have to do with [Update Credentials does not load new password into profiles cache with v2 profiles](https://github.com/zowe/vscode-extension-for-zowe/issues/1799)?

Hi Dennis, yes that should be right. Do you still experience this after updating Zowe Explorer to 2.1.0? It was just released to marketplace a couple hours ago. I just tested locally and the problem seems to be fixed.

**Comment by FALLAI-Denis** [comment]
Seems fixed with the upgrade to Zowe Explorer 2.1.0.
