### ISSUE TITLE
cannot open (job sysout file)

### ISSUE THREAD

**Issue by cds-ari** [IBM/zopeneditor-about#25]
I can expand a JOB's separate sysout files in the JOBS explorer window but when I click on one I get the following (names and URL changed for privacy):

cannot open zosspool:JOBABCD.JOB00058.JESMSGLG%3F%5B%22zowprof1%22%2C%7B%22recfm%22%3A%22UA%22%2C%22records-url%22%3A%22https%3A%2F%2F***.**.***.98%3A10443%2Fzosmf%2Frestjobs%2Fjobs%2FJ0000058SVSCJES2D74B1E0E.......%3A%2Ffiles%2F2%2Frecords%22%2C%22stepname%22%3A%22JES2%22%2C%22subsystem%22%3A%22JES2%22%2C%22job-correlator%22%3A%22J0000058SVSCJES2D74B1E0E.......%3A%22%2C%22byte-count%22%3A1049%2C%22lrecl%22%3A133%2C%22jobid%22%3A%22JOB00058%22%2C%22ddname%22%3A%22JESMSGLG%22%2C%22id%22%3A2%2C%22record-count%22%3A18%2C%22class%22%3A%22X%22%2C%22jobname%22%3A%22JOBABCD%22%2C%22procstep%22%3Anull%7D%5D. Detail: Unexpected end of JSON input

**Comment by phaumer** [comment]
Please file in the git repo for filing Zowe Explorer issue which is here: <https://github.com/zowe/vscode-extension-for-zowe/issues>. This is the repo is for the Z Open Editor VS Code extension.
