### ISSUE TITLE
IBM User Build / COBOL - Detection of nested COPYBOOKs is not performed

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#251]
## Development environment used

- Z Open Editor version: 2.1.0
- Editor Platform
  - [X] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version: 1.68.1
- Operating System: Windows 10 20H2
- Java Version: 1.8
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached: no

## Problem Description

Detailed steps for reproducing the problem:

1. Get the test application from dbb-zappbuild/samples/MortgageApplication/
2. Configure zapp.yaml or settings.json to reference the application's copybook folder
3. Configure the IBM User Build feature in user settings.json and workspace settings.json or in zapp.yaml
4. Open the file cobol/epscmort.cbl
5. Look for the reference to COPYBOOK EPSMTCOM
6. Note the reference to nested EPSMTINP and EPSMTOUT COPYBOOKs
7. Initialize the build environment
8. Request the IBM User Build of the COBOL program EPSCMORT
9. Build fails because COPYBOOKs EPSMTINP and EPSMTOUT are not found (this is not the only COPYBOOK processing problem)

### Observed behavior

The IBM User Build function, basic or full, does not process references to nested COPYBOOKs (COPYBOOK referenced by another COPYBOOK). Only the 1st level of COPYBOOK (COBOL to COPYBOOK) is processed.

Therefore, building a program using nested COPYBOOKs fails.

### Expected behavior

Processing nested COPYBOOKs.

**Comment by phaumer** [comment]
We added support for nested copybooks in 2.1.1 and there is an example for how to use it with user build here now: https://github.com/IBM/zopeneditor-sample/tree/wazi-main/multiroot 

Let us know if this worked for you @FALLAI-Denis
