### ISSUE TITLE
IBM User Build / COBOL - Partial support for paths containing spaces

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#252]
## Development environment used

- Z Open Editor version: 2.1.0
- Editor Platform
  - [X] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version: 1.68.1
- Operating System: Windows 10 20H2
- Java Version: 1.8
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached: yes/no

## Problem Description

The IBM User Build function partially supports the use of path (folder) containing space characters:
* IBM User Build triggers a mkdir command by enclosing the path in single quotes: OK
* IBM User Build triggers a chtag command without enclosing the path in single quotes: KO

### Observed behavior

![image](https://user-images.githubusercontent.com/63861965/176541737-2149a03d-87ea-4412-896b-f00b9aa52adb.png)

**Comment by phaumer** [comment]
Fixed with 2.1.1. We url encode that path now so spaces will show up as %20 on USS.
