### ISSUE TITLE
COBOL - CBL|PROCESS SERVICE directive not recognized

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#253]
## Development environment used

- Z Open Editor version: 2.1.0
- Editor Platform
  - [X] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version: 1.68.1
- Operating System: Windows 10 20H2
- Java Version: 1.8
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached: no

## Problem Description

The `SERVICE` compilation option introduced by a `CBL`|`PROCESS` directive is not accepted by the COBOL language server.

See sample in observed behavior.

### Observed behavior

![image](https://user-images.githubusercontent.com/63861965/177154628-8ecdeb81-9baa-4dae-9f52-94cb42488e36.png)

![image](https://user-images.githubusercontent.com/63861965/177154771-add14a56-33c8-468c-8a64-cea096602422.png)

![image](https://user-images.githubusercontent.com/63861965/177154856-6b18bf04-3996-44fd-9059-21103613cc19.png)

![image](https://user-images.githubusercontent.com/63861965/177154986-94b2d834-5143-48f0-a7a5-a6c2173dc20d.png)

The last problem on the `program-id` seems to be a consequence of other problems in the source code.

![image](https://user-images.githubusercontent.com/63861965/177155142-1ed47400-e0d0-408e-bc99-b3f51339ef1b.png)

**Comment by FALLAI-Denis** [comment]
Note also that the COBOL textmate grammar does not recognize the PROCESS directive, badly colored (incorrect syntax highlighting), which is synonymous with the CBL directive, (the COBOL language server recognizes the PROCESS directive well and does not signal an error to his subject).

**Comment by phaumer** [comment]
Fixed in Z Open Editor 3.1.0
