### ISSUE TITLE
Extensive loading time for REXX parser

### ISSUE THREAD

**Issue by BJostmeyer** [IBM/zopeneditor-about#256]
Hi,

I am using the VSCode extension IBM Z Open Editor to edit REXX file - extgension works fine. However I have REXX files with more than 2000 LoC and 2-3 dozens of Entrypoints. After opening a file like this it takes around 1min before outline is shown. Can this be improved?

**Comment by bknaysi** [comment]
Yes, the REXX performance when editing large or complex files is a known issue. We are working towards fixing it, although the underlying cause is a tricky one to resolve.

**Comment by BJostmeyer** [comment]
Many years ago - I was even using "vi" for C programming. Already at this time there was the possibility to include a "symbols" file  into the editor - and jump straight to the module in which method is implemented. This was not live parsing - it all comes from a file that was created (I believe) with a tool called "ctags". 

All I wanna say - I understand that starting a Java VM and do live parsing will take a while. I am also okay, when this time is spent the FIRST time a file is loaded (only) - after parsing has been done, the results should be saved to some (hidden) file - and next time I start the IDE and load the module it will hopefully show the links faster.

**Comment by phaumer** [comment]
Fixed in Z Open Editor 2.2.0
