### ISSUE TITLE
EXEC CICS INQUIRE SYSTEM missing MAXOPENTCBS option

### ISSUE THREAD

**Issue by ian-burnett** [IBM/zopeneditor-about#257]
## Development environment used

- Z Open Editor version: v2.1.0
- Editor Platform
  - [x] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia

Version: 1.69.0 (user setup)
Commit: 92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9
Date: 2022-07-07T05:28:36.503Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19044

- Java Version (when using VS Code or Theia, execute `java -version` and paste the details here):

openjdk version "11.0.15" 2022-04-19
IBM Semeru Runtime Open Edition 11.0.15.0 (build 11.0.15+10)
Eclipse OpenJ9 VM 11.0.15.0 (build openj9-0.32.0, JRE 11 Windows 10 amd64-64-Bit Compressed References 20220422_352 (JIT enabled, AOT enabled)
OpenJ9   - 9a84ec34e
OMR      - ab24b6666
JCL      - b7b5b42ea6 based on jdk-11.0.15+10)

## Problem Description

Detailed steps for reproducing the problem:

Cobol program:

       PROCESS CICS(SP)

       identification division.
       program-id.              FAIL.

       data division.
       working-storage section.

       01  ws-maxopentcbs       pic s9(8) binary value zero.

       procedure division using dfheiblk.

       main-processing section.

           exec cics inquire system
                             maxopentcbs(ws-maxopentcbs)
                             end-exec.

           goback.
           

### Observed behavior

Error marker on "maxopentcbs" token with popup error message "MAXTASKS expected instead of this input parsing"

### Expected behavior

MAXOPENTCBS is a valid option for the INQUIRE SYSTEM SPI command and has been since at least CICS TS V4.2 (June 2011)

https://www.ibm.com/docs/en/cics-ts/4.2?topic=commands-inquire-system

**Comment by phaumer** [comment]
Fixed in Z Open Editor 3.0.0
