### ISSUE TITLE
Question - Is the installation of Zowe CLI on the workstation still a prerequisite for using Z Open Editor?

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#263]
Hi,

In the past, we always installed the Zowe CLI component on workstations before installing Z Open Editor (and Zowe Explorer).
This with Zowe CLI V1.

It would seem, and this is conditional, that Z Open Editor can work without installing Zowe CLI V2, when a `zowe.config.json` file in the Zowe CLI V2 standard is present either in the Workspace, or in the User's Home Directory.

Can you tell us if the installation of Zowe CLI on the workstation is still a prerequisite for the operation of Z Open Editor (and cascading Zowe Explorer)?

If Zowe CLI is not installed on the workstation, but a` zowe.config.json` file is present, what Z Open Editor features would be impacted?

Thanks.

**Comment by phaumer** [comment]
Our goal was always to not require the installation of Zowe CLI for Zowe Explorer and Z Open Editor and this was the case for the Zowe 1.x profiles. However, there are still some open challenges with the new 2.0 team configuration files, such as merging the json schema when extensions such as RSE API or FTP get installed. 

We will work on a list of currently known issues for why we need CLI at the moment and post it here.

**Comment by JillieBeanSim** [comment]
Hey @FALLAI-Denis the main open issue in Zowe Explorer atm that requires Zowe CLI 7.x to be installed, 7.2.3 or higher as of Zowe Explorer 2.2.0, is Secure Credentials use [ZE issue #1850](https://github.com/zowe/vscode-extension-for-zowe/issues/1850).  With out the CLI installation we are missing a file that is created upon Zowe CLI installation in the home directory, ~/.zowe/settings/imperative.json.
There are some nice to haves that we would like to add to the VS Code extension that are only available via the Zowe CLI like appending registered Zowe Explorer extensions to the global config's schema like the CLI does for plugins, auto-init that gets connection information from the API ML, and config convert to easily convert v1 profiles into a v2 global config.

**Comment by phaumer** [comment]
Closing this one as answered.
