### ISSUE TITLE
Online Dopcumentation Issue - getting a 404 following a link

### ISSUE THREAD

**Issue by BJostmeyer** [IBM/zopeneditor-about#272]
In the online available Documentation I want to get more Information about the "Dependency Based Build" (DBB) and try to follow below link - but unfortunately I end up on a 404 Page - Document not found

![image](https://user-images.githubusercontent.com/36626099/190377065-6c33bf08-5ff5-4b76-8e66-45e0a018b059.png)

**Comment by FALLAI-Denis** [comment]
Hi,

I confirm the broken link.

The information you are looking for is in "IBM Wazi Developer for Red Hat CodeReady Workspaces": [https://www.ibm.com/docs/en/wdfrhcw/1.4.0?topic=code-setting-up-user-build](https://www.ibm.com/docs/en/wdfrhcw/1.4.0?topic=code-setting-up-user-build)

**Comment by phaumer** [comment]
Was waiting for the 2.2.0 docs to be published to fix this. 

The new link is now <https://www.ibm.com/docs/en/cloud-paks/z-modernization-stack/2022.3?topic=code-setting-up-user-build>
