### ISSUE TITLE
No code jumping/peek etc. when copybooks have .cbl extension on version above 1.0.3

### ISSUE THREAD

**Issue by MikeDEVpl** [IBM/zopeneditor-about#273]
## Development environment used

- Z Open Editor version: any above 1.0.3
- Editor Platform:  Visual Studio Code 1.71.1
- Operating System: Windows 11 Version 10.0.22000 Build 22000
- Java Version:
     openjdk 17.0.4.1 2022-08-12
    OpenJDK Runtime Environment Temurin-17.0.4.1+1 (build 17.0.4.1+1)
    OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1 (build 17.0.4.1+1, mixed mode, sharing)
- Logs attached: no

## Problem Description
When both cobol programs and copybooks have an .cbl extension on any version above 1.0.3 code jumping/peek and other 'intelisense' features does not work. Probably cobol program is treated as copybook which does not have those functions.

This happens when I add my property groups configuration (exactly this config "zopeneditor.cobol.includeFileExtensions"):

"zopeneditor.propertygroups": [
        {
            "name": "local-files",
            "type": "local",
            "syslib": [
                "CPY",
                "DCL"
            ]
        }          
    ],
    "zopeneditor.cobol.includeFileExtensions": [
        ".CBL"
    ],

Detailed steps for reproducing the problem:

1. Create two folders CPY & SRB on the same level
2. Copy cobol program to SRB folder
3. Copy copybook which is referenced by program from point 2 to CPY folder
4. Add property groups configuration from above to settings.json
5. Reload extension

### Observed behavior

- We can go to copybook by ctrl+ click
- Advanced editor functions like code jumping/peek etc does not work at any version above 1.0.3

### Expected behavior

- We can go to copybook by ctrl+ click
- Advanced editor functions like code jumping/peek are working

**Comment by phaumer** [comment]
I will label this as an enhancement request while we research this, but I am not optimistic that we can support this. We need a different file extension for copybooks as also the parsing is different of copybooks versus programs. We need to be able to distinguish them.

**Comment by sdaimwood** [comment]
Hi there, due to constraints with how our client and language server handles copybooks, this is not a feature we'll be able to support. Thank you for using Z Open Editor, we appreciate the enhancement request.
