### ISSUE TITLE
COBOL: REMARKS

### ISSUE THREAD

**Issue by RBeacher** [IBM/zopeneditor-about#276]
## Development environment used

- Z Open Editor version:
- Editor Platform
  - [x] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version:
- Operating System (on which VS Code runs such as Windows 10 2004, otherwise name and version of platform such as OpenShift v4.3):  **Windows 10 Enterprise**
- Java Version (when using VS Code or Theia, execute `java -version` and paste the details here):   
**java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)**
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html) how to get them): no

## Problem Description

A working storage variable starting with " REMARKS" will be incorrectly identified as a REMARKS paragraph and subsequent valid definitions and logic will be commented in error.

1. First step

![image](https://user-images.githubusercontent.com/114092834/191558515-d401e52f-05a7-40ad-a138-2ccaf66d3161.png)

-

Working Storage variables should be allowed to start with " REMARKS" without being lexed as comments.

-

**Comment by phaumer** [comment]
Fixed in Z Open Editor 3.0.0
