### ISSUE TITLE
COBOL - zapp.yaml - property-group - Syntax for DEFINE option

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#278]
## Development environment used

- Z Open Editor version: 2.2.0
- Editor Platform
  - [X] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version: 1.71.2
- Operating System: Windows 10 x64 20H2
- Java Version: OpenJDK V11
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached: no

## Problem Description

Z Open Editor, or the COBOL language server, recognizes only one of the two possible syntaxes for the declaration of a "DEFINE" compilation option expressed in the zapp.yaml file (and probably also in settings.json, but not checked): using the equal character as a separator between the variable name and the associated value.
The syntax using the comma character as a separator is not recognized.
However, the comma separator is recommended for compatibility with the USS version of the IBM Enterprise COBOL compiler.

![image](https://user-images.githubusercontent.com/63861965/192108411-10bbfe93-ac39-4694-899e-44be0b7ed618.png)

![image](https://user-images.githubusercontent.com/63861965/192108569-8eda1388-4fb9-4438-ab01-e31be8c01cd6.png)

![image](https://user-images.githubusercontent.com/63861965/192108626-be456d87-7881-43dd-abd0-67e15adeac17.png)

### Expected behavior

Recognition of the two possible syntaxes for the DEFINE compiler option.

**Comment by phaumer** [comment]
Fixed in Z Open Editor 3.1.0
