### ISSUE TITLE
Zowe logo on https://ibm.github.io/zopeneditor-about/ needs fixed

### ISSUE THREAD

**Issue by jmertic** [IBM/zopeneditor-about#28]
Hi!

I see the Zowe logo used on https://ibm.github.io/zopeneditor-about/ in the infograph isn't correct - there's no official stacked version. Could this be changed to the non-stacked version ( sources at https://github.com/openmainframeproject/artwork/blob/master/examples/active.md#zowe-logos )

Thank you!

**Comment by rodney-wilson** [comment]
@jmertic thanks for letting us know. We are working on an updated, non-stacked, Zowe logo.

**Comment by jmertic** [comment]
Thank you @rodney-wilson ! Let us know when it's done.

**Comment by phaumer** [comment]
We will now use the new Logo published here: https://github.com/openmainframeproject/artwork/blob/master/examples/active.md#zowe-logos

**Comment by jmertic** [comment]
Awesome - thank you!

**Comment by rodney-wilson** [comment]
The logo update is done @jmertic. Let us know if this fix is okay: https://ibm.github.io/zopeneditor-about/

**Comment by jmertic** [comment]
Looks perfect - thank you!

**Comment by rodney-wilson** [comment]
You're welcome!
