### ISSUE TITLE
Don't use IBM acronyms as if the world knows what they are.

### ISSUE THREAD

**Issue by jlczuk** [IBM/zopeneditor-about#285]
On this [page,](https://ibm.github.io/zopeneditor-about/Blog/hlasm-blog.html#editor-features) we find this text:
```...Brenton Belmar, a STSM of the zMilicode Team, Mike Fulton, a DE... ```

I suggest changing it to:
```...Brenton Belmar, a Senior Technical Staff Member of the zMilicode Team, Mike Fulton, a Distinguished Engineer... ```

**Comment by phaumer** [comment]
Done. Thanks for the feedback.
