### ISSUE TITLE
Error in userbuild with a source file name containing special characters

### ISSUE THREAD

**Issue by friedhelmmuench** [IBM/zopeneditor-about#288]
## Development environment used

- Z Open Editor version: 2.0.3
- Editor Platform
  - [x] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version: 1.65.2
- Operating System (on which VS Code runs such as Windows 10 2004, otherwise name and version of platform such as OpenShift v4.3): Windows 10
- Java Version (when using VS Code or Theia, execute `java -version` and paste the details here): 1.8.0_341
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version: 7.5.1
  - Node.js version: 16.18.0
- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html) how to get them): no

## Problem Description

Hello,
we try to build a source file with $... characters in the filename with the userbuild feature of Z Open Editor.

While analyzing the issue, we tried to start the userbuild directly from the z/OS shell and surrounded the source file name in the command with quotes (' ') to escape special characters in the script parameters. This works as expected.

So our conclusion is, that Z Open Editor has to be changed to surround the source file name in the generated user build command with quotes to avoid handling of special characters in the command args by the shell.

Regards  
Friedhelm 

### Detailed steps for reproducing the problem:

You can reproduce this error by running a userbuild with an arbitrary source file containing a $ in the filename.

### Observed behavior

The build fails with a FileNotFoundException, because the file SS.asm is not found. We found out, that the substring $EMAIL in the generated command is replaced by the shell on z/OS with the content of the (empty) environment-variable EMAIL. 

### Expected behavior

Even source files with special characters in their name can be built.

**Comment by phaumer** [comment]
Fixed in 3.0.1

**Comment by friedhelmmuench** [comment]
> Fixed in 3.0.1
Works perfectly, thank you!
