### ISSUE TITLE
Need timestamps on user build output/log

### ISSUE THREAD

**Issue by ogauneau** [IBM/zopeneditor-about#292]
To troubleshoot performance problems, it will be helpfull to have timestamps on the log output of the user build:

**Comment by ogauneau** [comment]
To better see if the time is spent in Z Open Editor or Zowe Explorer or RSE API calls,...

**Comment by phaumer** [comment]
@ogauneau we now have timestamps in the user build log when the Z Open Editor v3.1.0 log level is set to DEBUG. Same setting for both logs.
