### ISSUE TITLE
Your specified Property Groups with a GLOB pattern returns more than 20 directories to search through

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#293]
## Description of the enhancement requested

Warning messages are issued when searching for COPYBOOKs locally on the number of folders scanned.

We may have many folders because we import Git repositories of resources (dedicated to copybooks) into the VS Code workspace, although we apply a "sparse-checkout" on these repositories to reduce the number of folders, (this choice was made to ensure compatibility with IBM DBB).

The fact that the message is a warning seems to automatically enable display of IBM Z Open Editor output, with the default log level at "INFO".

We would like :
* either to be able to control the number of files that triggers the warning via a ZOE parameter
* either the message is downgraded from warning to DEBUG to no longer trigger the display of the ZOE output

It may also not be necessary to repeat this warning message each time you search for a COPYBOOK.

![image](https://user-images.githubusercontent.com/63861965/204519817-ed50d3bb-cd3d-470c-98ac-8de4a5bfa477.png)

![image](https://user-images.githubusercontent.com/63861965/204520778-6afab972-b528-4a9b-8b75-e5f4b5fc55d5.png)

![image](https://user-images.githubusercontent.com/63861965/204520987-73a44f3e-523c-44bd-9458-a5ed353484c1.png)

![image](https://user-images.githubusercontent.com/63861965/204520128-4e3217d7-5351-4bdf-bc75-9be853ac58bc.png)

![image](https://user-images.githubusercontent.com/63861965/204519262-c8533422-8959-4726-9fa4-8ee47ce08c45.png)

Considering the timestamps on the COPYBOOK searches, to see if the control over the number of scanned folders does not turn out to be more expensive than the search itself.

**Comment by phaumer** [comment]
We are looking for ways to improve this as we observe that just the pure evaluation of the glob patterns (i.e. finding the list of directories to search in) already has a performance impact; especially when user slower storage. Once we optimized the overall behavior we well also reexamine the log messages.

**Comment by FALLAI-Denis** [comment]
Hi,

I think the situation may depend on a lot of contextual conditions and it will be difficult to find a general rule.

The best would be to allow you to set our own limit by means of a setting, to be set either at the user settings level or at the workspace level settings, with a value to deactivate any control (value 0 for example).

The level of the alert (info, warning...) should also be able to be managed by a setting.

**Comment by phaumer** [comment]
Ok, perhaps just having debug level information about the file numbers and time it took without providing an "opinion" is enough for people to troubleshoot.

**Comment by FALLAI-Denis** [comment]
Also be careful not to overload the log, event un DEBUG mode, by writing a message each time a COPYBOOK is accessed.
Our COBOL programs use hundreds of COPYBOOKs (at least potentially referencing, as we use conditional compilation in COPYBOOKs to make context-dependent cascading calls).

**Comment by FALLAI-Denis** [comment]
Hi,

In our solution, searching for a local copybook takes an average of 0.3 seconds, (SSD disk) including writing the warning message in the ZOE log about the number of folders scanned, and without this management, the time would still be less than 0.3 seconds.

**Comment by phaumer** [comment]
We made some big performance improvements in Z Open Editor 3.1.0 and removed this warning altogether.
