### ISSUE TITLE
Invalid Credentials 

### ISSUE THREAD

**Issue by hdauphin23** [IBM/zopeneditor-about#295]
Type: <b>Performance Issue</b>

About 2 weeks ago I have been attepmting to login to my Zexplorer with the credentials that were. provided to me. However, when enter an error message appears indicating that there credentials I have provided are invalid. Hoping to have my credentials reset or find a alterative solution.

Extension version: 3.0.0
VS Code version: Code 1.73.1 (Universal) (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:08:38.961Z)
OS version: Darwin x64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.12GB free)|
|Process Argv|--crash-reporter-id 09d34412-d3cc-4054-9355-502799263e6a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   19	   106	  6360	code main
    6	    33	  6364	   gpu-process
    0	     8	  6365	   utility-network-service
    4	    74	  6371	   shared-process
    0	     8	  6375	     ptyHost
    0	    33	  7211	     fileWatcher
    0	     0	  7242	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   156	  7209	   window (Welcome to Z Open Editor)
    0	   106	  7210	   extensionHost
    0	    33	  7216	     /Users/harolddauphin/Desktop/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Users/harolddauphin/Desktop/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=7210
    0	    66	  7223	   window (undefined)
    3	    74	  7233	   issue-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
282f8724:30602487
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
89544117:30613380

```

</details>

**Comment by phaumer** [comment]
Hello @hdauphin23 I don't think this is the correct repo. This one is for IBM Z Open Editor and not Zowe Explorer. It looks like you need to contact your administrator to work on getting you credentials reset, perhaps? Who provided the credentials? If it was zExplore then they also have their own [support channels](https://community.ibm.com/community/user/ibmz-and-linuxone/groups/group-home?communitykey=27b746cd-ca36-49bb-a1ad-01e7aec7d9aa&tab=group-home).
