### ISSUE TITLE
Display warnings for unused variables and unreachable code.

### ISSUE THREAD

**Issue by B-Teague** [IBM/zopeneditor-about#30]
Any plans to add warnings to the linting rules when an unused variable or unreachable / dead code is found?

**Comment by phaumer** [comment]
@B-Teague we do have that support. See here: https://ibm.github.io/zopeneditor-about/Docs/setting_unreachablecodewarnings.html 

Let us know if that works for you.

**Comment by phaumer** [comment]
Closing this item for now. Please, reopen it if I misunderstood or you have additional requirements.
