### ISSUE TITLE
If COBOL source contains any errors functionality is lost

### ISSUE THREAD

**Issue by dakaa16** [IBM/zopeneditor-about#300]
When an error exist in COBOL source, you are not able to see a preview when hovering over dependencies, and you are not able to inspect variables or go to declaration by using `ctrl+click`.
As we often experience the bug, where copybooks are seen as containing an error (#237), the features are only rarely available to us.
Having errors in the source, should not prevent me from using important features, that does not relate to said error.

Trying to see preview when hovering over copybook:
![Hover](https://user-images.githubusercontent.com/26183764/205875060-c11cf0e8-1b92-4eff-8a79-ada9b5ceb6ba.png)

**Comment by FALLAI-Denis** [comment]
Hi,

See also #253, #203, #199, #154.

**Comment by phaumer** [comment]
For some language server functions as clean parse is required, but not all, e.g. the outline view is still there. For the include files preview it should also be possible to keep that going. We will investigate.

**Comment by phaumer** [comment]
We made some improvements for this case in v3.1.0. It will not work in all error situations, but improves editor behavior and performance for several.
