### ISSUE TITLE
Codepage translation issue

### ISSUE THREAD

**Issue by Marco4691** [IBM/zopeneditor-about#306]
## Development environment used

- Z Open Editor version:
- Editor Platform
  - [x] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version:
- Operating System (on which VS Code runs such as Windows 10 2004, otherwise name and version of platform such as OpenShift v4.3):
- Java Version (when using VS Code or Theia, execute `java -version` and paste the details here):
- [x] Related to RSE API?
  - RSE API Plugin version: 2.2.0
  - Zowe CLI version: 7.6.2
  - Node.js version: 18.12.1
- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html) how to get them): yes/no

## Problem Description
When editing PL/1 source encoded on mainframe in codepage 1148 the '^' symbol (0x5F ebcdic) is incorrectly translated and becomes a '4' in the edit-buffer resulting in parsing issues to the language server.

Detailed steps for reproducing the problem:

1. First step

### Observed behavior

- zapp.yaml file contains RSE-mappings specifying the following:
profiles:
  - name: RSE-Mappings
    type: rseapi
    settings:
      mappings:
        - resource: "**COB*"
          extension: cbl
          transfer: text
          encoding: IBM-1148
          memberMappings:
            - extension: dat
              transfer: binary
              resource: "*DAT"
        - resource: "**.PRG"
          extension: pl1
          transfer: text
          encoding: IBM-1148
        - resource: "**.INCLUDE"
          extension: pl1
          transfer: text
          encoding: IBM-1148
      default.encoding: IBM-1148

### Expected behavior

- the ebcdic character '^' being 0x5F should be correctly translated to its corresponding UTF8 character
- however the character '4' is being displayed in the editor window causing parsing issues.

**Comment by phaumer** [comment]
We will investigate and try to reproduce the issue.

**Comment by Marco4691** [comment]
Any success in reproducing? It is a blocking issue for us to start using the editor in our environment.

**Comment by phaumer** [comment]
Lot of people were out on vacation. Will let you know once someone picked it up.

**Comment by phaumer** [comment]
@Marco4691 I can confirm that this is a bug in RSE API and will be fixed in an upcoming release.

**Comment by phaumer** [comment]
@Marco4691 a fix is available for RSE API 1.0.x: https://ibm.github.io/mainframe-downloads/host-components.html 
If you are 1.1.x we intend to include the fix there as well, soon.

**Comment by phaumer** [comment]
RSE API 1.1.x with the fix is now also available.
