### ISSUE TITLE
COBOL Compile Directives (SKIP1) "ERROR_TOKEN" unexpected tokens ignored parsing

### ISSUE THREAD

**Issue by davidkcoblentz** [IBM/zopeneditor-about#307]
Receive a parsing error on the following COBOL source code when using a SKIP1 statement in the middle of a MOVE statement that continues on a following line. The source compiles with no errors. I would never code this but it exists in a very large system with this type of coding.

## COBOL Source Code
```
01498  INITIALIZE-NUMERIC-FIELDS.                                       SC1WHIDC
01499      SKIP1                                                        SC1WHIDC
01500      MOVE ZEROS TO                                                SC1WHIDC
01501      SKIP1                                                        SC1WHIDC
01502          AUDIT-TRAIL-DATE OF WORK-AREAS                           SC1WHIDC
01503          DET-SUPP-ORD-QTY OF WORK-AREAS                           SC1WHIDC
```

## Source Code Example
![image](https://user-images.githubusercontent.com/80063515/207172905-90e1035a-552b-4473-b267-4f6f712d76bc.png)

![image](https://user-images.githubusercontent.com/80063515/207171323-2efffafd-4191-4d1d-89b9-17e87f43bdb6.png)

## Compile Listing output, no errors
![image](https://user-images.githubusercontent.com/80063515/207174250-3102a253-19ea-48b7-8d2f-fdde9c8b9430.png)

## My System Info
Version: 1.74.0 (user setup)
Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
Date: 2022-12-05T16:38:16.075Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.17763
Sandboxed: No
![image](https://user-images.githubusercontent.com/80063515/207178157-4cf3f60c-7acd-4806-bb9b-ed781afe4dd5.png)

**Comment by FALLAI-Denis** [comment]
Hi,

Same issue for any compiler-directing statement positioned in the middle of a COBOL statement or or inside a COPY directive.

![image](https://user-images.githubusercontent.com/63861965/207804933-d572a1b6-98db-4943-9584-000878830371.png)

Also note that the *CONTROL / *CBL directive is not recognized as such if it is not aligned on column 7, but this directive can appear anywhere from column 7.

**Comment by phaumer** [comment]
@davidkcoblentz fixed in v3.3.3. Can you try?

**Comment by davidkcoblentz** [comment]
I currently have v3.3.2 and checked for updates but it says there are no updates available. Is v3.3.3 released to the public yet?

***@***.***

**Comment by davidkcoblentz** [comment]
Works great!!  Thanks for the fix!

***@***.***
