### ISSUE TITLE
exec format error on Che Deployment on OCP

### ISSUE THREAD

**Issue by dan-jast** [IBM/zopeneditor-about#32]
We are trying to install Che in our OCP cluster(4.2.18) running on z/VM Guests. When we run the `./deploy.sh $namespace` command, We are seeing a nightly build 
```
Pulling image “quay.io/eclipse/che-operator:nightly”
``` 
being pulled. This fails to start Che properly, which returns the error message below in the logs: 
```
standard_init_linux.go:211: exec user process caused "exec format error"
```

**Comment by phaumer** [comment]
Our blog post currently only covers deploying on Intel-based clusters. We will look at deploying to Z clusters at a later point.
