### ISSUE TITLE
COBOL Property Groups defined: None

### ISSUE THREAD

**Issue by paulobigas** [IBM/zopeneditor-about#320]
Hello,
I trying to define a propriety group for the copybook's members in my VSCode /IBM ZOpenEditor, in a z/osmf connection to my mvs files. But no matter what i try it seems he don't detect any propriety group created (  - COBOL Property Groups defined: None). I have the YAML extension installed and the zapp.yaml file in the \.vscode directory. Even the local files aren't detected. 

What am I doing wrong?

Thanks in advance,

- Z Open Editor version: 3.0.1
- Editor platform: Visual Studio Code
- Editor platform version: 1.75.1
- Required minimal editor platform version: ^1.53.2
- Editor installation root directory: c:\Users\paulo.a.bigas\AppData\Local\Programs\Microsoft VS Code\resources\app
- Editor workspaces: No workspaces open.
- Is a valid Java configured: true
  - Java: C:\Program Files\Eclipse Adoptium\jdk-11.0.16.101-hotspot\bin\java.exe
  - Java memory allocation: 512
  - Java startup user settings: Not defined.
- Key user settings:
  - Unreachable Code enabled: true
  - HLASM version used: 2.5
  - HLASM macros file used: c:\Users\paulo.a.bigas\.vscode\extensions\ibm.zopeneditor-3.0.1\resources\hlasm-macros-v2r5.json
  - HLASM instructions file used: c:\Users\paulo.a.bigas\.vscode\extensions\ibm.zopeneditor-3.0.1\resources\hlasm-instructions.json
  - HLASM Macro resolution enabled: false
  - Enforce Case Sensitive Include File Names: false
  - ZAPP schema used: file:///c%3A/Users/paulo.a.bigas/.vscode/extensions/ibm.zopeneditor-3.0.1/resources/zapp-schema-1.0.0.json
  - IBM User Build enabled: true
  - Zowe CLI API profile management used: v1 profiles in use.
  - Zowe CLI Secure Credentials enabled: true
  - Zowe CLI profiles of types rse, zosmf or ssh found: MG(zosmf)
  - Zowe CLI files profile name specified in VS Code user settings: MG
  - Zowe CLI SSH profile name specified in VS Code user settings: Not defined.
  - Zowe CLI files profile used for remote include files: MG
  - Zowe CLI SSH profile used: No profile found.
  - Zowe CLI profiles configured for user build: MG (zosmf), No SSH profile found
  - Zowe Explorer RSE API Mappings File setting: Not defined.
  - Zowe Temp-Dir value: Not defined.
  - COBOL Property Groups defined: None.
  - COBOL include file extensions: .cpy,.copybook,.copy,.cobcopy,.source
  - PL/I Property Groups defined: None.
  - PL/I include file extensions: .inc,.include,.plinc,.pcx,.pci
  - HLASM Property Groups defined: None.
  - HLASM include file extensions: .s,.assemble,.asm,.hlasm,.hla,.copyasm,.macasm,.bms
  - VS Code Files Assocications: *.COBOL*:cobol,*.COB*:cobol,*.COBCOPY*:cobol,*.COPYBOOK*:cobol,*.COPY*:cobol,*.PL1*:pl1,*.PLI*:pl1,*.INC*:pl1,*.INCLUDE*:pl1,*.JCL*:jcl,*.ASM*:hlasm,*.ASSEMBLE*:hlasm,*.HLASM*:hlasm,*.HLA*:hlasm,*.MACLIB*:hlasm,*.EXEC*:rexx,*.REXX*:rexx,*.REXXINC*:rexx,*.source:cobol,*.copyasm:hlasm,*.macasm:hlasm,*.bms:hlasm,*.rex:rexx,*.rexx:rexx,*.SOURCE(AMI38020):cobol
- Zowe Explorer VS Code Extension version: 2.6.1
  - Successfully activated: true
  - Installation path: c:\Users\paulo.a.bigas\.vscode\extensions\zowe.vscode-extension-for-zowe-2.6.1
  - Log file location: c:\Users\paulo.a.bigas\.vscode\extensions\zowe.vscode-extension-for-zowe-2.6.1\logs
  

->DEBUG
2023-02-20T13:19:49.898Z DEBUG: ZLanguagesResourceResolver.documentRequested: The COBOL language server requested the following include file: "GMCD0400". The ID for this request was assigned as "wq2vw" There are 1 pending requests being processed.
2023-02-20T13:19:49.899Z WARN : You opened a file with include files, but do not have a Property Group defined that specifies where to find them. Review the documentation and your settings or Zapp files.
2023-02-20T13:19:49.902Z WARN : The COBOL language server requested the include file "GMCD0400", which was not found. enforceCaseSensitiveIncludeFileNames was set to false. Check your Zowe CLI profile and property group settings and if you have not already done so, switch to the "DEBUG" log level for more information.
2023-02-20T13:19:49.903Z DEBUG: ZLanguagesResourceResolver.buildResponse(RequestId:wq2vw): File "GMCD0400" was not found.
2023-02-20T13:19:49.904Z DEBUG: ZLanguagesResourceResolver.buildResponse(RequestId:wq2vw): Finished request wq2vw. 0 pending requests left to process.
2023-02-20T13:19:49.906Z DEBUG: ZLanguagesResourceResolver.documentRequested: The COBOL language server requested the following include file: "AMCV3800". The ID for this request was assigned as "iw9e4b" There are 1 pending requests being processed.

->ZAPP File
################################################################

name: test
description: For IBM Z Open Editor 3.0.0 or newer. Wazi's code samples with COBOL, PL/I, and HLASM applications
version: 3.0.0
author:
  name: IBM CORPORATION

propertyGroups:
  - name: cobol-copybooks
    language: cobol
    libraries:
      - name: syslib
        type: local
        locations:
          - "**/COPYBOOK"
      - name: syslib
        type: mvs
        locations:
          - "DESV.LIB.COPY"
      - name: MYLIB
        type: mvs
        locations:
          - X93295.LIB.COPY
      - name: MYLIB
        type: local
        locations:
          - "**/COPYLIB-MVS"
      - name: MYFILE
        type: local
        locations:
          - "**/COPYLIB"

**Comment by sdaimwood** [comment]
Hi there, based on the log and description of your environment it sounds like there may be a couple issues if I'm understanding your setup correctly:

1. In your zapp.yaml, you have a duplicate entry at the top. There are two `name` entries, one with a value of `test` and one with the value `IBM CORPORATION` you'll need to remove one of those for the yaml file to be parsed correctly, it shouldn't matter which one you remove. 
2. Your zapp.yaml may not be in the correct location. You mentioned that it is located in your `.vscode` directory, it actually needs to be placed in the top level directory of your workspace. So for example:

Incorrect:
```
workspace
└───.vscode
    │   settings.json
    │   zapp.yaml
└───COBOL
│   └───COPYBOOK
│   │   │   COPY.cpy
│   │   │   ...
│   │
│   └───SAM
│       │   ...
```

Correct: 
```
workspace
└───.vscode
    │   settings.json
└───COBOL
│   └───COPYBOOK
│   │   │   COPY.cpy
│   │   │   ...
│   │
│   └───SAM
│       │   SAM1.cbl
│       │   ...
└───.zapp.yaml
```

So it should be at the same level as the .vscode folder. Let us know if these changes help get copybooks resolved. The biggest thing to look for in your log would be to see that instead of the message that says:

```
 WARN : You opened a file with include files, but do not have a Property Group defined that specifies where to find them. Review the documentation and your settings or Zapp files.
```

You'll instead receive one that says:

```
DEBUG: ZAPP: A valid ZAPP file was found in "your-dir-here" and will be used instead of user settings.
```

**Comment by paulobigas** [comment]
That was it! I just moved the my zapp.yaml to my workspace directory and it worked. Thank you very much!
