### ISSUE TITLE
COBOL - Error while processing boolean compilation variables

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#321]
## Development environment used

- Z Open Editor version: 3.0.1
- Editor Platform
  - [X] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version: 1.75.1
- Operating System: Windows 10 22H2
- Java Version: V11
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached: no

## Problem Description

The COBOL Language Server does not correctly handle condition expressions on compilation variables in boolean format compared with the constant b'0' or b'1', which subsequently triggers parse errors at the global level and emitting false syntax errors.

![image](https://user-images.githubusercontent.com/63861965/220286726-29859c18-06ab-458a-a054-061210ce4ba0.png)

Problems also on parsing the >>evaluate directive:

![image](https://user-images.githubusercontent.com/63861965/220289708-fbd3a075-1d2c-4dc7-83e8-acadcf21aa55.png)

![image](https://user-images.githubusercontent.com/63861965/220290460-70564a6a-f436-40df-a376-f02b79228556.png)

**Comment by FALLAI-Denis** [comment]
Hi,

I haven't tested it but I think that if the management of conditional compilation does not work at the Language Server level, and this leads to poor or false detection of the COPYBOOKs actually used by the program during compilation, this must have a impact on the IBM User Build function (call to DBB-zAppbuild): copybooks will be missing (transfer from local to remote system) when compiling User Build.

In general, the poor management of conditional compilation by the COBOL Language Server causes us many problems and makes most of the features specific to Z Open Editor unusable (any syntax error disables many features in ZOE).

Perhaps you should consider no longer managing conditional compilations and considering that all the source lines are part of the program (management by excess, but at least the "necessary" is managed, in the absence of the "sufficient"), or provide an option to allow disabling conditional compilation support in the COBOL Language Server.

In any case, we want substantive and rapid action on the problems related to the management of conditional compilation in the COBOL Language Server because we have now switched to intensive use mode of Z Open Editor and these problems are becoming critical for us.

**Comment by FALLAI-Denis** [comment]
See [https://github.com/IBM/zopeneditor-about/issues/154](https://github.com/IBM/zopeneditor-about/issues/154)

**Comment by phaumer** [comment]
Fixed in Z Open Editor 3.1.0
