### ISSUE TITLE
Question: Can zapp files be used when browsing remote pds using zowe.

### ISSUE THREAD

**Issue by nk2164** [IBM/zopeneditor-about#324]
I am wondering if it is possible to use the zapp file when opening a pds with zowe plugin ? I am able to access PLI modules in my local directory and resolve local and remote copybooks ...but wanted to do something similar when directly opening the module in remote PDS...is it possible ? Thanks  a lot.

**Comment by phaumer** [comment]
@nk2164 I moved your issue to this repository that we use to collect feedback items.

About your question: yes, see the attached screen shot. I opened the program PSAM1 from a PDS and it resolved the CUSTPLI file from another PDS and the BALSTATS file from a local source, as it was not available in the PDS. You see how it is specified in the ZAPP file on the right. The ordering of these nested lists determine the search order.

<img width="1676" alt="2023-02-27_14-45-57" src="https://user-images.githubusercontent.com/4391934/221704396-47b74b31-8b78-414c-9c45-192b46a6947b.png">

Also see [these docs pages](https://ibm.github.io/zopeneditor-about/Docs/setting_propertygroup.html) for more details.

**Comment by nk2164** [comment]
@phaumer Thanks a lot. Yeah, I had missed adding the defaultCliProfile in my settings at the time I opened the issue, so it was not pointing to my zosmf profile. I did add it later in the evening .....just opened my pds again and it did resolve all the copybooks.

**Comment by phaumer** [comment]
@nk2164 glad to hear that it works now. 

Note, the defaultCliProfile Z Open Editor setting is not needed. It will always pick the profile listed as default in the Zowe team config file. If you list RSE and z/OSMF profiles it will always pick RSE. The defaultCliProfile setting can be used to override the Zowe defaults, though.
