### ISSUE TITLE
{env:USERNAME} in zapp.yaml?

### ISSUE THREAD

**Issue by COBOL-Erik** [IBM/zopeneditor-about#325]
I would like all mainframe developers to be able to share a zapp.yaml, with no need for changes by individual developers. But we have personal datasets for copy books, that follow naming conventions. Could it be possible to specify variables in the zapp.yaml file? For example something like {env:USERNAME} (used in other settings in VS Code)?

**Comment by phaumer** [comment]
@COBOL-Erik thanks for this item. We agree that this would be important to add. 
I moved the item to this repository in which we collect the Z Open Editor issues.

**Comment by FALLAI-Denis** [comment]
Hi,

Especially since the zapp file resides in principle in the VS Code Workspace so in the Git repository and is therefore shared by all users who work with this Git repository.

**Comment by COBOL-Erik** [comment]
Exactly!
Thanks!

**Comment by COBOL-Erik** [comment]
This is implemented now. Thanks!

**Comment by phaumer** [comment]
Ok, thanks. We do not do environment variables, but you define variables as settings. Great to hear that this works for you.

**Comment by COBOL-Erik** [comment]
That’s what I meant. We add the variable with a script 😊
