### ISSUE TITLE
zowe.settings.version Falscher Typ. „integer“ erwartet.

### ISSUE THREAD

**Issue by SG-A47** [IBM/zopeneditor-about#326]
In der sessions.json wird zowe.settings.version beim Start auf "2.6.1" migriert.
Das führt zu der obigen Fehlermeldung. Wenn man den Textstring durch ein Integer ersetzt, ist der Fehler weg.
Beim nächsten Start von  VS Code ist er wieder da. Wie kann man das abstellen?

**Comment by phaumer** [comment]
Thanks. This is an issue caused by Zowe Explorer. I filed it for you here: <https://github.com/zowe/vscode-extension-for-zowe/issues/2166>.
