### ISSUE TITLE
COBOL - "SectionName" expected instead of this input

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#329]
## Development environment used

- Z Open Editor version: 3.1.0
- Editor Platform
  - [X] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version: 1.74.3
- Operating System: Windows 10
- Java Version: V8
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached: no

## Problem Description

Hi,

Version 3.1.0 of Z Open Editor has greatly improved the operation of the COBOL Language Server, and we thank you very much for that.

However, there are still anomalies which for us affect the entire source code.

In the example below, the COBOL Language Server appears to be expecting a COBOL Section name at a comment.

Is this due to the comment itself? The presence of characters that are not recognized by the COBOL language even though they are used in comments?

Is it due to the presence of conditional compilation directives that precedes in the source code through the call to a copybook?

### Observed behavior

![image](https://user-images.githubusercontent.com/63861965/224377848-79701e96-cc28-452f-b0d9-bad7bba2a92e.png)

![image](https://user-images.githubusercontent.com/63861965/224381492-0785ee81-2dc6-4c91-b403-cd79cbb536bf.png)
On the right margin, we see that almost all the source code is declared in error by the COBOL Language Server.

![image](https://user-images.githubusercontent.com/63861965/224379142-7b4c1db2-1462-4e15-b74e-cec7d748c4a7.png)

Removing the comments only moves the appearance of the problem a bit further into the source code:
![image](https://user-images.githubusercontent.com/63861965/224379845-7160e1e3-b726-4f4c-b857-488de5cd0f87.png)

Called copybooks:
![image](https://user-images.githubusercontent.com/63861965/224380177-696a0925-5032-4158-82f4-ffbfe45d065f.png)

![image](https://user-images.githubusercontent.com/63861965/224380295-b3196366-8f71-4a15-9a98-e606ef44654e.png)

**Comment by phaumer** [comment]
@FALLAI-Denis I OCRed your samples, but cannot reproduce the problem. I do see the DataDescriptionEntryList issues in the two copybooks, but not the error in the program you see. Could you complete the attached sample to reproduce the issue?

[sample-code.zip](https://github.com/IBM/zopeneditor-about/files/10946590/sample-code.zip)

**Comment by FALLAI-Denis** [comment]
Hi @phaumer 

Thank you again for your efforts to resolve our issues.
These revolve around the handling of conditional compilation by the COBOL Language Server.

I proceeded by successive addition of code in the test program until obtaining a first anomaly.
I have not yet succeeded in reproducing the same case, but I have already caused a problem which could then trigger others in cascade.

See new sample code here:
[sample-code-v2.zip](https://github.com/IBM/zopeneditor-about/files/10948342/sample-code-v2.zip)

![image](https://user-images.githubusercontent.com/63861965/224481299-f08ab912-c5d5-4d89-bd90-3694ad4021b5.png)

![image](https://user-images.githubusercontent.com/63861965/224481335-658ab781-f4a0-4fab-b039-d64c2936e199.png)

![image](https://user-images.githubusercontent.com/63861965/224481404-20372449-778b-4f9e-8fc6-da407999b804.png)

![image](https://user-images.githubusercontent.com/63861965/224481434-2bf61079-5cfc-4f63-ba9e-d1b5cb5ee971.png)

**Comment by PrasangAPrajapati** [comment]
Hi @FALLAI-Denis,

Thank you for the contributions here, we have analyzed the problem using the sample code that you have provided with v2. The issue is on line 79 in file `AAADACCE.cpy` with the declaration using REPLACING statement. 

```
01               5-:DD:00-CPTENR PIC  S9(9) BINARY VALUE 0.      
```

If you comment that line, the errors should go away from that COPYBOOK file. 

A similar issue is already been filed previously. [Issue 186](https://github.com/IBM/zopeneditor-about/issues/186)

**Comment by PrasangAPrajapati** [comment]
Closing this issue as duplicate of [186](https://github.com/IBM/zopeneditor-about/issues/186)

**Comment by FALLAI-Denis** [comment]
Hi @PrasangAPrajapati 

Thanks for your research but I don't understand why you closed this issue.

The code compiles perfectly fine, without any warnings.

The text used seems to me completely legal and complies with the specifications of the IBM Enterprise COBOL compiler:

`01               5-:DD:00-CPTENR PIC  S9(9) BINARY VALUE 0.`

![image](https://user-images.githubusercontent.com/63861965/227341014-f7db99ac-1a91-44d5-b0d9-64e3f3e7c020.png)

![image](https://user-images.githubusercontent.com/63861965/227342276-0c320ce3-e91e-40fc-8a04-6ae1748aa4a1.png)

If the line pointed to as the error is moved elsewhere in the AAADACCE copybook, it is no longer in error...

![image](https://user-images.githubusercontent.com/63861965/227344659-a775686e-3ae7-40ee-91b6-3d77b11d34f0.png)

![image](https://user-images.githubusercontent.com/63861965/227344527-39e2e9a4-816a-4fd3-8726-abf98be8f835.png)

For me, the problem is indeed related to the management of the variables of conditional compilation and to the calculation of their changes of values which intervenes in the program or in the called copybooks.

I request that this issue be reopened.

**Comment by PrasangAPrajapati** [comment]
@FALLAI-Denis Thanks again for providing feedback. I've tried it again and after looking into it in detail, looks like an issue with conditional compilation and handling of its variables. I am reopening this issue and will look further into it.

**Comment by phaumer** [comment]
@FALLAI-Denis we made some more improvements in v3.3.2 for this issue. Can you verify?

**Comment by FALLAI-Denis** [comment]
Hi,

Thanks for these improvements.

The problem has disappeared.
But other issues that were hidden have appeared: I'm opening another request for these new issues.
