### ISSUE TITLE
Open source support request - variable for temp copybook path 

### ISSUE THREAD

**Issue by bearou** [IBM/zopeneditor-about#33]
As z Open Editor receives COBOL copybooks in certain temp folders named after the corresponding dataset name on the zOS, we would like to access these folders in a smart (ie. not hard coded) manner.

Is "a variable" or something similar available to the developer so we can use these copybooks in ie. a compile situation ? 

Best regards Claus

**Comment by phaumer** [comment]
When you use Zowe Explorer to open a file the temp dir for storing these files can be set with 

```json
"Zowe-Temp-Folder-Location": {
        "folderPath": "/home/ibmuser/zowe-temp"
    },
```

in your VS Code user settings. Is that what you are looking for?

If this is for the resolved copybooks that the editor shows in the hover, then yes, we use the same setting for that. It is just that the naming schema for the Zowe Explorer files is different that of our LSP. We have plans to resit that and unify these to avoid download each file twice.

**Comment by phaumer** [comment]
Closing. Please, reopen if this did not solve the issue for you.

**Comment by bearou** [comment]
Thank you @phaumer - sorry for late reply. This might work; will revert if not 👍
