### ISSUE TITLE
Pointing to wrong version in plugin file

### ISSUE THREAD

**Issue by kunwarmahen** [IBM/zopeneditor-about#34]
In zopeneditor-about/che/plugins/zowe.yaml, it is refering to wrong version of plugin  https://github.com/IBM/zopeneditor-about/releases/download/0.4.3/Zowe.vscode-extension-for-zowe-1.0.1.vsix

**Comment by phaumer** [comment]
We have PR https://github.com/IBM/zopeneditor-about/pull/29/files that we merge soon.

**Comment by phaumer** [comment]
fixed
