### ISSUE TITLE
COPY in column 7 is OK for zOpenEditor

### ISSUE THREAD

**Issue by ROBIN-Olivier** [IBM/zopeneditor-about#340]
- Z Open Editor version: 3.1.1
- Editor Platform
  - [x] Visual Studio Code 1.72.2
- Operating System: Windows 10 Entreprise
- Java Version: 11

When I code a copy in column 1 to 6 of my cobol program, an anomaly message is displayed.
But when I code it in column 7, no anomaly is detected by zopeneditor :
![image](https://user-images.githubusercontent.com/103997342/235922309-0c34b479-2897-40a4-9191-7b290d427931.png)

However, the compilation crashes because the COPY is badly positioned.

**Comment by phaumer** [comment]
Fixed in Z Open Editor v3.2.0
