### ISSUE TITLE
After Update to 3.2.0 the Buttons / Menu Entrys for Prepare and Run user Build are gone 

### ISSUE THREAD

**Issue by richydwp** [IBM/zopeneditor-about#349]
Z Open Editor version: 3.2.0
Editor Platform
[ x] Visual Studio Code
[ x] Red Hat CodeReady Workspaces
 Eclipse Che
 Standalone Theia
Editor Platform Version:
Operating System (on which VS Code runs such as Windows 10 2004, otherwise name and version of platform such as OpenShift v4.3): Windows 10
Java Version (when using VS Code or Theia, execute java -version and paste the details here): Java 11
 Related to RSE API?
RSE API Plugin version:
Zowe CLI version: 2.4.1
Node.js version:
Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html) how to get them): yes
## Problem Description

Detailed steps for reproducing the problem:

1. First step

Upgrade from zOpen Editor 3.1.1 to 3.2.0 and the 3 Entrys (run and prepare User build) in the menu which appears on right click in a Cobol programm are gone. 

Go back to 3.1.1 and tehy come back again. 

I have no idea whats is wrong

**Comment by richydwp** [comment]
After Update vscode  to 1.78.1 buttons are back again.

**Comment by phaumer** [comment]
We see that this impacts VS Code version below 1.76 and lower. Therefore, the workaround for now is to upgrade to a newer version of VS Code, if that is possible, or use Z Open Editor 3.1.1 until we have published fix.

**Comment by phaumer** [comment]
Fixed with v3.2.1
