### ISSUE TITLE
Enhance language recognition with directories

### ISSUE THREAD

**Issue by zszabo14** [IBM/zopeneditor-about#35]
Hi

The editor recognises file type by its extension. But, in our case we don't have extension on source files. Please add a new configuration setting where directories can be also added to files.associations, so we can set a type for all files in a folder.
eg:

folders.associations": {
        "*\JLC": "jcl",
        "*\COBOL": "cobol",

So, files in any directory named COBOL will be treated as COBOL.

**Comment by phaumer** [comment]
Thanks for the feedback @zszabo14. This is already possible with files.associations and GLOB patterns such as 

```json
"files.associations": {
   "**/COBOL/*": "cobol"
}
```

See here for the doc: https://code.visualstudio.com/docs/languages/overview#_can-i-map-additional-file-extensions-to-a-language

Please, reopen if I misunderstood your request.

**Comment by zszabo14** [comment]
HI, I tested it and experienced a strange behavior. I edited the setting.json added:  "**/JCL/*" : "jcl". It worked well. Then I restarted VS Code, clicked on a JCL file. The syntax was blinked for a short moment and then disappeared. I checked the settings.json and my added line was gone. 
[settings.json - WWFD - Visual Studio Code 2020-03-25 09-07-53.zip](https://github.com/IBM/zopeneditor-about/files/4379734/settings.json.-.WWFD.-.Visual.Studio.Code.2020-03-25.09-07-53.zip)

**Comment by phaumer** [comment]
@zszabo14 the issue of the disappearing file.associations was fixed in v0.4.7. Can you confirm that you are you on that version? I cannot reproduce it, but this was an issue in earlier versions.

**Comment by zszabo14** [comment]
Hi, 

Now I'm on 0.4.7, but I'm not sure which version was on when I saw the issue. I will check with this version soon,

**Comment by zszabo14** [comment]
It works in 0.4.7

but the syntax coloring looks strange
![image](https://user-images.githubusercontent.com/42870072/78919529-50f0e580-7a92-11ea-8ff5-cf7d0cf54f71.png)

**Comment by phaumer** [comment]
Mmh, this indicates that the file was mapped to a different language. What do you see on the right of the status bar at the bottom? What language does it show?

**Comment by zszabo14** [comment]
JCL
