### ISSUE TITLE
bitlang.cobol extension used by Z Open Editor conflicts with that used by vscode-ibmi

### ISSUE THREAD

**Issue by jwoehr** [IBM/zopeneditor-about#352]
The bitlang.cobol extension used by Z Open Editor conflicts with that used by [vscode-ibmi](https://github.com/halcyon-tech/vscode-ibmi)

COBOL reports in VSCode "Problems":
```
VSCode version                              : 1.80.1
 Platform                                   : linux
 Architecture                               : x64
Extension Information:
 Extension path                             : /home/jwoehr/.vscode/extensions/bitlang.cobol-9.7.15
 Version                                    : 9.7.15
 UNC paths disabled                         : false
 Parse copybook for references              : false
 Editor maxTokenizationLineLength           : 20000
 Semantic token provider enabled            : false
 editor.semanticHighlighting.enabled        : configuredByTheme
 [COBOL]editor.semanticHighlighting.enabled : true
 workbench color theme                      : Visual Studio Light - C++
 Is Workspace Trusted                       : true

The extension zopeneditor from IBM has conflicting functionality
 Solution      : Disable or uninstall this extension, eg: use command:
                 code --uninstall-extension IBM.zopeneditor
 Reasons       : contributes conflicting grammar
               : contributes language id
 Id            : IBM.zopeneditor
 Description   : Provides COBOL, PL/I, HLASM, and REXX language servers, as well as tools for IBM Z development.
 Version       : 3.2.0
 Repository    : https://github.com/IBM/zopeneditor-about
 Bug Reporting : https://github.com/IBM/zopeneditor-about/issues
```
## Development environment used

- Z Open Editor version: 3.2.0
- Editor Platform
  - [x] Visual Studio Code
```
Version: 1.80.1
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-12T17:22:25.257Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.2.6-76060206-generic
```
- Java Version (when using VS Code or Theia, execute `java -version` and paste the details here): openjdk 11.0.19 2023-04-18
- Zowe CLI version: 7.16.6
- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html) how to get them): no

## Problem Description

Detailed steps for reproducing the problem:

Load Z Open Editor and IBM Code for i in same VSCode Installation

### Observed behavior

![image](https://github.com/IBM/zopeneditor-about/assets/4604036/1ee43066-050a-4538-8a97-f31180866747)

### Expected behavior

These 2 IBM flagship open source projects for enterprise systems co-ordinate on 3rd-party extension strategy.

### FYI
See [this issue for Code for i](https://github.com/halcyon-tech/vscode-ibmi/issues/1442)

**Comment by FALLAI-Denis** [comment]
Hi @jwoehr 

Have you considered using VS Code profiles to isolate each of the extensions in a different usage context?

[Profiles in Visual Studio Code](https://code.visualstudio.com/docs/editor/profiles).

IBM Z Open Editor is intended to manage programming languages running on an IBM z/OS system.
IBMI is intended to manage programming languages running on an IBM i system.
There is no objective reason to want to use these two extensions in the same context.

**Comment by jwoehr** [comment]
Thanks, that is probably the best solution.

**Comment by phaumer** [comment]
Great suggestion @FALLAI-Denis. Thanks.
