### ISSUE TITLE
COBOL program wrapped in JCL

### ISSUE THREAD

**Issue by LukasJaks** [IBM/zopeneditor-about#354]
## Development environment used

- Z Open Editor version: v3.1.1
- Editor Platform
  - [x] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version: 1.76.1
- Operating System (on which VS Code runs such as Windows 10 2004, otherwise name and version of platform such as OpenShift v4.3): Windows 10 21H2
- Java Version (when using VS Code or Theia, execute `java -version` and paste the details here):
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version: 7.12.0
  - Node.js version: v18.14.2
- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html) how to get them): no

## Problem Description

Detailed steps for reproducing the problem:

1. First step wrap cobol source program in JCL compile procedure
2. manually select cobol as language

### Observed behavior

- In my company, we have cobol programs wrapped in JCL procedure, which creates problem when you select cobol as source in VS code with IBM Z Open Editor. If you manually select cobol as source and its wrapped in JCL, it tries to see the JCL code as cobol and underlines all of it in red (obviously, but thats not the issue, we dont really care about that). After that everything seems ok until few tens of lines down, then it starts to red underline most of the code. Saying either "Misplaced constructor parsing" or "ERROR_TOKEN unexpected tokens ignored parsing". Everything seems to be colored properly tho. As for logs, theres no difference between having jcl included or not.

### Expected behavior

- not have red lines everywhere

**Comment by FALLAI-Denis** [comment]
HI @LukasJaks,

I understand that your request concerns the support of several language modes in the same document.

VS Code allows this, but I think your request is too specific to your context and you will have to implement your own solution: you want to manage documents that use both the JCL language mode and the COBOL language mode, but the number of combinations of language mode is infinite, and the rules for switching from one language mode to another language mode can also be context-specific.

I invite you to read an article on Medium and the VS Code documentation:
* Medium: [Multi-Language Support in VSCode Text Documents](https://betterprogramming.pub/multi-language-support-in-vscode-text-documents-3d4f9cbeab1d)
* VS Code reference documentation:  [Syntax Highlight Guide](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#embedded-languages) , [Embedded Programming Languages](https://code.visualstudio.com/api/language-extensions/embedded-languages)
* VS Code sample extension: [LSP Example for Embedded Language using Language Service](https://github.com/microsoft/vscode-extension-samples/tree/main/lsp-embedded-language-service)

There are two mechanisms that are implemented for processing a language mode:
* syntax highlighting: it is based on textmate files describing the syntax of a language.
* grammar recognition: it is based on a language server.

To achieve your goal, you would have to develop a proprietary extension associated with a new "JCL + COBOL" language mode. 
This extension should:
* define a syntax combining the syntaxes (textmate)  of the JCL and COBOL language modes, and define the patterns that allow switching from one mode to another, (and these patterns may be specific to your context).
* create a language server filtering JCL regions and COBOL regions and addressing the COBOL language server when needed, (ZOE does not implement a language server for JCL).

In your case, it may not be necessary to implement the COBOL language server, the combination of JCL and COBOL syntax highlighting may be sufficient for your needs.

Regarding the appearance of red squiggle lines, to avoid them, the COBOL language server should be disabled to keep only the COBOL syntax highlighting.
Another solution is to make them less intrusive, see: 
* #337

**Comment by sdaimwood** [comment]
Hi @LukasJaks, while we support embedded CICS and SQL through the `EXEC` statement in COBOL, as @FALLAI-Denis mentioned, we do not support JCL wrapping in Z Open Editor or the JCL language with a language server. We do have a standalone JCL textmate, so JCL files should have syntax highlighting when opened, but no language functionality.

While not ideal, if you want to get rid of all red errors there is a setting to disable all reported problems in a program. To enable that, go to VS Code settings, the setting falls under Z Open Editor -> Cobol -> Disable problems. If you'd like to search for it, the setting ID is `zopeneditor.cobol.disableProblems`. The drawback of this is that real errors won't be reported, although I'm not sure in your case if any "real" errors were being reported anyway as the document almost certainly wasn't able to be parsed correctly with the JCL present.

**Comment by LukasJaks** [comment]
Hello,

@FALLAI-Denis thank you, for us, it will probably be solved by disabling the COBOL language server. As we dont need to have the JCL syntax highlighted. or if someone will complain, we will use @sdaimwood. 

I guess we can now close this issue as resolved, even though, I still wonder why it's not being parsed correctly, one would think that just the JCL part would be in red lines, and the rest would be fine.

Thank you for your help though!

**Comment by phaumer** [comment]
@LukasJaks thanks for submitting this. We keep it in our radar, but I had not heard about this practice before. Our cobol language mode right now is strict as the language is very sensitive about every character and column a character is placed etc.
