### ISSUE TITLE
Z/Open Editor hasn’t seemingly taken account of the Keytar removal from VSCode

### ISSUE THREAD

**Issue by davidkjackson54** [IBM/zopeneditor-about#359]
It appears that z/Open Editor has not catered for the documented removal of keytar from VSCode that was released over the past few days.  

![IMG_1167](https://github.com/IBM/zopeneditor-about/assets/46171060/4a365155-9faf-4cd4-a918-3f0eec3d9160)

**Comment by ibmrcruicks** [comment]
This "error" - flagged with a warning triangle - does not appear to indicate any actual problem with the editors. As long as ZOWE version and VSCode versions are compatible, the editor opens just fine on MVS and USS datasets and files.
What *does* produce an error is trying to find and set the "Zowe Security:Credential Key" as this is no longer provided by the ZOWE extension

**Comment by davidkjackson54** [comment]
This problem started to occur yesterday after the update of VSCode v1.83.0 . Nothing else changed.  The problem occurs immediately on VSCode startup.

**Comment by ibmrcruicks** [comment]
V1.83 removed the keytar shim - the Db2 Developer Extension is now properly broken; z Open Editor's error suggests it is broken but probably isn't.
The error definitely needs fixed/removed to avoid confusion.

**Comment by phaumer** [comment]
We have replaced keytar with a new library in Zowe Explorer already for a while now. This error in Z Open Editor pops up because of a test we had forgotten to remove in time. For now you can ignore the warning as the functionality is not impacted. Our next release will have the warning removed.

**Comment by ibmrcruicks** [comment]
@phaumer - when is that release due?  We have many "new to Z" users who are currently encountering this error as their first experience with open source access to IBM Z.

**Comment by phaumer** [comment]
@ibmrcruicks I understand, but we cannot talk about release dates outside of the official IBM announcements.

**Comment by phaumer** [comment]
@ibmrcruicks @davidkjackson54 we just published an emergency fix with version 3.2.3 that gets rid of the dialog.

**Comment by ibmrcruicks** [comment]
thanks for the speedy turnaround!

**Comment by davidkjackson54** [comment]
Thank you.
