### ISSUE TITLE
No copybooks being received after upgrade to zOS 2.4

### ISSUE THREAD

**Issue by bearou** [IBM/zopeneditor-about#36]
Zowe connection to the mainframe works, and the Z Open editor extension is still coloring COBOL programs, but no external refereces are resolved since no copybooks are being received. 
I regrettably can not find ANY material to support this issue; no entries in any logs locally or on zOS. No abends or RACF rejections. 
So, the first part towards a solution would be to pin point where to look for evidence.
Brgds Claus

**Comment by phaumer** [comment]
@bearou does Zowe Explorer and/or Zowe CLI work? Are you opening the program via Zowe Explorer or is it a local file?

**Comment by bearou** [comment]
Zowe Explorer and Zowe CLI both work. I am opening COBOL source via the Zowe Explorer.

**Comment by bearou** [comment]
I have been looking for logs, documentation etc. that could help the situation; 
looking in log files in uss under /..../var/zosmf/data/logs/ does not seem to reveal anything. SYSLOG and IZUSVR1 neither. 
This worked Friday, then we did a zOS upgrade during the weekend, and now no receive jobs are being submitted.

**Comment by phaumer** [comment]
I did try it with z/OSMF 2.4 and 2.3 now myself and could not see any differences in behavior. I assume there is nothing in the Output tab under Log (Window)? We have a story for adding detailed logging to the copybook resolving; also to help with Property Group configurations. I will make that a priority.

We are also a few hours away from releasing support for RSE (Remote System Explorer) API support that can be used instead of z/OSMF. RSE ships with z/OS Explorer and IDz. If you have that already configured in your org then it will be a simple upgrade.

**Comment by phaumer** [comment]
We just published a new version of IBM Z Open Editor, v0.4.7.  This version does not only add [RSE beta support](https://ibm.github.io/zopeneditor-about/Docs/rse_interactwithzos.html), but also uses a newer version of Zowe CLI (2.36 -> 6.8.2) to perform the z/OSMF calls for copybook resolving. Could you try with this version? Perhaps it makes a difference.

**Comment by bearou** [comment]
Still major issues with upgrade. Seems like JVM problems. Our service provider has opened a ticket @IBM.
However, no changes when using 0.4.7 extension.

**Comment by bearou** [comment]
@phaumer - this is getting critical; we have a management demo in a few days. Any lead to where we might look for clues ?

**Comment by phaumer** [comment]
My apologies @bearou, did z/OSMF support suggest anything? 
On our side we work on adding logging for Zowe operations. I will update this issue.

**Comment by phaumer** [comment]
@bearou the new 0.5.0 version now has a Logger that you can switch on in the user settings. Set it to Debug, reproduce the problem and send me the logs via email. We can the continue the analysis via email if you do not mind. Closing this item here now.

See <https://ibm.github.io/zopeneditor-about/Docs/knownissues.html#troubleshooting-using-log-files>
