### ISSUE TITLE
Outline view is not working for files opened with vscode debug session.

### ISSUE THREAD

**Issue by CuriousDev289** [IBM/zopeneditor-about#360]
## Problem Description

I am working on debug adapter extension for COBOL. In debug session for the COBOL program when source code is loaded, it is  outline view is not showing program structure. (color codeing on program is visible). Getting msg “No Symbols found” in ouline view. 

I have analyzed this issue with IBM Z Open Editor extension and found that the document selector has registered with **uri.scheme: “file”** only. Here VSCODE is opening debug source code in custom editor with uri.scheme : **debug**.

Tried editing extension.js and added the scheme : “debug” then it started showing the outline on cobol source code in debug session. Please find below changes i tried:

### Current line:
getLanguageClientOptions(){return{documentSelector:[{scheme:"file",language:s.Language.COBOL}],initializationOptions:this.getInitializationOptions()}}

### Updated line:
getLanguageClientOptions(){return{documentSelector:[{scheme:"file",language:s.Language.COBOL}**,{scheme:"debug",language:s.Language.COBOL}**],initializationOptions:this.getInitializationOptions()}}

### **Questions:**
1.	is it possible to add the “debug” uri.scheme for the document selector for all language?
2.	is it possible to provide the API to inform z open editor about any custom scheme?

Also please suggest if there is any other way to run the IBM Z open editor language parser on custom editors which has custom URI scheme.

Thanks!!

**Comment by CuriousDev289** [comment]
Thank you @phaumer for quick update.

**Comment by phaumer** [comment]
I agree. It will be a great enhancement.

**Comment by phaumer** [comment]
We added this with Z Open Editor 4.0.0
