### ISSUE TITLE
COBOL - Go To Reference of Intermediate Data Name Ignores COBOL Context

### ISSUE THREAD

**Issue by davidkcoblentz** [IBM/zopeneditor-about#362]
## Development environment used

- Z Open Editor version:
Version: 1.83.1 (user setup)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19044

  - Zowe CLI version: Not Used
  - Node.js version: Not Used
- Logs attached No

## Go To Reference of Intermediate Data Name Ignores COBOL Context

Detailed steps for reproducing the problem:

1. Create a COBOL source program that has a data name that is defined as an intermediate data name in multiple 01 Level definitions.
    for example see COBOL data name HIGHEST-ASSEMBLY-ID in the pic below. It is defined as in intermediate (15 Level) under 
    multiple 01 levels. 
    HIGHEST-ASSEMBLY-ID  OF ORIGINAL-USER-REQUEST OF **COMMON-WORK-AREA-2**  and
    HIGHEST-ASSEMBLY-ID OF ORIGINAL-USER-REQUEST OF **MWW001P**
2. Using SHIFT+F12 issue the GO TO REFERENCE command with the cursor in the HIGHEST-ASSEMBLY-ID data name.
3. The GO TO REFERENCE spyglass list does not consider the COBOL Context of the intermediate data name but lists ALL references to HIGHEST-ASSEMBLY-ID regardless of COBOL context to the 01 level.

### Observed behavior
Note the COBOL context of HIGHEST-ASSEMBLY-ID referenced in Working Storage in the pic below is:
HIGHEST-ASSEMBLY-ID  OF ORIGINAL-USER-REQUEST OF **COMMON-WORK-AREA-2**. 

In this program HIGHEST-ASSEMBLY-ID is also defined as an intermediate data name as part OF ORIGINAL-USER-REQUEST OF MWW001P.

In the spyglass code view HIGHEST-ASSEMBLY-ID OF ORIGINAL-USER-REQUEST OF **MWW001P** is listed but I would not expect it to be since it is not part of the original Go To Reference data name of **COMMON-WORK-AREA-2**.

### Expected behavior
I would expect the spyglass code view to only list references to HIGHEST-ASSEMBLY-ID as part of the 01 Level **COMMON-WORK-AREA-2** without listing references of  to HIGHEST-ASSEMBLY-ID as part of the 01 level **MWW001P**.

![image](https://github.com/IBM/zopeneditor-about/assets/80063515/77542541-1184-40b8-8d0e-0d02c5113f1c)

### *** Also noticed that if Go To Reference is used on elementary item MESSAGE-IND OF MWW005B it does not show the spyglass code view even though another reference exists besides the definition

I am attaching the COBOL source of this program.
[SC0WWFIC.txt](https://github.com/IBM/zopeneditor-about/files/13189759/SC0WWFIC.txt)
[MWW001P.txt](https://github.com/IBM/zopeneditor-about/files/13189810/MWW001P.txt)
[MWW005B.txt](https://github.com/IBM/zopeneditor-about/files/13189811/MWW005B.txt)

**Comment by Russell-May** [comment]
I agree, this looks like a bug.  I'll look into it.

**Comment by phaumer** [comment]
@davidkcoblentz we fixed it in v3.3.2. Can you verify?
