### ISSUE TITLE
Tabstops and Tabsize of the settings.json are no longer activ

### ISSUE THREAD

**Issue by SG-A47** [IBM/zopeneditor-about#365]
VSCode 1.79.2 
Z Open Editor 3.3.1
on Windows 11

The definitions for zopeneditor.cobol.tabstops and Tabsize of the settings.json don´t work any more after the last Update.
Tabsize now is 6 and there are no Tabstops.

There is no information that something might have changed along with the Updates of VSCode or Z Open Editor.
How can I get back my Tabstops and the Tabsize?

**Comment by phaumer** [comment]
@SG-A47 could you provide more details and the settings you are using? I do not see a change. 
When I define custom tab stops such as

```json
"zopeneditor.cobol.tabstops": [
    0,
    10,
    12,
    15
  ]
```

I can tab forward and backward as specified.

**Comment by SG-A47** [comment]
Here are my tabstops for cobol.
    "zopeneditor.cobol.tabstops": [
        0,
        6,
        7,
        11,
        14,
        17,
        20,
        23,
        26,
        29,
        32,
        35,
        38,
        41,
        44,
        71
    ],
These tabstops are now no longer working. Tabbing stops at 6, 11, 16 and so on. So tabsize is 5.
But 
![grafik](https://github.com/IBM/zopeneditor-about/assets/119935308/b3147f87-b871-4f55-9ba9-9fdb7828d538)
and User setting, workspace setting and Directory setting are the same. They are all 3.

**Comment by SG-A47** [comment]
Could it have something to do with the change to the ZAPP files?
If so, where do I have to copy the tab options in the zapp files?

**Comment by SG-A47** [comment]
I must state that there is no language specific indentation any more. The Editor is working with some fixed tab sizes. 
For Cobol it ist 5. 
![grafik](https://github.com/IBM/zopeneditor-about/assets/119935308/d53fdfc6-3328-4608-bbdb-1e3bedd0f5de)
For HLASM it is 6
![grafik](https://github.com/IBM/zopeneditor-about/assets/119935308/3485d46e-574f-459e-93da-c108e0f5eb6f)
The values for zopeneditor.cobol.tabstops are not active.
It seems that these options from the settings.json are not read.

**Comment by benjamin-t-santos** [comment]
@SG-A47 Can you try and follow the steps outlined here and send a screenshot of the output after you press 'tab' in a Cobol file?
https://code.visualstudio.com/docs/getstarted/keybindings#_troubleshooting-keybindings
That will help us tell if the tab is being recognized/handled correctly by our extension.

Other things to check:
- Do you have any other zOS/cobol extensions installed?
- During extension startup, are you seeing any other errors? Check the [Z Open Editor output log](https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html#finding-versions-of-all-vs-code-extensions-installed) after reloading your workspace (Open the command palette (Ctrl + Shift + P) and execute the command `>Reload Window`)

**Comment by FALLAI-Denis** [comment]
Hi,

It seems to me that the information `Spaces` (I do'nt have `Tab Size`?) returned in the VS Code status bar reflects the choices to replace tabs by spaces for indentations. Tab Size is also auto-detected by file analysis. Tab Size is not Tab Stop.
See [Basic Editing in Visual Studio Code - Indentation](https://code.visualstudio.com/docs/editor/codebasics#_indentation) in VS Code documentation.

Stopping on specific columns using the tab key seems to me to be a specific Z Open Editor feature, managed by the `zopeneditor.cobol.tabstops` setting.

In this screen capture, tab key is used before typing "x".
  
![TabStop](https://github.com/IBM/zopeneditor-about/assets/63861965/12dd10dc-bded-4ab9-8eaf-ba32213c9687)

**Comment by phaumer** [comment]
Excellent news. Thanks for the update.
