### ISSUE TITLE
COBOL LS - Error processing conditional compilation that wrongly exclude copybook inclusion and trigger false unresolved reference

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#366]
## Development environment used

- Z Open Editor version: 3.3.2
- Editor Platform
  - [X] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version: 1.84.2
- Operating System: Windows 10 x64 21H2
- Java Version: Java 11
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached: no

## Problem Description

Since the ZOE 3.3.2 update, the management of conditional compilation by the Language Server has greatly improved. Most of the problems have disappeared.
I thank you very much for the work accomplished.

However, a new problem has arisen.
Probably due to an internal miscalculation of the values of the conditional compilation variables by the Language Server, some copybooks find themselves excluded by conditional compilation conditions, which then causes errors in the Language Server's analysis:
* unresolved variables (they are in a wrongly excluded copybook)
* unresolved paragraph or section names (they are declared in wrongly excluded copybooks)

### Observed behavior

In the example below, the RTP1 variable used in a program is not resolved.
This variable is declared in the AAADGRUP copybook which is conditionally included by the compilation variable AA-A-LECTURES-AVEC-RUPT.
The compilation variable AA-A-LECTURES-AVEC-RUPT is declared (by a copybook) with the false value (b'0'), then is switched to the true value (b'1') when calling other copybooks.
Apparently the Language Server cannot manage changes in the values of this AA-A-READINGS-WITH-RUPT variable.
See in attachment the compilation listing of this program (or a version close to this program).

![image](https://github.com/IBM/zopeneditor-about/assets/63861965/73e30e43-c677-4a90-a01d-73642fb3fb4e)

### Expected behavior

See compilation listing:
[S9TL1A_listing.pdf](https://github.com/IBM/zopeneditor-about/files/13489009/S9TL1A_listing.pdf)

**Comment by FALLAI-Denis** [comment]
Hi,

This request has been categorized as "enhancement" but from my point of view it is a "bug" because false problems are declared by ZOE and this impacts the user.

**Comment by Russell-May** [comment]
I have been able to identify at least one issue that might be impacting you, but I have been unable to fully replicate what you are describing.  Would you be able to provide example files, either the ones you screenshotted from or stripped down versions that display the same issue?

**Comment by FALLAI-Denis** [comment]
Hi @Russell-May 

Thank you for your efforts in resolving these latest issues.
Attached, a zip file containing the minimum elements to reproduce the problem described here.

[ZOE366.zip](https://github.com/IBM/zopeneditor-about/files/13559066/ZOE366.zip)

**Comment by Russell-May** [comment]
> I replaced the ">>when other" clauses by ">>when codition" in the copybooks: all the false errors reported in the program have disappeared. However, there remain errors in the interpretation of the copybooks themselves.
> 
> Perhaps we should deactivate the analysis of conditional compilation in copybooks because in fact it has no meaning at the level of a copybook and only makes sense globally at the level of a program?

I'm glad that replacing the ">>when other" clause resulted in a clean parse from the main program for you as well.  It makes me confident that the upcoming fix for ">>when other" should get your COBOL parsing cleanly with no modifications.

As for the parsing of the copybooks themselves, this is the currently expected behavior as the copybook does not have the context to parse properly.  The suggestion of disabling the analysis of conditional compilation in copybooks I don't believe would have the desired effect as choosing to either include or exclude all of the conditional content would result in invalid COBOL in many cases leaving you with just as many errors as before.  We are continuing to consider different solutions for better copybook parsing and appreciate your input on it, but for now, parsing copybooks that require additional context from the COBOL file they are used in can result in unexpected errors.

**Comment by FALLAI-Denis** [comment]
Hi @Russell-May 

Regarding copybooks:
* VS Code allows you to display only the errors of the current file: I noticed that by activating this option no more errors were displayed for the main program
* the copybooks concerned are part of a framework and in principle the developer has no need / use to consult them in VS Code

So even if the analysis of copybooks is done taking into account conditional compilation this should not pose a problem on the main programs.

Ok to only deal with the problem related to the ">>when other" directive.

Thanks again for your efforts.

**Comment by phaumer** [comment]
Fixed for >>when other was deliver with v3.3.3. Please try, @FALLAI-Denis

**Comment by FALLAI-Denis** [comment]
Hi @phaumer,

Great !
This year Christmas fell on December 15!
I send a huge thank you to the entire ZOE development team!
I wish you a very happy end of year celebration.
