### ISSUE TITLE
IBM Open Editor

### ISSUE THREAD

**Issue by SUNDONEcindy** [IBM/zopeneditor-about#372]
## Development environment used

- Z Open Editor version:
- Editor Platform
  - [ ] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version:
- Operating System (on which VS Code runs such as Windows 10 2004, otherwise name and version of platform such as OpenShift v4.3):
- Java Version (when using VS Code or Theia, execute `java -version` and paste the details here):
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html) how to get them): yes/no

## Problem Description

Detailed steps for reproducing the problem:

1. First step

### Observed behavior

-

### Expected behavior

-

**Comment by phaumer** [comment]
Submitted by mistake?
