### ISSUE TITLE
COBOL - "No end directive" problem in case of >>define directive on the last line of a copybook

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#374]
## Development environment used

- Z Open Editor version: 3.3.3
- Editor Platform
  - [X] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version: 1.851
- Operating System: Windows 10 20H2 AMD64
- Java Version: Java 11
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached: no

## Problem Description

When the conditional compilation directive` >>define` is on the last line of a copybook, this will incorrectly raise an error regarding the absence of an end directive.

### Observed behavior

![image](https://github.com/IBM/zopeneditor-about/assets/63861965/cd134add-0fdc-4995-a129-379b61a610ea)

![image](https://github.com/IBM/zopeneditor-about/assets/63861965/55c09818-0c58-4ec6-a162-bbb669cac74b)

See also the other error messages that have no reason to exist.

**Comment by phaumer** [comment]
Fixed in v3.4.0.
