### ISSUE TITLE
REXX Comment /**/ tag all the file as comment

### ISSUE THREAD

**Issue by CorentinGrard** [IBM/zopeneditor-about#384]
## Development environment used

- Z Open Editor version:
- Editor Platform
  - [X] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version: 1.86.0 
- Operating System (on which VS Code runs such as Windows 10 2004, otherwise name and version of platform such as OpenShift v4.3): `MacOS 14.2.1 and Windows`
- Java Version (when using VS Code or Theia, execute `java -version` and paste the details here): `openjdk version "1.8.0_312"`
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html) how to get them): no

## Problem Description

Detailed steps for reproducing the problem:

1. Open a REXX file
2. Type a comment `/**/`
3. The rest of the file will now be tagged as comment

### Observed behavior

- `/**/` will tag rest the file as comment but `/* */` doesn't

### Expected behavior

- `/**/` should only tag as comment itself

**Comment by phaumer** [comment]
Fixed in v3.4.0.
