### ISSUE TITLE
Related to closed bug 1970 - issue with http only rse profile

### ISSUE THREAD

**Issue by zFernand0** [IBM/zopeneditor-about#386]
I do have the same issue, Zowe explorer is not working with a RSE account set with HTTP only.

Retrieving response from uss-file-list Error: Zowe REST Operations API Error: | http(s) request error event called | Error: write EPROTO 2242944:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:....\third_party\boringssl\src\ssl\tls_record.cc:231: |

Zowe CLI answer correctly without SSL.

_Originally posted by @Thibaut69 in https://github.com/zowe/vscode-extension-for-zowe/issues/2704_

---

This is the related closed bug:
- https://github.com/zowe/vscode-extension-for-zowe/issues/1970

**Comment by phaumer** [comment]
Hello @Thibaut69. I understand that sometimes you do not have control over how these server are deployed in your organization. But, we really cannot support pure http anymore. If we would even tried to deploy test servers like this in IBM all alarms would chime :-) I will propose that Zowe should remove the Protocol settings from the profiles.
