### ISSUE TITLE
Editor confused by ÅÄÖ regarding number of operands

### ISSUE THREAD

**Issue by COBOL-Erik** [IBM/zopeneditor-about#389]
## Development environment used

- Z Open Editor version:
- Editor Platform
  - [X] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version:
- Operating System (on which VS Code runs such as Windows 10 2004, otherwise name and version of platform such as OpenShift v4.3): Windows 11
- Java Version (when using VS Code or Theia, execute `java -version` and paste the details here):
java version "1.8.0_401"
Java(TM) SE Runtime Environment (build 1.8.0_401-b25)
Java HotSpot(TM) 64-Bit Server VM (build 25.401-b25, mixed mode)
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version: 7.18.2
  - Node.js version: v18.17.1
- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html) how to get them): no

## Problem Description

Detailed steps for reproducing the problem:

1. First step
Open an Assembler source member using Zowe Explorer in VS Code

### Observed behavior

Everything works fine, except when operands have Swedish letters in them. Then the editor will complain regarding the number of operands.
![image](https://github.com/IBM/zopeneditor-about/assets/32245335/31b33b48-650f-4f4d-a600-834e68a1d37b)
Note that the second ZAP, with operands without Ä in them, works fine.

### Expected behavior

ÅÄÖ should not break the editor in this way.

**Comment by phaumer** [comment]
Fixed in Z Open Editor 4.0.0
