### ISSUE TITLE
RSE API Plug-in for Zowe CLI do not get spool files for any job ID

### ISSUE THREAD

**Issue by alfonso-rios-ibm** [IBM/zopeneditor-about#39]
First command gets successfully the job ID but second command to list the spool files indicates the jobId was not found or does not exist.

```
zowe rse-api-for-zowe-cli list jobs -o "START1" -p "DBCGIRLM" --rse-profile torzdt1.canlab.ibm.com
STC00040   DBCGIRLM ACTIVE
```

```
zowe rse ls sfbj STC00040 --rse-p torzdt1.canlab.ibm.com
Command Error:
jobId was not found or does not exist.
```

**Comment by JillieBeanSim** [comment]
Thanks Alfonso for bringing this to our attention. I will address this issue.

**Comment by phaumer** [comment]
The issue was fixed now. Please, go back to the [Download Site](https://epwt-www.mybluemix.net/software/support/trial/cst/welcomepage.wss?siteId=536&tabId=1045&w=1&p=1&_ga=2.108910983.403655627.1584975487-2110257964.1580332105), download the latest version 0.4.8 and install it.
