### ISSUE TITLE
TSO Support in RSE API?

### ISSUE THREAD

**Issue by travatine** [IBM/zopeneditor-about#40]
Hi,

Is there any plans to add TSO command support to RSE API?

Today i use "issueCommand" (from ZOSMF) to run "TSO rexx execs" or "call MVS programs".
It'd be great if RSE could be used to do the same ( as ZOSMF).

Thanks

**Comment by phaumer** [comment]
Thanks a lot for filing the request.

**Comment by travatine** [comment]
Hi,
Is there any plans for adding TSO support in 2020?

Thanks

**Comment by travatine** [comment]
Hi @phaumer ,

I see that the RSE API now has TSO command support:
![image](https://user-images.githubusercontent.com/17565183/96202584-31cb9700-0f92-11eb-9388-634006d5e50a.png)

**Comment by phaumer** [comment]
@travatine yes, we [announced](https://www-01.ibm.com/common/ssi/ShowDoc.wss?docURL=/common/ssi/rep_ca/5/899/ENUSLP20-0515/index.html&request_locale=en) it now and it will be available Friday. See here for more details: https://ibm.github.io/zopeneditor-about/Blog/rse-october-110.html#issue-tso-commands

**Comment by travatine** [comment]
Thanks again @phaumer , I'll try it out friday

**Comment by mariamerola1** [comment]
Hi @phaumer I see that it was released the new version of IBM RSE API Plug-in for Zowe CLI 1.1.0. Following the instructions from this link  https://ibm.github.io/zopeneditor-about/Docs/setup_integration.html#installing-the-requisite-ibm-rse-api-z-os-host-component I starting the dowload from here: https://ibm.github.io/mainframe-downloads/downloads.html  clicking on VS CODE. When it is finished the download in the zip file there is still IBM RSE API Plug-in for Zowe CLI 1.0.0. How can install the new version?

**Comment by phaumer** [comment]
@travatine @mariamerola1 IBM RSE API Zowe CLI Plugin 1.1.0 is now available here: https://ibm.github.io/mainframe-downloads/downloads.html#wazi

Summary of what is new in 1.1 is here: https://ibm.github.io/zopeneditor-about/Blog/rse-october-110.html#issue-tso-commands

See here for what else is new: https://ibm.github.io/zopeneditor-about/Blog/new-content.html

**Comment by travatine** [comment]
Thanks @phaumer , 
I can now invoke TSO commands via RSE from zowe cli:
![image](https://user-images.githubusercontent.com/17565183/97830550-43d66500-1d08-11eb-8663-d9bd0ff81df2.png)

**Comment by mariamerola1** [comment]
Hi @travatine , I removed the old version of RSE API plug in and I just installed the new version of RSE API Plug in 1.1.0:
<img width="452" alt="immagine" src="https://user-images.githubusercontent.com/64986198/97862854-564f9f00-1d06-11eb-88da-22b1e34a517e.png">
When I try to run the command: zowe rse issue command "HELP COMMANDS" I receive this:


mariamerola@MacBook-Pro-di-Maria-2 ~ % zowe rse issue command "HELP-COMMANDS"
Command Error:
Issue TSO Command is not supported with RSE API**v1.0.0.**
mariamerola@MacBook-Pro-di-Maria-2 ~ % 


Do you know why?

**Comment by travatine** [comment]
Hi @mariamerola1 , I also needed to install the latest RSE API PTFs, you get them on shop z or from here http://public.dhe.ibm.com/ibmdl/export/pub/software/htp/zos/tools/rse-api-ptf/com.ibm.rseapi.host.smpe.ptf-1.0.1-0-0-hama100-ui71260.zip and http://public.dhe.ibm.com/ibmdl/export/pub/software/htp/zos/tools/rse-api-ptf/com.ibm.rseapi.host.smpe.ptf-1.0.2-0-0-hama100-ui72086.zip

**Comment by mariamerola1** [comment]
Thanks @travatine .
