### ISSUE TITLE
COBOL formatter - Errors formatting SQL statements

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#400]
## Development environment used

- Z Open Editor version: 4.1.0
- Editor Platform
  - [X] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version: 1.88.0
- Operating System: Windows 10 22H2
- Java Version: 1.7
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached: no

## Problem Description

The COBOL formatter incorrectly reformats the SQL statements included in the program.

Regarding SQL comments:
* applies uppercase/lowercase conversions on these comments
* does not recognize the sequence `--` and transforms it into `- - ` which makes the code uncompilable

In fact, the texmate grammar, like the COBOL language server, does not seem to manage comments included in SQL statements.

Regarding the management of parentheses:
* the opening parenthesis is stuck to the word that precedes it; same problem seen on purely COBOL instructions using subscripted/indexed variables

### Observed behavior

* SQL comments:
![image](https://github.com/IBM/zopeneditor-about/assets/63861965/1f800e9e-d3d3-4b89-93fb-77da726b41a1)
![image](https://github.com/IBM/zopeneditor-about/assets/63861965/0d50bf82-9986-413c-bc11-29dd45ff8218)

* Opening parenthesis
![image](https://github.com/IBM/zopeneditor-about/assets/63861965/3dde73ca-58ae-440d-ba4d-1f6083392137)
![image](https://github.com/IBM/zopeneditor-about/assets/63861965/34c1c6f6-f7f2-46a6-9b06-3047ae9e67ec)

**Comment by phaumer** [comment]
We addressed this problem in v4.2.0. Let us know if this work for you.
