### ISSUE TITLE
Extension not activating when unable to write settings

### ISSUE THREAD

**Issue by Peariforme** [IBM/zopeneditor-about#403]
## Development environment used

- Z Open Editor version: 3.3.3
- Editor Platform
  - Visual Studio Code : 1.85.1
- Operating System : Windows 11
- Java Version : 21.0.1

## Problem Description

Sometimes IBM Z Open editor extension does not activate at startup. which leads to some message saying that function has not been found.
![image](https://github.com/IBM/zopeneditor-about/assets/47952322/64f3c852-241c-491c-935f-c5c0c103cdc1)

We can see in the developper console that it is related to the incapacity at activation to write in the settings
![image](https://github.com/IBM/zopeneditor-about/assets/47952322/b2d4cf19-da81-4c6e-8f92-df7b0b9a823b)

Why does the extension needs to write on settings at each startup ? Could you tackle the errors so that it can be seen by user without going to the developper console, for example with a notification ?

**Comment by RichardSGFR** [comment]
Hello, do you now if this bug will be resolved soon ?

**Comment by phaumer** [comment]
We reorganized the startup activities to adjust the order of initializing thing as well as deal with concurrency issues. Hopefully you will not see this issue anymore in v4.2.0.
