### ISSUE TITLE
ROTATE THEN AND SELECTED BITS number of operands

### ISSUE THREAD

**Issue by Dylan-hub-bit** [IBM/zopeneditor-about#418]
Development environment used
- Z Open Editor version: v4.2.0
- Editor Platform
  - [x] Visual Studio Code
- Editor Platform Version: 1.90.0 (user setup)
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
Date: 2024-06-04T19:33:54.889Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
- Operating System: Windows_NT x64 10.0.19045
- Java Version:
openjdk version "17.0.8.1" 2023-08-24
OpenJDK Runtime Environment Temurin-17.0.8.1+1 (build 17.0.8.1+1)
OpenJDK 64-Bit Server VM Temurin-17.0.8.1+1 (build 17.0.8.1+1, mixed mode, sharing)
- Logs attached: no

The ROTATE THEN AND SELECTED BITS instruction is reporting an error expecting 5 operands, but it shouldn't because the 5th operand is optional.

Detailed steps for reproducing the problem:

Open a HLASM module with the following instruction:
      RNSBGT &R,&R,34,63       
and in the Problems window it reports the following:
"Unexpected number of operands. Expected 5 but found 4"

[{
	"resource": "/c:/Users/me/git/myrepo/blah.asm",
	"owner": "_generated_diagnostic_collection_name_#4",
	"code": "-6",
	"severity": 8,
	"message": "Unexpected number of operands. Expected 5 but found 4",
	"startLineNumber": 415,
	"startColumn": 10,
	"endLineNumber": 415,
	"endColumn": 16
}]

The Principles of Operations has:
ROTATE THEN AND SELECTED BITS
RNSBG R1,R2,I3,I4[,I5] [RIE-f]
ROTATE THEN EXCLUSIVE OR SELECTED BITS
RXSBG R1,R2,I3,I4[,I5] [RIE-f]
ROTATE THEN OR SELECTED BITS 
ROSBG R1,R2,I3,I4[,I5] [RIE-f]

**Comment by sdaimwood** [comment]
This bug was fixed in version 4.3.0. Thank you for reporting the problem.

The error messages should be more concise and helpful when optional operands are present.
