### ISSUE TITLE
New version of z/Open Editor was pushed out today and now getting message about the need for a Java > V11

### ISSUE THREAD

**Issue by davidkjackson54** [IBM/zopeneditor-about#419]
This only started this morning after a new version of z/Open Editor was pushed out to VSCcode.

I am getting this message:
![image](https://github.com/IBM/zopeneditor-about/assets/46171060/fdcf0c72-4103-46d7-82b2-888e55971b55)

I am running Semeru V21
A **Java --version** shows this:

java --version
**openjdk 21.0.3 2024-04-16 LTS
IBM Semeru Runtime Open Edition 21.0.3.0 (build 21.0.3+9-LTS)
Eclipse OpenJ9 VM 21.0.3.0 (build openj9-0.44.0, JRE 21 Windows 11 amd64-64-Bit Compressed References 20240416_179 (JIT enabled, AOT enabled)
OpenJ9   - b0699311c7
OMR      - 254af5a04
JCL      - ac8f341bc20 based on jdk-21.0.3+9)**

**Comment by benjamin-t-santos** [comment]
Hi @davidkjackson54, sorry that the recent Z Open Editor update is causing you this issue.
I was able to get the same Java (IBM Semeru 21.0.3.0) working with Z Open Editor 4.3.0 on Windows 11, so I feel confident that we can this working for you again.
Some questions that will help us fix this:
- Can you share your output for `java -version`? (with a single hyphen, `-version` vs. `--version`)
- Open the Z Open Editor Welcome Page by opening the command prompt (Ctrl + Shift + P) and running `">IBM Z Open Editor: Welcome"`. Scroll down to the prerequisites section and expand the "64-bit Java version 11 or higher is found" section. It provides info on where Z Open Editor looked for your Java. If you could send me a screenshot of yours, that would be very helpful. Here is mine for reference:
<img width="1132" alt="Screenshot 2024-06-18 at 7 58 05 PM" src="https://github.com/IBM/zopeneditor-about/assets/115251181/07d8b3bf-b7ee-44d8-acf0-87d5510de94f">

Thanks.

**Comment by davidkjackson54** [comment]
The java --version and java -version both provide the exact same information:
C:\Users\djackson4>**java --version**
openjdk 21.0.3 2024-04-16 LTS
IBM Semeru Runtime Open Edition 21.0.3.0 (build 21.0.3+9-LTS)
Eclipse OpenJ9 VM 21.0.3.0 (build openj9-0.44.0, JRE 21 Windows 11 amd64-64-Bit Compressed References 20240416_179 (JIT enabled, AOT enabled)
OpenJ9   - b0699311c7
OMR      - 254af5a04
JCL      - ac8f341bc20 based on jdk-21.0.3+9)

C:\Users\djackson4>**java -version**
openjdk version "21.0.3" 2024-04-16 LTS
IBM Semeru Runtime Open Edition 21.0.3.0 (build 21.0.3+9-LTS)
Eclipse OpenJ9 VM 21.0.3.0 (build openj9-0.44.0, JRE 21 Windows 11 amd64-64-Bit Compressed References 20240416_179 (JIT enabled, AOT enabled)
OpenJ9   - b0699311c7
OMR      - 254af5a04
JCL      - ac8f341bc20 based on jdk-21.0.3+9)

The Z/Open Editor welcome screen shows this:
![image](https://github.com/IBM/zopeneditor-about/assets/46171060/74f99cfb-8e67-4a93-ad0a-7a02d0689d85)

I noticed in your screen shot that you point to the uppoer folder whereas in mine IW asw pointing ath t /bin.
I changed by JAVA_HOME to come up one level:
![image](https://github.com/IBM/zopeneditor-about/assets/46171060/be86e423-7a35-46b0-b0a1-8d42fd791475)

 It now works...    I seem to remember that at one point in time you had to point to the bin but clearly not now!
