### ISSUE TITLE
Not able to open DBB metadata file (BuildReport.html and BuildReport.json)  in browser

### ISSUE THREAD

**Issue by ratnamGT** [IBM/zopeneditor-about#421]
I have created DBB metadata reports in Mainframe USS file path and exported it through DBB CLI .BuildReport.html and BuildReport.json files are in my Mainframe USS path . I am not able to  open the files in VScode USS .It is opening in binary format in VScode editor . I want to open it in the browser to see the metadata and dependency reports.
Could you please help me on this?

**Comment by benjamin-t-santos** [comment]
Hi @ratnamGT. Which UI are you trying to use to open the files (Zowe Explorer, z/OS Resources Table, etc.)? If you could attach a screenshot or video that would be helpful.

**Comment by ratnamGT** [comment]
@benjamin-t-santos  Thanks for your response ,I am trying Zowe Explorer ,I opened the BuildReport.html with encoding ISO8859-1 and it opened in HTML source code . But I want to use that file in browser from Zowe Explorer .
I am attaching the screenshot.
![builreport screenshot from zowe editor](https://github.com/IBM/zopeneditor-about/assets/172598523/673b0a20-4c90-44e5-ab69-381026bafe32)
![builreport screenshot from zowe editor](https://github.com/IBM/zopeneditor-about/assets/172598523/2c95d5d9-a138-48e6-886e-5d59c8dc66a5)

**Comment by benjamin-t-santos** [comment]
Thanks. Zowe Explorer is a VS Code extension published by [Zowe](https://www.zowe.org/). It is open-source and not maintained by IBM. If this is a feature you would like to see in Zowe Explorer, I would recommend creating an enhancement request on their repository: https://github.com/zowe/zowe-explorer-vscode

When a USS file is opened in Zowe Explorer, it is downloaded locally to a temporary folder and opened in a new editor. You can see at the top of your editor the path to this temporary folder. You should be able to open the HTML file in a browser from there. Another option is downloading your files from USS using Zowe CLI.
