### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by OrtizUNT** [IBM/zopeneditor-about#423]
![help](https://github.com/IBM/zopeneditor-about/assets/173732346/b91b2791-483e-4046-8d8a-f03cfd05a5fc)
![help2](https://github.com/IBM/zopeneditor-about/assets/173732346/7540a5b9-0589-4bc9-8cb4-485e30b5ffbe)
## Development environment used

- Z Open Editor version: [Your Z Open Editor version]
- Editor Platform
  - [x] Visual Studio Code
- Editor Platform Version: [Your VS Code version]
- Operating System (on which VS Code runs such as Windows 10 2004, otherwise name and version of platform such as OpenShift v4.3): Windows 10 [Your Windows version]

## Problem Description

Detailed steps for reproducing the problem:

1. Installed Java 64-bit version 17 or higher.
2. Set JAVA_HOME environment variable to `C:\Program Files\Java\jdk-17`.
3. Configured `zopeneditor.JAVA_HOME` in VS Code settings to `C:\Program Files\Java\jdk-17`.
4. Restarted Visual Studio Code.

### Observed behavior

In the VS Code settings, the `zopeneditor.JAVA_HOME` and other Java location fields are showing as not valid. The editor does not recognize the Java installation.

### Expected behavior

VS Code should recognize the Java installation correctly, and `zopeneditor.JAVA_HOME` should be validated and used without issues.

**Comment by benjamin-t-santos** [comment]
Hi @OrtizUNT. To help you debug this issue, can you send me the following information:

- The output of running `java -version` in your terminal
- Your Z Open Editor output log on DEBUG level - https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html#troubleshooting-using-log-files

Can you also ensure that `C:\Program Files\Java\jdk-17`directory contains the `bin` folder? Its contents should look something like this.
<img width="858" alt="Screenshot 2024-06-25 at 8 44 32 AM" src="https://github.com/IBM/zopeneditor-about/assets/115251181/e07c7243-b430-4cab-8bf3-0ad919ca4ce1">

**Comment by OrtizUNT** [comment]
It contains the bin folder but it has the README google file too is that suppose to be there ?

And I also did the zopeneditor log and set it to DEBUG

I can't figure out how to see the output of running java - versioon in my terminal how do i find that ?

________________________________
From: benjamin-t-santos ***@***.***>
Sent: Tuesday, June 25, 2024 7:47 AM
To: IBM/zopeneditor-about ***@***.***>
Cc: Ortiz Orozco, Carlos ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [IBM/zopeneditor-about] Installation Issue (Issue #423)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Hi @OrtizUNT<https://github.com/OrtizUNT>. To help you debug this issue, can you send me the following information:

  *   The output of running java -version in your terminal
  *   Your Z Open Editor output log on DEBUG level - https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html#troubleshooting-using-log-files

Can you also ensure that C:\Program Files\Java\jdk-17directory contains the bin folder? Its contents should look something like this.
Screenshot.2024-06-25.at.8.44.32.AM.png (view on web)<https://github.com/IBM/zopeneditor-about/assets/115251181/e07c7243-b430-4cab-8bf3-0ad919ca4ce1>

**Comment by OrtizUNT** [comment]
![help22222](https://github.com/IBM/zopeneditor-about/assets/173732346/0faccce4-e1c7-4937-9935-904ef103949f)
![p2](https://github.com/IBM/zopeneditor-about/assets/173732346/50a22625-cd4e-4f62-977e-3646ab7d3d37)

**Comment by benjamin-t-santos** [comment]
- On Windows, open up a terminal and type `java-version`. Paste the output here.
- Now that the log level is set to debug, can you paste the Z Open Editor log after reloading VS Code? You can reload VS Code with the command palette (Ctrl + Shift + P and enter "Developer: Reload Window") and then open the log following the guide in that link I commented.
- I notice that in your screenshot of the Java folder, the path to that folder is different than the one specified in your JAVA_HOME variable (jdk-11 vs jdk-17). Is this on purpose?
- Can you try opening your VS Code settings and add the `"zopeneditor.JAVA_HOME"` setting, with the path to your Java as the setting's value?

**Comment by benjamin-t-santos** [comment]
@OrtizUNT did any of those fixes work for you?

**Comment by OrtizUNT** [comment]
I figured it out thank you

**Comment by OrtizUNT** [comment]
Yes, I finally got it to work thank you but now I'm having an issue with REXX1 step 4 where it asks to enter this zowe profiles create tso-profile zxplore -a FB3 after copying and pasting GUESSNUM and SOMEREXX to my Zxxxxx.SOURCE

This is what it tells me

PS C:\Users\corti> zowe profiles create tso-profile zxplore -a FB3
zowe : File C:\Users\corti\AppData\Roaming\npm\zowe.ps1 cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ zowe profiles create tso-profile zxplore -a FB3
+ ~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess


________________________________
From: benjamin-t-santos ***@***.***>
Sent: Tuesday, July 2, 2024 10:01 AM
To: IBM/zopeneditor-about ***@***.***>
Cc: Ortiz Orozco, Carlos ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [IBM/zopeneditor-about] Installation Issue (Issue #423)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

@OrtizUNT<https://github.com/OrtizUNT> did any of those fixes work for you?

**Comment by benjamin-t-santos** [comment]
I would recommend asking for help with that question on the IBM Z Xplore learning platform.

**Comment by benjamin-t-santos** [comment]
I would recommend asking for help with that question on the IBM Z Xplore learning platform.
