### ISSUE TITLE
RSE profiles not returning members with Zowe Explorer member filter search

### ISSUE THREAD

**Issue by JillieBeanSim** [IBM/zopeneditor-about#426]
Porting issue for RSE type profiles:

> Greetings,
> 
> ## The problem
> Trying to Retrieve members with a filter in populous datasets doesn't return the expected results. The magnitude is around ten thousand for the particular dataset where the problem was detected.
> 
> [Issue 1270](https://github.com/zowe/zowe-explorer-vscode/issues/1270) looks similar, but this issue doesn't talk about filters.
> 
> ### Error recreation
> Recreation requires a dataset with thousands of member. I will name such dataset "TEST.DS". Assume this dataset has an even spread of members in alphabetical ordering.
> 
> * Navigate to Zowe Explorer tree view
> * Open contextual menu in profile
> * Select "Filter PDS members"
> * Search for "TEST.DS(Q*)"
> 
> Result is:
> 
> > No results are returned.
> 
> Expected result is:
> 
> > Results are returned and start with "Q"
> 
> Next is a recreation of the error in our environment: ![filter_dataset-error](https://private-user-images.githubusercontent.com/31370603/343250677-a00dfd18-8b2a-473e-8a45-c65ab635a8f2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMzM3NzksIm5iZiI6MTcyMTMzMzQ3OSwicGF0aCI6Ii8zMTM3MDYwMy8zNDMyNTA2NzctYTAwZGZkMTgtOGIyYS00NzNlLThhNDUtYzY1YWI2MzVhOGYyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDIwMTExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwMDJmNDFkOWI2ZTY3ODIxMTA4NmIzNTJhMzcyNWEyMWRiNzE1YmM5ZDdmMWFhOTIzMGExZDIyODZjOTk2MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Ssyj5aL_tZB9tvaCzZ8zkUNheX44NIt1q3EbskmQLc) [ ![filter_dataset-error](https://private-user-images.githubusercontent.com/31370603/343250677-a00dfd18-8b2a-473e-8a45-c65ab635a8f2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMzM3NzksIm5iZiI6MTcyMTMzMzQ3OSwicGF0aCI6Ii8zMTM3MDYwMy8zNDMyNTA2NzctYTAwZGZkMTgtOGIyYS00NzNlLThhNDUtYzY1YWI2MzVhOGYyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDIwMTExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwMDJmNDFkOWI2ZTY3ODIxMTA4NmIzNTJhMzcyNWEyMWRiNzE1YmM5ZDdmMWFhOTIzMGExZDIyODZjOTk2MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Ssyj5aL_tZB9tvaCzZ8zkUNheX44NIt1q3EbskmQLc) ](https://private-user-images.githubusercontent.com/31370603/343250677-a00dfd18-8b2a-473e-8a45-c65ab635a8f2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMzM3NzksIm5iZiI6MTcyMTMzMzQ3OSwicGF0aCI6Ii8zMTM3MDYwMy8zNDMyNTA2NzctYTAwZGZkMTgtOGIyYS00NzNlLThhNDUtYzY1YWI2MzVhOGYyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDIwMTExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwMDJmNDFkOWI2ZTY3ODIxMTA4NmIzNTJhMzcyNWEyMWRiNzE1YmM5ZDdmMWFhOTIzMGExZDIyODZjOTk2MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Ssyj5aL_tZB9tvaCzZ8zkUNheX44NIt1q3EbskmQLc) [ ](https://private-user-images.githubusercontent.com/31370603/343250677-a00dfd18-8b2a-473e-8a45-c65ab635a8f2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMzM3NzksIm5iZiI6MTcyMTMzMzQ3OSwicGF0aCI6Ii8zMTM3MDYwMy8zNDMyNTA2NzctYTAwZGZkMTgtOGIyYS00NzNlLThhNDUtYzY1YWI2MzVhOGYyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDIwMTExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwMDJmNDFkOWI2ZTY3ODIxMTA4NmIzNTJhMzcyNWEyMWRiNzE1YmM5ZDdmMWFhOTIzMGExZDIyODZjOTk2MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Ssyj5aL_tZB9tvaCzZ8zkUNheX44NIt1q3EbskmQLc)
> 
> ### Ancillary tests
> #### Under hundred members dataset
> Assume dataset "LIGHT.DS" with less than 100 members.
> 
> * Navigate to Zowe Explorer tree view
> * Open contextual menu in profile
> * Select "Filter PDS members"
> * Search for "LIGHT.DS(Q*)"
> 
> Result is:
> 
> > Results are returned and start with "Q".
> 
> #### Curl call
> Assume dataset "TEST.DS". More than a thousand members. this dataset has an even spread of members in alphabetical ordering.
> 
> Use the following curl (replace what is needed):
> 
> > curl -X 'GET' '{{mainframehost}}/rseapi/api/v1/datasets/search/PDSMembers?filter={{TEST.DS}}&memberPattern=Q%2A' -H 'accept: application/json' -H 'Authorization: {{auth}}' -H 'Number-Of-Results: 50000'
> 
> Result is:
> 
> > Results are returned and start with "Q"
> 
> Recreation in our environment: ![filter_dataset-curl](https://private-user-images.githubusercontent.com/31370603/343250624-d82b4444-a031-424f-8472-996692c9342b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMzM3NzksIm5iZiI6MTcyMTMzMzQ3OSwicGF0aCI6Ii8zMTM3MDYwMy8zNDMyNTA2MjQtZDgyYjQ0NDQtYTAzMS00MjRmLTg0NzItOTk2NjkyYzkzNDJiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDIwMTExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2NjI3ZmIyZWZmYmVjZjc4ZTkyYjFlZWJhNTBkMjM5ZGJjNmQ0MmM3ZjQwY2Q4NjkzZmViMDQyZGRhZDIwMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bN26e_gkdzlqhkISWCkKT7dBL-8RPunRadYRuMwyP2I) [ ![filter_dataset-curl](https://private-user-images.githubusercontent.com/31370603/343250624-d82b4444-a031-424f-8472-996692c9342b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMzM3NzksIm5iZiI6MTcyMTMzMzQ3OSwicGF0aCI6Ii8zMTM3MDYwMy8zNDMyNTA2MjQtZDgyYjQ0NDQtYTAzMS00MjRmLTg0NzItOTk2NjkyYzkzNDJiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDIwMTExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2NjI3ZmIyZWZmYmVjZjc4ZTkyYjFlZWJhNTBkMjM5ZGJjNmQ0MmM3ZjQwY2Q4NjkzZmViMDQyZGRhZDIwMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bN26e_gkdzlqhkISWCkKT7dBL-8RPunRadYRuMwyP2I) ](https://private-user-images.githubusercontent.com/31370603/343250624-d82b4444-a031-424f-8472-996692c9342b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMzM3NzksIm5iZiI6MTcyMTMzMzQ3OSwicGF0aCI6Ii8zMTM3MDYwMy8zNDMyNTA2MjQtZDgyYjQ0NDQtYTAzMS00MjRmLTg0NzItOTk2NjkyYzkzNDJiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDIwMTExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2NjI3ZmIyZWZmYmVjZjc4ZTkyYjFlZWJhNTBkMjM5ZGJjNmQ0MmM3ZjQwY2Q4NjkzZmViMDQyZGRhZDIwMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bN26e_gkdzlqhkISWCkKT7dBL-8RPunRadYRuMwyP2I) [ ](https://private-user-images.githubusercontent.com/31370603/343250624-d82b4444-a031-424f-8472-996692c9342b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMzM3NzksIm5iZiI6MTcyMTMzMzQ3OSwicGF0aCI6Ii8zMTM3MDYwMy8zNDMyNTA2MjQtZDgyYjQ0NDQtYTAzMS00MjRmLTg0NzItOTk2NjkyYzkzNDJiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDIwMTExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2NjI3ZmIyZWZmYmVjZjc4ZTkyYjFlZWJhNTBkMjM5ZGJjNmQ0MmM3ZjQwY2Q4NjkzZmViMDQyZGRhZDIwMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bN26e_gkdzlqhkISWCkKT7dBL-8RPunRadYRuMwyP2I)
> 
> ## Miscelaneous data
> * OS: Windows_NT x64 10.0
> * Zowe Explorer Version: 2.16.2
> * Zowe CLI Version: 7.13.0
> 
> When we call the server through VS Code, the server registered this entry:
> 
> > --------------- - - [---------------------] "GET /rseapi/api/v1/datasets/search/PDSMembers?filter=CMN.ABASE.CPY&memberPattern=* HTTP/1.1" 200
> 
> Otherwise, with curl, the server entry is:
> 
> > --------------- - - [---------------------] "GET /rseapi/api/v1/datasets/search/PDSMembers?filter=CMN.ABASE.CPY&memberPattern=Q* HTTP/1.1" 200
> 
> We believe the filtering is happening client-side in the explorer and that is what is causing the bug since there is a limit of items fetched.

## Development environment used

- Z Open Editor version:
- Editor Platform
  - [ ] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version:
- Operating System (on which VS Code runs such as Windows 10 2004, otherwise name and version of platform such as OpenShift v4.3):
- Java Version (when using VS Code or Theia, execute `java -version` and paste the details here):
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html) how to get them): yes/no

## Problem Description

Detailed steps for reproducing the problem:

1. First step

### Observed behavior

-

### Expected behavior

-

**Comment by antonkc** [comment]
Here it is:
ibm.zopeneditor 4.3.0
zowe.vscode-extension-for-zowe 2.17.0
RSE API 3.3.0.0

**Comment by likhithanimma1** [comment]
> Here it is: ibm.zopeneditor 4.3.0 zowe.vscode-extension-for-zowe 2.17.0 RSE API 3.3.0.0

Hey @antonkc Can you update to the latest version of RSEAPI?  The latest one would be part of z/OS Explorer 3.3.5. and confirm that if you are still seeing the issue

**Comment by antonkc** [comment]
Greetings @likhithanimma1 ,

Updated the versions. The same error happens. Same characteristics. By the way, it also happens in ZOSMF.

**Comment by JillieBeanSim** [comment]
Thanks for the information @antonkc.
Hey @likhithanimma1 if this is verified to be an issue with zosmf type profiles too, we should be able to reopen the ZE issue this was ported from for a resolution since it's not rse type profile specific.

**Comment by likhithanimma1** [comment]
Closing this issue and reopening the issue https://github.com/zowe/zowe-explorer-vscode/issues/2978 for resolution where it is ported from as it is not only specific with rse but also with zosmf .
