### ISSUE TITLE
Zowe RSE CLI : command returning only after timeout while downloading a dataset

### ISSUE THREAD

**Issue by Thibaut69** [IBM/zopeneditor-about#427]
node -v
v20.10.0

zowe --version
7.25.1

zowe plugins list
 -- pluginName: @ibm/rse-api-for-zowe-cli
 -- package: @ibm/rse-api-for-zowe-cli
 -- version: 4.3.0
 -- registry: http://registry.npmjs.org/

 -- pluginName: @zowe/db2-for-zowe-cli
 -- package: @zowe/db2-for-zowe-cli@zowe-v2-lts
 -- version: 5.0.7
 -- registry: http://registry.npmjs.org/

## Problem Description

While launching a command : zowe rse dl ds "xxx.yyy" -f "./tmp/myfile.txt"

I get a success response

success: true
from:    xxx.yyy
to:      ./tmp/myfile.txt

file_to_download: 1
success:          1
error:            0
skipped:          0

But then, the prompt in VsCode terminal don't give back hand during 60 seconds timeout.

So if you want to download files 1 by 1, your script will wait for 60 secondes between 2 downloads.

**Comment by phaumer** [comment]
Fixed in v4.4.0. Can you let us know if it worked for you?
