### ISSUE TITLE
User revoked because of copybook retrieving

### ISSUE THREAD

**Issue by RichardSGFR** [IBM/zopeneditor-about#429]
## Development environment used

- Z Open Editor version: 4.1.0
- Editor Platform
  - [ ] Visual Studio Code 
- Editor Platform Version: 1.88.0

## Problem Description

When having a zapp.yaml file set up to retrieve copybook direclty on MVS, IBM Z/open editor use the Zowe profile to retrieve the copybook. If the password on the zowe profile is incorrect, the users get no information saying there is a password issue and in the end get his user revoked.

Could it be possible to add a warning that users would be able to understand saying that the copybook retrieve action has failed because of zowe bad credentials ?

**Comment by FALLAI-Denis** [comment]
Hi,

Concerned by this problem in the past, and having opened various incidents for this, which have been dealt with, in principle today the problem should be resolved... except perhaps in certain cases:
* expired password management
* password change directly at TSO level (RACF or TSS), while a VS Code session is already open.

See:
* #142 
* #197
* #249 
* #255

The conditions under which the problem occurred should be detailed.
Also see if you are working with z/OSMF or RSEs (in my case z/OSMF).
Do you have access to the MVS log to see the ICH408 messages associated with your user?
If yes, does the revocation occur after several erroneous accesses?

From what I understand of how Z Open Editor currently works:
* Before any search for "mvs" copybooks, query the list of "SYS1.PROCLIB" files to validate the credentials
* At this stage there should be a 401 return code and a pop-up requesting the update of credentials in Z Open Editor
* If the credentials are validated, Z Open Editor opens several channels in parallel for downloading "mvs" copybooks (I think there are 5).

**Comment by RichardSGFR** [comment]
Hello,

I am using a z/osmf profile. For me  it seems to be the second case : 

"password change directly at TSO level (RACF or TSS), while a VS Code session is already open."

I'll try to reproduce it

**Comment by phaumer** [comment]
@RichardSGFR as @FALLAI-Denis correctly described this would be a regression of missed scenario for us. So it would be good if you could describe the exact steps you are performing and perhaps share you Debug-level log file with us.

**Comment by RichardSGFR** [comment]
I do not reproduce the issue, I'll close this ticket. I4ll open a new one if I understand how it happened.
