### ISSUE TITLE
z open editor in  vscode hover not functioning Using IBM/ Eclipse JDK

### ISSUE THREAD

**Issue by azrlb** [IBM/zopeneditor-about#43]
Win 10, Z open version 0.49, Zowe explorer version 1.4.1 
JAVA SDK: dowloaded from IBM/Eclipse version
PATH: zopeneditor.JAVA_HOME": "C:\\Program Files\\IBM\\Eclipse\\ibm_sdk80"

COBOL: Hover does not show declaration of variable.

BTW: Get this error from COBOL language server if I click on variable instead of hover
"Request textDocument/documentLink failed.
  Message: Internal error.
  Code: -32603"
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: com.ibm.systemz.cobol.editor.core.parser.CobolParseController

Caused by: java.lang.NoClassDefFoundError: com.ibm.systemz.cobol.editor.core.parser.CobolParseController
	at com.ibm.lsp.cobol.core.handlers.DocumentLinkHandler.getDocumentLinks(DocumentLinkHandler.java:36)

I got it working by downloading/using Oracle Java SDK Version 8 ("C:\\Program Files\\Java\\jdk1.8.0_251)  instead of IBM SDK on Eclipse.

**Comment by phaumer** [comment]
Glad to hear that it worked for you with Oracle. I am resolving it with Won't Fix as we will be focusing on OpenJDK in the future.
