### ISSUE TITLE
Db2 must be installed automatically 

### ISSUE THREAD

**Issue by wpogodzin** [IBM/zopeneditor-about#430]
I propose to include installing db2 automatically(or as added feature),because now I have been trying to install db2 during last week(with Docker then initially on my Windows).Nmber 1032 and  number1042 mistakes appeared,I read 10 recommendations how to fix it and no moving forward.This will be icing on the cake!

- I would like to see..

**Comment by phaumer** [comment]
The complication is that it is published by a different group in IBM. Perhaps we can provide an extension pack at some time, but any specific issue you face now you need to report at https://github.com/IBM/db2forzosdeveloperextension-about/issues
