### ISSUE TITLE
Localization  (l10n) - Associate a comment with each text to be localized

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#432]
## Description of the enhancement requested

In relation to issue:
* #144 

French (and German) localization is now available starting with ZOE version 4.4.0.
Thanks for this. 🤩

It is indicated in the release notes that localization file (`bundle.l10n.<locale>.json`) is automatically generated through IBM's AI machine translation.
To help in detection of automatic localization errors, improve this machine localization by manual reprocessing, or manage other localization languages, it would be necessary to know the context of use of each localized text.

With the i18n localization system, each text was associated with a key that often recalled the context of use of this text.
With the l10n localization system, each text is associated with its English version and it becomes difficult to identify the context of use of this text. However, it is possible to associate a comment with each text, the purpose of this comment is to help translators understand the context without having access to the original source code, (as explain [here](https://github.com/microsoft/vscode-l10n/tree/main/l10n-dev)).

So I suggest:
* associate a comment on each text to explain the context of use of this text,
* this comment could be the old i18n key, or a solution to be defined.

Thanks.

**Comment by phaumer** [comment]
Thanks for the suggestion. I am closing this one for now as it more relates to our IBM internal processes and not directly to the product delivered. If you see any specific statements/text in Z Open Editor that is not translated correctly it would be great to receive those here as issues.
