### ISSUE TITLE
Copy files across zOS connections

### ISSUE THREAD

**Issue by johntgatesjr** [IBM/zopeneditor-about#438]
I am in the process of moving from one system to another.  I have a connection to each system in my VS Code zowe window.  I copy from one connection successfully.  When I attempt to paste in another connection, I get this error:

Error: z/OSMF REST API Error: | Rest API failure with HTTP(S) status 404 | category: 4 | rc:       8 | reason:   0 | message:  LMINIT error | details:  |   - ISRZ002 Data set not cataloged - 'ZOS23-6B' was not found in catalog. |  |

Is this something that should work?  Would simplify my life if it did.

John

**Comment by JillieBeanSim** [comment]
Hey @johntgatesjr copying data sets across LPARs is not yet available in Zowe Explorer but is available in Zowe CLI.  There is an open [issue](https://github.com/zowe/zowe-explorer-vscode/issues/3012) in Zowe Explorer for this enhancement, feel free to upvote the issue 😄
