### ISSUE TITLE
After upgrade to IBM Z Open Editor 4.5 - RSE cannot open z/os datasets, fails with command not supported

### ISSUE THREAD

**Issue by ziosstaff** [IBM/zopeneditor-about#443]
## Development environment used

- Z Open Editor version:
- Editor Platform
  - [X ] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version:
- Operating System (on which VS Code runs such as Windows 10 2004, otherwise name and version of platform such as OpenShift v4.3): Windows 11
- Java Version (when using VS Code or Theia, execute `java -version` and paste the details here): 11
- [ ] Related to RSE API?
  - RSE API Plugin version: 4.4
  - Zowe CLI version:  7.29.2
  - Node.js version: v18.12.1
- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html) how to get them): yes/no

## Problem Description
Error: This command is not supported with RSE API version 1.0.15

errorDetails: [Error: This command is not supported with RSE API version 1.0.15
  	at d.<anonymous> (c:\Users\xxxxx\.vscode\extensions\ibm.zopeneditor-4.5.0\dist\extension.js:8:2284132)
  	at Generator.next (<anonymous>)
  	at s (c:\Users\xxxxx\.vscode\extensions\ibm.zopeneditor-4.5.0\dist\extension.js:8:2282551)
  	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)],
  label: 'MVS-DATASET-HERE',
  moreInfo: undefined
Detailed steps for reproducing the problem:

1. First step

### Observed behavior

-

### Expected behavior

-

**Comment by phaumer** [comment]
@ziosstaff thanks for reporting this issue. We just released Z Open Editor 4.5.1 and RSE API Plugin for Zowe CLI 4.5.1 with a fix. Let us know if this now works for you again.
