### ISSUE TITLE
zapp.yaml (COBOL) - Wrongly replacing the existing file with the default file

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#444]
## Development environment used

- Z Open Editor version: 4.5.0
- Editor Platform
  - [X] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version: 1.92.1
- Operating System: Windows 10 22H2
- Java Version: 11
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached : no

## Problem Description

We note on some VS Code Workspaces (mono root folder), but not all, corresponding to Git Repositories, that the zapp.yaml file present in this Workspace is wrongly replaced by the default zapp.yaml file, which then creates errors in the search for copybooks, generates errors at the Language Server level, and in fact deactivates many features of Z Open Editor.

This problem seems to be related to timeout issues in VS Code, which can have several origins:
* extension startup time
* volume of files present in the local folders to be scanned declared in the zapp.yaml file

The local folders to scan for copybooks are populated by importing (git clone / fetch / sparse-checkout) other Git repositories containing copybooks.
These imported Git repositories can themselves contain zapp.yaml files.

The problem appears when the number of Git repositories imported into the folder declared in zapp.yaml increases.

The zapp.yaml file can be wrongly overwritten even after starting VS Code, apparently when opening a new COBOL file, which triggers a copybook search, and thus probably a search for the zapp.yaml file.

The workaround was to disable the automatic creation of the zapp.yaml file when it is missing, (but in our case it is not missing, it is just not detected by Z Open Editor).

Thanks.

![image](https://github.com/user-attachments/assets/4a266e33-3020-4855-a36a-f79a7276fc1f)

![image](https://github.com/user-attachments/assets/8d2a1954-6478-41cf-b5c6-315b7facbac0)

![image](https://github.com/user-attachments/assets/5fdc48c1-bf30-467a-9901-5ad7cb03d146)

![image](https://github.com/user-attachments/assets/491ebe4e-375b-4bb0-b565-7a10523ff0eb)

![image](https://github.com/user-attachments/assets/be0e99e8-a72e-4f55-88c2-1ea8702bf37d)

**Comment by phaumer** [comment]
We added an existence check in 5.0.0 to avoid overwriting the file.

**Comment by FALLAI-Denis** [comment]
Hi @phaumer,

Thank you.
However, in our context we will disable the automatic creation of the zapp.yaml file.
There is no reason why it should not exist, and we think it is preferable for our developers to ask us about its absence rather than working with a zapp.yaml file that does not correspond to our operating context.

Maybe we will reactivate the automatic creation when the next request is delivered:
* #391 

Thanks.
