### ISSUE TITLE
Issue with Zowe Explorer v3.0.0

### ISSUE THREAD

**Issue by cybersorcerer** [IBM/zopeneditor-about#448]
## Development environment used
IBM Z Open Editor V4.5.1
ZOWE Explorer V3.0.0
VSCode V1.93.1
Windows 10 Enterprise 22H2
Java IBM Semeru Runtime Open Edition 17.0.5.0 (build 17.0.5+8)
ZOWE CLI V7.24.0
NODE V20.17.0

## Problem Description
Hi guys,
after a Zowe Explorer update to Version 3.0.0 today, i get the following error from IBM Z Open Editor:
```
Error: Unable to register Z Open Editor with Zowe Explorer. Error returned: "Zowe Explorer VS Code Extension 3.0.0 is not compatible. Update Zowe Explorer to a 2.x version."
```
IBM Z Open Editor seems to work somewhat however, at least for HLASM. I get access to macros by hoovering over the macro name, Syntax Highlighting, Outline etc all seems to work so far when used from local files, but it does not work anymore from z/OS Datasets. Looks it does not detect the type of source code. If you open a member of a PDS with HLASM or COBOL Code, it flags it as plain text.  And yes the dataset name pattern is defined in VSCode Extension setttings. When will IBM Z Open Editor Support Zowe Explorer 3.x and the changes in their API?

regards
Ronny

**Comment by FALLAI-Denis** [comment]
Hi,

See:
* #435

**Comment by phaumer** [comment]
@cybersorcerer yes, sorry. We tried to warn people in our Discussion forum. The instructions above will help you to go back. You can also try the [alpha build](https://github.com/IBM/zopeneditor-about/releases/tag/5.0.0-alpha1) we posted here in this repo.

Normally, we cannot talk about dates, but [our announcement for the next release](https://www.ibm.com/docs/en/announcements/application-delivery-foundation-zos-500-developer-zos-enterprise-edition-1700-extend-vs-code-eclipse-productivity-tools-wazi-deploy-302-adds-conditional-statements) just went live. It is the 18th.

**Comment by ssamayoa** [comment]
I just about to ask/complain about this message but since we connect to our z/OS via FTP (z/OSMF is too expensive in terms of CPU which increases our monthly bill) such message is, for now, merely a small inconvenience.

Looking forward for the release!

**Comment by cybersorcerer** [comment]
@phaumer thanks for your answer. I decided to not downgrade but try the alpha instead.
Regards Ronny

**Comment by phaumer** [comment]
5.0.0 is now available
