### ISSUE TITLE
MEMLIMIT= in Jobcard marked as error

### ISSUE THREAD

**Issue by cybersorcerer** [IBM/zopeneditor-about#454]
## Development environment used

- Z Open Editor version: 5.0.0
- Editor Platform
  - [X] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version: Version: 1.94.2
                                         Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
                                         Date: 2024-10-09T16:08:44.566Z
                                         Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.94.2 
                                        Chrome/124.0.6367.243 Electron/30.5.1 Safari/537.36
- Operating System (on which VS Code runs such as Windows 10 2004, otherwise name and version of platform such as OpenShift v4.3): Windows 10 22H2 Build Version 19045.5011
- Java Version (when using VS Code or Theia, execute `java -version` and paste the details here): openjdk version "17.0.5" 2022-10-18
IBM Semeru Runtime Open Edition 17.0.5.0 (build 17.0.5+8)
Eclipse OpenJ9 VM 17.0.5.0 (build openj9-0.35.0, JRE 17 Windows 10 amd64-64-Bit Compressed References 20221018_298 (JIT enabled, AOT enabled)
OpenJ9   - e04a7f6c1
OMR      - 85a21674f
JCL      - 32d2c409a33 based on jdk-17.0.5+8)
- [ ] Related to RSE API? No
  - RSE API Plugin version:
  - Zowe CLI version: CLI Version: 8.0.1
  - Zowe Release Version: v3.0.2
  - Node.js version: v20.17.0

## Problem Description

MEMLIMIT= on a JCL JOB Statement gets flagged as error, this is wrong. The exact same MEMLIMIT= parameter on a JCL EXEC Statement is not flagged. Needless to say, the JOB runs just fine as it is. Have a look at the following screenshot:

![image](https://github.com/user-attachments/assets/bd470708-4f81-4777-9a17-9a7e18e869dd)

As a note the example contains an inline jcl procedure, but the problem is the same using JCL decks without inline procedures.

regards

Ronny

**Comment by phaumer** [comment]
Fixed in v5.1.0.
