### ISSUE TITLE
IBM Z open editor not recognizing file associations and zopeneditor.datasets.jclDatasets

### ISSUE THREAD

**Issue by Madhubalan-p** [IBM/zopeneditor-about#457]
IBM Z open editor not recognizing file associations and zopeneditor.datasets.jclDatasets

## Development environment used

- Z Open Editor version: v5.0.0
- Editor Platform
  - Visual Studio Code
- Editor Platform Version: 1.94.2 (system setup)
- Operating System (on which VS Code runs such as Windows 10 2004, otherwise name and version of platform such as OpenShift v4.3): Windows 10 Enterprise for Virtual Desktops
- Java Version (when using VS Code or Theia, execute `java -version` and paste the details here): openjdk version "21.0.3" 2024-04-16 LTS
IBM Semeru Runtime Open Edition 21.0.3.0 (build 21.0.3+9-LTS)
- [yes ] Related to RSE API?
  - RSE API Plugin version: 5.0.0
  - Zowe CLI version: 8.3.0
  - Node.js version: v20.15.1
- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html) how to get them): no

## Problem Description
After updating to new version of IBM z open editor-v5.0.0, if I open a member from a dataset called myuser.JCLS from zowe explorer, ibm z open editor is not interpreting it as jcl even though i have declared the files.associations in vscode user settings file ("*.JCL*": "jcl","*.JCLS*": "jcl",). it is instead interpreting it is as a normal text file. tried both files.associations and "zopeneditor.datasets.jclDatasets". none of them is working.

Detailed steps for reproducing the problem:

1. First step

IBM z open editor is not interpreting a member from a dataset as jcl even though the file associations and zopeneditor.datasets.jclDatasets have been updated as per dataset name. 

-

IBM z open editor is not interpreting a member from a dataset as jcl after defining file associations and zopeneditor.datasets.jclDatasets as per dataset name. 

-

**Comment by benjamin-t-santos** [comment]
Hi @Madhubalan-p,
Would you mind sharing the version of Zowe Explorer that you are using? In v3, Zowe Explorer switched from using on-disk storage for programs to a virtual file system. This could have affected how Zowe Explorer assigns file extensions to files opened in the tree views.

**Comment by Madhubalan-p** [comment]
Hi @benjamin-t-santos , I am using the new version of zowe explorer-v3.0.2.

**Comment by benjamin-t-santos** [comment]
Hi @Madhubalan-p,
As I expected, the Zowe v3 filesystem is the source of these issues. The new file system has a different path structure for data sets and members. Before, the member name was inserted into the file path in parentheses (ex: `MYUSER.JCLS(MEMBER)`), but now members are added as a new path segment  (ex: `MYUSER.JCLS/MEMBER`). You will need to adjust your `file.associations` to support the new format.

Here is a glob pattern you can try in your `file.associations` to account for the new v3 path format:

- `"**/*JCLS*{,/*}": "jcl"` - matches to any data set or member containing "JCLS"

Let me know if that works for you.

We would like to improve the user experience and avoid situations like this in the future by making Zowe Explorer language agnostic and giving extenders control over how files are associated. Please consider upvoting this issue: https://github.com/zowe/zowe-explorer-vscode/issues/3131

**Comment by Madhubalan-p** [comment]
thanks @benjamin-t-santos . your suggestion works fine. would be great if the documentation of ibm z open editor is updated also.

**Comment by phaumer** [comment]
Marking it as an enhancement for our docs.

**Comment by benjamin-t-santos** [comment]
We explain the new extension format in our docs: https://ibm.github.io/zopeneditor-about/Docs/setting_fileassociations.html#setting-file-associations
