### ISSUE TITLE
Changes are not saved to USS file opened from z/OS Resources Table

### ISSUE THREAD

**Issue by adam-wolfe** [IBM/zopeneditor-about#458]
## Development environment used

- Z Open Editor version: 5.0.0
- Editor Platform
  - [x] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version: 1.95.3
- Operating System (on which VS Code runs such as Windows 10 2004, otherwise name and version of platform such as OpenShift v4.3): Windows 10
- Java Version (when using VS Code or Theia, execute `java -version` and paste the details here):
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html) how to get them): no

## Problem Description

Detailed steps for reproducing the problem:

1. Find a file using the z/OS Resources Table, and click on it to open it in an editor tab.
2. Make some changes.
3. Save the file.
4. Check the file on the mainframe (using "Pull from mainframe" or ssh), and notice that the file does not include your changes.

### Observed behavior

- If I open a file (with write permission), make changes, then hit ctrl+s to save. The file appears to be saved (the dot in the editor tab goes away), but changes are not made to the file on the mainframe.
- However, if I open the same file from the USS tree, make changes, and save the file, the changes are made to the file on the mainframe

### Expected behavior

- If I save changes in an editor tab, the changes should be sent back to the mainframe regardless of how I opened the file using Zowe Explorer.

**Comment by benjamin-t-santos** [comment]
Hi @adam-wolfe,
Thanks for filing this bug, I was able to recreate it. Starting with the next release of Z Open Editor, the z/OS Resources Table will use the same virtual filesystem as Zowe Explorer for opened MVS and USS files. This should fix the issue you are experiencing as well as provide better synchronization between the two views. 
If you encounter other bugs or have any enhancement requests for the z/OS resources table, do not hesitate to file them here.

**Comment by phaumer** [comment]
We fixed this in v5.1.0. Let us know if this works for you.

**Comment by benjamin-t-santos** [comment]
@adam-wolfe Are your advanced capabilities enabled? You can check the advanced capabilities section of the Z Open Editor Welcome Page (Open the Command Palette with Ctrl + Shift + P and run ">IBM Z Open Editor: Welcome" 
<img width="1029" alt="Screenshot 2024-12-10 at 12 18 23 PM" src="https://github.com/user-attachments/assets/874dc57b-3c22-4ccd-aee6-44b862c53ea7">

You can also try opening the table with the ">IBM Z Open Editor: Open z/OS Resources Table" command from the command palette, but this will also only be available if advanced capabilities are enabled.

**Comment by adam-wolfe** [comment]
Ah, makes sense. I do not have an activation key. I had installed Z Open Editor to try to debug an issue a user reported with Zowe Explorer that I thought might have been a conflict between the Z Open Editor and Zowe Explorer extensions, which turned out not to be the case. 

If you and @phaumer believe this to be fixed, I am sure it is good to close.
