### ISSUE TITLE
MACRO hovering/check definition does not work when coded without COPY statement

### ISSUE THREAD

**Issue by ztekSol** [IBM/zopeneditor-about#459]
1. First step

### Observed behavior

when a MACRO is referred from CUSTOM MACLIB using 
-MVS property group , hover/check definition   is working only when the MACO is coded with a COPY statement. It's not working when the MACO is coded as a regular operand.  is  this expected behaviors.

example #1 : MACRO name ICEPL68 from remote MVS MACLIB

 COPY ICEPL68 ( hover over macro works as it is coded with COPY statement ) 
 ICEPL68 ( does not work as it in cot coded with COPY statement ) 

example #2 : GDSMPFX is in local work space directory , however hover does not work as it is not coded with COPY statement )

DSMCIANP GDSMPFX                                                        
         END   DSMCIANP                                                 

### Expected behavior

Can we have hovering / peek definition functionality for all MACROs ( local / remote with MVS type) whether coded with COPY statement or not ?
-

**Comment by sdaimwood** [comment]
Hi there, thank you for your interest and use of Z Open Editor. See https://github.com/IBM/zopeneditor-about/issues/316 regarding resolution of custom macros. Currently local macros are supported for custom macro resolution as an [advanced capability](https://ibm.github.io/zopeneditor-about/Docs/advanced_overview.html). Remote macros will also be supported in a future release.
