### ISSUE TITLE
Issue with "go to reference/definition" and "find all references"

### ISSUE THREAD

**Issue by jgorday** [IBM/zopeneditor-about#46]
Issue Type: <b>Bug</b>

I'm working through the course and when I hover over a variable name and try to use "go to definition,"" go to reference" or "find all references" it says that none exist. Thing is, these functions were working earlier just fine. What have I screwed up and how can I fix it? Thanks! 

Extension version: 0.4.9
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 2, 1|
|Memory (System)|16.00GB (11.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by phaumer** [comment]
@jgorday thanks for the report. Could paste in the specific piece of code from the course that caused the problem so that we can try reproducing it?

**Comment by phaumer** [comment]
I am closing this item for now until we have more information about how to reproduce.
