### ISSUE TITLE
Cannot succesfully execute 'zowe rse' command

### ISSUE THREAD

**Issue by dastagg** [IBM/zopeneditor-about#48]
I am trying to complete the tutorial located here:

https://ibm.github.io/zopeneditor-about/Docs/rse_tutorial.html#prerequisites

I have installed the rse plugin and created a rse profile (rseCLI):
```
zowe profiles create rse rseCLI --host 192.86.32.250 --port 4035 --user <myZid> --password <mypw> --base-path rseapi --reject-unauthorized false --protocol https
```
replacing the --user and --password values.

When I try to run the first test command:
`zowe rse submit local-file "./JCL/ALLOCATE.jcl"`
I get the following error:

```
$ zowe rse submit local-file "./JCL/ALLOCATE.jcl"
Command Error:
Zowe REST Operations API Error:
http(s) request error event called
Error: write EPROTO 139741148952448:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

Error Details:
HTTP(S) client encountered an error. Request could not be initiated to host.
Review connection details (host, port) and ensure correctness.

Host:      192.86.32.250
Port:      4035
Base Path: rseapi
Resource:  /api/v1/jobs/string
Request:   POST
Headers:   [{"Accept":"application/json"},{"Content-Type":"application/json"}]
Payload:   {
```

I created a new profile (rseCLI3).with protocol: http (instead of https) 
set it to be the default and I get this error message:

```
$ zowe rse submit local-file "./JCL/ALLOCATE.jcl"
Command Error:
Zowe REST Operations API Error:
http(s) request error event called
Error: Parse Error: Expected HTTP/
Error Details:
HTTP(S) client encountered an error. Request could not be initiated to host.
Review connection details (host, port) and ensure correctness.

Host:      192.86.32.250
Port:      4035
Base Path: 
Resource:  /api/v1/jobs/string
Request:   POST
Headers:   [{"Accept":"application/json"},{"Content-Type":"application/json"}]
Payload:   {
```
I am using the ZOSMF plugin, same host/different port(10443) and it works.

I also tried created zseCLI2 and rseCLI4 with 10443 and http/https but that didn't work either.

Any ideas or thoughts would be welcomed.

**Comment by dastagg** [comment]
I'm going to close this. It appears that the RSEAPI is not installed/configured yet.

**Comment by phaumer** [comment]
Thanks @dastagg. Yes steps have to be done on z/OS as this is a new technology that requires an RSE update: https://ibm.github.io/zopeneditor-about/Docs/rse_interactwithzos.html#installing-the-rse-api-z-os-host-component
