### ISSUE TITLE
Unable to open outline

### ISSUE THREAD

**Issue by zbotzer** [IBM/zopeneditor-about#49]
I'm trying to open outline for some of our COBOL members  but got the message:
"The active editor cannot provide outline information"
I reviewed issues for this issue but couldn't find any regarding COBOL.

Any help would be appreciated.

**Comment by phaumer** [comment]
@zbotzer do you see messages in the Output panel? Most users who experience this issue have a problem with installing the correct Java version? For example, https://github.com/IBM/zopeneditor-about/issues/47. 

Did you check the Java-related topics in this section? https://ibm.github.io/zopeneditor-about/Docs/getting_started.html#prerequisites

**Comment by zbotzer** [comment]
@phaumer Yes, indeed. I've got a problem with the correct Java version. I didn't connect that.
I didn't manage to set up settings.json to include "zopeneditor.JAVA_HOME" .
I managed once but after trying to add other parts.
I attached my settings.json. Please check what's wrong. Tnx

[settings.json.txt](https://github.com/IBM/zopeneditor-about/files/4611247/settings.json.txt)

**Comment by zbotzer** [comment]
@phaumer I managed to fix settings.json and now I can see messages in the outline panel.
But hovering  is not working for me. What I'm doing wrong?
Thanks

**Comment by zbotzer** [comment]
Editing ZOS COBOL or Assembler member, on OUTLINE I got:
"No symbols found in document ...."
Works fine for JCL  members.
 What is wrong?

**Comment by phaumer** [comment]
Closing this item for now as it seem to be related to incorrect syntax of the COBOL, i.e. using the wrong columns as discussed in the Slack channel. We do not offer an outline view for JCL. It is just syntax highlighting. We also do not have Assembler support, yet.
