### ISSUE TITLE
Cobol Property Group Path Wildcarding

### ISSUE THREAD

**Issue by pwawrzoszek** [IBM/zopeneditor-about#5]
Let’s say I have a directory structure where my copybooks are in nested folders, split by application like so:

globalCopybooks/APP1/CPY/app1.cpy
globalCopybooks/APP2/CPY/app2.cpy

Am I able to wildcard the path in the cobol property group location property to pick up all the above folders? For example:

    "wazi.cobol.propertygroup": [
        {
          "name": "copylibs",
          "locations": [
            "../globalCopybooks/*/CPY"
          ],

I would expect the above path to pick up all the copylibs in that directory structure. Instead, it seems that wazi can’t find any of my copybooks now. I have to explicitly specify the path. This would be useful functionality to have as interfaces likely won't exist in just one folder.

**Comment by phaumer** [comment]
@pwawrzoszek we added this now for local files in v.0.3.11 of the IBM Z Open Editor in the VS Code Marketplace. Try it out and let us know how it works for you. The docs are here <https://ibm.github.io/zopeneditor-about/Docs/setting_propertygroup.html>
