### ISSUE TITLE
Allow binary download with "zowe rse download data-set" (like zos mf --binary option)

### ISSUE THREAD

**Issue by travatine** [IBM/zopeneditor-about#58]
Hi,

Please can an option be added to allow downloading files as binary?
(and / or also the "encoding" option like zosmf has too?)

![image](https://user-images.githubusercontent.com/17565183/84885677-f3969780-b0c5-11ea-89d1-0fcf86e8476e.png)

Thanks

**Comment by travatine** [comment]
Also Zosmf dataset download API appears to treat text files as ibm1047 and converts then to ASCII/utf8 when downloaded as text, RSE appears to use ibm037 instead- this results square brackets ( as used in json) being changed to "incorrect" characters.

**Comment by phaumer** [comment]
Thanks. We want to add that.

**Comment by travatine** [comment]
Thanks for adding unix file download as binary in v1.1.0.  ( https://ibm.github.io/zopeneditor-about/Blog/rse-october-110.html#download-unix-files-as-binary ), would it please be possible to also download data sets as binary?
Thanks again

**Comment by phaumer** [comment]
@travatine this was now added to RSE API Plugin for data sets in Zowe CLI v1.1.2. Can you let us know if this works for you as expected?

**Comment by travatine** [comment]
Hi @phaumer ,

Thanks for implementing this feature.
It will be very useful for downloading UTF8 JSON from data sets.

I just installed v1.1.2 ( I have @zowe/cli@6.25.0):
```
...
PS C:\Users\travatine> zowe plugins list

Installed plugins:

 -- pluginName: @ibm/rse-api-for-zowe-cli
 -- package: D:\bm-rse-api-for-zowe-cli-1.1.2.tgz
 -- version: 1.1.2
 -- registry: https://registry.npmjs.org/
```

The new command is available in the CLI:
```
PS C:\Users\travatine> zowe rse  download ds -b "a4.load(idida)"
Command Error:
This command is not supported with RSE API version 1.0.2
```


As soon as I get the PTF for RSE API 1.0.3 Installed, I'll confirm the download works too.

Thanks!

**Comment by travatine** [comment]
Hi @phaumer ,

I got the RSE API 1.0.3 PTF applied.

When I download a dataset member ( program object )  as Text , it works:
```
PS C:\Users\fam-travist> zowe rse  download  ds  "'a4.linklib(idichki)'"
Data set downloaded successfully.
```

When I try downloading the same " program object" as binary, I get a 401 error:
```
Destination: a4/linklib/idichki.txt
PS C:\Users\fam-travist> zowe rse  download  ds  "'a4.linklib(idichki)'" --binary
Command Error:
Zowe REST Operations API Error:
Rest API failure with HTTP(S) status 401
<!doctype html><html lang="en"><head><title>HTTP Status 401 – Unauthorized</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 401 – Unauthorized</h1></body></html>
Error Details:
HTTP(S) error status "401" received.
Review request details (resource, base path, credentials, payload) and ensure correctness.

Host:      pthfae1
Port:      6800
Base Path: rseapi
Resource:  /api/v1/datasets/a4.linklib%28idichki%29/rawContent
Request:   GET
Headers:   [{"Authorization":"Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MDc5MTU3MDksInN1YiI6InRyYXZpc3QiLCJpc3MiOiJyc2VhcGkiLCJqdGkiOiI1M2Y3ODI5MS0yN2ExLTRkMGEtYmJkMy1mNWQ0NThhZWRkYTIiLCJSQUNGX1RpY2tldCI6Ik1KWDBLOVhRIiwiSlNPTl9EQVRBIjoiSlNPTiBPQkpFQ1QiLCJleHAiOjE2MDc5NDQ1MDl9.F2j06aRl8QNWV1xUuAI-ghD48w3joRRzqItBZ8IsSac"},{"Accept":"application/octet-stream"},{"Content-Type":"application/octet-stream"}]
Payload:   undefined
```
I tried downloading the member as "text" again after the error, and the download was successful ( so I think I am still authenticated when attempting the binary download).

Am I running the command incorrectly or something?
