### ISSUE TITLE
Debugging statements flagged in ENVIRONMENT-DIVISION and DATA-DIVISION

### ISSUE THREAD

**Issue by edrubins** [IBM/zopeneditor-about#59]
## Development environment used
- Editor Platform
  - [ x] Visual Studio Code
  - [ ] CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standlone Theia
- Platform Version:
VS Code version 1.46.0
Z Open Editor Version 0.5.1
- Operating System (on which VS Code runs such as Windows 10 2004, otherwise name and version of platform such as OpenShift v4.3):
 Windows 10 Version 2004
 Linux Ubuntu 16.04 LTS.
- Java Version (when using VS Code or Theia, extecute `java -version` and paste the details here):
OpenJDK Runtime Environment (build 1.8.0_252-b09)
Eclipse OpenJ9 VM (build openj9-0.20.0, JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20200422_667 (JIT enabled, AOT enabled)
OpenJ9   - 05fa2d361
OMR      - d4365f371
JCL      - 5e623848e9 based on jdk8u252-b09)
- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/knownissues.html) how to get them): yes/no

## Problem Description
According to IBM documentation for Enterprise COBOL, SOURCE-COMPUTER paragraph:
"You can code debugging lines in the environment division (after the OBJECT-COMPUTER paragraph), and in the data and procedure divisions.   "

Debugging lines placed in the ENVIRONMENT-DIVISION and DATA-DIVISION are flagged with  ' "BASIS" expected instead of this error.' Debugging lines in the PROCEDURE-DIVISION are not.

Detailed steps for reproducing the problem:

Add an ENVORONMENT-SECTION.
In the ENVIRONMNET-SECTION add a CONFIGURATION-SECTION.
In the CONFIGURATION-SECTION add a SOURCE-COMPUTER. IBM-370 WITH DEBUGGING MODE. paragraph.
Optionally, add an "OBJECT-COMPUTER. IBM-370. paragraph following the SOURCE-COMPUTER paragraph.
Add  "       D     DISPLAY 'DEBUGING mode enabled." statements to the ENVIRONMENT-DIVISION, DATA-DIVISION and PROCEDURE-DIVISION.

Observed behavior:

The statements added to the ENVIRONMENT-DIVISION and DATA-DIVISION are flagged as described above. This is true both with and without the OBJECT-COMPUTER paragraph after the CONNFIGURATION-SECTION in the ENVIRONMENT-DIVISION.

Designed behavior:
According to the IBM documentation quoted above, the debugging lines should not be flagged in the ENVIRONMENT-DIVISION or the DATA-DIVISION.
-

**Comment by gplambert** [comment]
@edrubins Hi Ed, I think there may be some confusion on the DISPLAY statements being placed in the Environment and Data Divisions.  The IBM documentation doesn't really make it clear, but any statements placed in those divisions still need to be valid statements for those divisions.  Display statements are not valid for the Env and Data divisions.  When `WITH DEBUGGING MODE` is present, all lines with a 'D' in column 7 will be compiled and therefore must be valid statements and syntactically correct.  If you try compiling a program with those DISPLAY statements in those divisions, you should get a compile error.
