### ISSUE TITLE
Usability with closing windows

### ISSUE THREAD

**Issue by davenice** [IBM/zopeneditor-about#6]
1) Preferences view doesn't respond to alt+w

2) I often found myself typing in, or closing, the wrong view because I'm used to Eclipse and closing only editors. I think it isn't clear enough which view has focus. The little light coloured bar isn't very prominent.

**Comment by phaumer** [comment]
I am closing this one now as we are now primarily implementing against VS Code while still striving to making all functions work in Theia as well. `alt+w` works in VS Code so if this remains and issue in Theia we need to file defects there as the Preferences Editors are provided by them.
