### ISSUE TITLE
Cobol comments introduced by a "/" character

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#60]
## Development environment used

- Editor Platform
  - [X] Visual Studio Code
  - [ ] CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standlone Theia
- Platform Version: VS Code 1.46.0 / Z Open Editor 1.0.0
- Operating System: Windows 10 PRO 64 "1607"
- Java Version: build 1.8.0_102-b14
- Logs attached: no

## Problem Description

Detailed steps for reproducing the problem:

1. In a Cobol source, create a line with a "/" character in column 7, followed by a text.

Observed behavior:

The line with the character "/" in column 7 is not colored as a comment. The text is colored like a Cobol line, with recognition of keywords and symbols.
However, it does not raise an error, and is therefore well recognized as being a comment from a syntactical point of view.

The same remark applies to lines with a "D" character in column 7 when the "WITH DEBUGGING MODE" clause is not active.

Designed behavior:

Rows with a "/" character in column 7 should be treated as rows with a "*" character in column 7.

![ZOECOMM](https://user-images.githubusercontent.com/63861965/85318477-57eb9980-b4c0-11ea-8cf9-a79c4267e3fa.png)

**Comment by phaumer** [comment]
We fixed the / issue in v1.0.3.  The `when the "WITH DEBUGGING MODE" clause is not active` case we currently have no plan of fixing.
