### ISSUE TITLE
Configure the string character delimiter in snippets and code completion: QUOTE or APOST

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#61]
Cobol code snippets, and code completion, systematically use QUOTE as a character string delimiter.
In France, it is usual to use the APOST character as a character string delimiter.

You should be able to configure the character string delimiter in the settings of the Z Open Editor extension, Cobol language, and use this character in Cobol snippets and code completion.

This parameter should be able to be managed at the "User", "Workspace" and "multi-files root workspace" levels.

**Comment by FALLAI-Denis** [comment]
Ideally, the choice of character delimiter should be dependent of the presence of the "CBL QUOTE|APOST" compilation directive in the source code being edited.

**Comment by phaumer** [comment]
Fixed in Z Open Editor 1.1. We extended property groups with language and compiler option properties:
https://ibm.github.io/zopeneditor-about/Docs/setting_propertygroup.html#language-scoping
