### ISSUE TITLE
EXEC SQL WHENEVER are compilation directives (not statement) : not concerned by unreachable code 

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#63]
## Development environment used

- Editor Platform
  - [x] Visual Studio Code
  - [ ] CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standlone Theia
- Platform Version: VS Code 1.46.1 / ZOE 1.0.0
- Operating System: Windows 10 1607
- Java Version: 1.8
- Logs attached: no

## Problem Description

Extract from https://github.com/IBM/zopeneditor-about/issues/18#issuecomment-643372231

In some cases the "EXEC SQL WHENEVER" directives can be considered as not reachable, but as they are not instructions, they are compilation directives, they should not appear as non-reachable code.

**Comment by sdaimwood** [comment]
This bug was fixed in version 4.3.0, thank you for your patience while we worked on a fix.
