### ISSUE TITLE
 The secure credentials Zowe CLI plugin is active and currently not supported

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#66]
## Description of the enhancement requested

We use Z Open Editor to work on Cobol sources.
These Cobol sources use COPYBOOKs. COPYBOOKs are available on the z/OS host system.

Z Open Editor cannot access COPYLIBs on the z/OS host: it fails due to the presence of the Secure Credentials plugin.

See attached log.
[zoe-log.txt](https://github.com/IBM/zopeneditor-about/files/4838249/zoe-log.txt)

![ZOE-COPY](https://user-images.githubusercontent.com/63861965/85882740-1d477100-b7e0-11ea-8d83-d5be2ab2b8ad.png)

![ZOE-properties](https://user-images.githubusercontent.com/63861965/85882986-84fdbc00-b7e0-11ea-8699-9674ea910f8d.png)

**Comment by phaumer** [comment]
Support for the Secure Credentials plugin is on our roadmap to support. For now you need to use profiles that do not use it.

**Comment by peterpk** [comment]
Hopefully it's fairly high on the roadmap.  Telling users "you must store your password in cleartext to use our function" is not a great message.

**Comment by oakmount66** [comment]
I'm in line with peterpk - I hope it will come very soon. 
In our organization we have been told by the security guys, that saving the password in clear text is a now go (read a show stopper)

/Lars.

**Comment by davidkjackson54** [comment]
This is likely to be a showstopper for many secure sites.  Ourselves included.

**Comment by phaumer** [comment]
Fixed in Z Open Editor 1.1.

**Comment by FALLAI-Denis** [comment]
Thanks a lot !
