### ISSUE TITLE
Force the opening of COPYBOOK / INCLUDE in a new Editor (Ctrl + Clic)

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#67]
## Description of the enhancement requested

By default, the opening of a COPYBOOK (or an INCLUDE) from a Cobol source code (or from a PL / I source code), by the action "Ctrl + clic" on the preview, is done in the current editor (and replaces the current source code) if the source has not been modified (still in "preview mode").

This behavior can be avoided by setting the "workbench.editor.enablePreview" parameter to "false".

It would be preferable that the opening of a COPYBOOK or INCLUDE by the action "Ctrl + clic" is always done in a new editor, regardless of the "workbench.editor.enablePreview" parameter.

**Comment by phaumer** [comment]
I think we want to provide an authentic VS Code experience as much as possible. With the setting you have the choice to configure it the way you want.
