### ISSUE TITLE
macros highlight as parameters, not instructions

### ISSUE THREAD

**Issue by mhammack** [IBM/zopeneditor-about#69]
First, thank you!  I've been looking for an HLASM syntax highlighter for VS-Code for a while.

When I opened a file, I noticed that instructions typically show up as magenta (on my system) as do macros.  However, if the macro name starts with a dollar sign ('$'), that is highlighted the same as arguments and then the arguments to the macro are highlighted as comments.  Other local macros are fine.

Not end of world, but a difference from ISPF editor.

**Comment by kdbeall** [comment]
@mhammack Thank you for pointing this out! I'll update our textmate grammar.

**Comment by FALLAI-Denis** [comment]
MACRO are like COPY and should be search for according to propertygroups. 
They can define Data or Code. 
But names for Data or Label can be « computed » by Macro coding.

**Comment by phaumer** [comment]
Fixed the $ issue in v1.0.3.
