### ISSUE TITLE
IBM Z Open editor takes over as the Default editor for .cbl. .cob files

### ISSUE THREAD

**Issue by venkatzhub** [IBM/zopeneditor-about#70]
## Development environment used

- Editor Platform
  - [ x] Visual Studio Code
  - [ ] CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standlone Theia
- Platform Version: 1.47
- Operating System (on which VS Code runs such as Windows 10 2004, otherwise name and version of platform such as OpenShift v4.3): Mac OS Mojave 10.14.6
- Java Version (when using VS Code or Theia, extecute `java -version` and paste the details here): 
<img width="1239" alt="image" src="https://user-images.githubusercontent.com/33162229/87429795-ec21bb80-c5a9-11ea-9114-7b2e45dd48c4.png">

- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/knownissues.html) how to get them): no

## Problem Description

IBM Z Open Editor takes over as the Default editor for .cbl and .cob files. In my VSCode instance, I have other COBOL extensions including COBOL Language support extension (https://marketplace.visualstudio.com/items?itemName=broadcomMFD.cobol-language-support) and Bitlang COBOL extension. Once IBM Z Open Editor is installed, I could not find a way to use the other COBOL extensions that were installed resulting in some capabilities not working properly. The only way to use the other extensions is to disable or uninstall IBM Z Open Editor. 
Once I uninstall the IBM Z Open Editor, VSCode requires a reload, but that still doesn't remove the IBM Z Open editor completely, I had to quit and restart VSCode.

Detailed steps for reproducing the problem:
Install IBM Z Open Editor from VSCode Marketplace
Open a COBOL file 
Try to change the association - but that is not taking effect. 

### Expected behavior
User should have the choice to pick different editor associations when multiple editors are in play.

**Comment by phaumer** [comment]
@venkatzhub we did this on purpose for a simpler user experience and to avoid that other extension would somehow accidentally interfere or users would reports issue that are not related to our extension as they might have lost track. VS Code does allow you to disable and enable extensions for each individual workspace, which could be workaround for now. 

We should probably consider providing on/off switches for specific languages in our settings, though. Will explore that.

**Comment by venkatzhub** [comment]
@phaumer - thanks for looking into the on/off switches for specific languages, that would be required to allow users to take advantage of the capabilities being offered by other extensions.

**Comment by venkatzhub** [comment]
@phaumer - any updates on this? We are getting more and more customers running into this issue.

**Comment by spgennard** [comment]
@phaumer - Have you considered having an alias in the languages/package.json, for example: ibm.cobol

Then you could do, the following in the settings:

```json
   "files.associations": {
        "*.cob": "IBM_COBOL"
    }
```

Plus, this would also allow you check the document and change the document language on the fly:

```typescript
vscode.languages.setTextDocumentLanguage(doc, "IBM_COBOL");
```

**Comment by phaumer** [comment]
@spgennard thanks, we will look into adding an alias, but keep the cobol language id as MS defines the situation of multiple extensions with `This will introduce a new language or enrich the knowledge VS Code has about a language.` [here](https://code.visualstudio.com/api/references/contribution-points#contributes.languages). I guess this would be more important for @venkatzhub to do as well to be able to resolve such conflicts in che4z.

**Comment by phaumer** [comment]
@venkatzhub I tried the "alias" proposal from above and it seems that the alias is only for documentation purposes. The file.association object only works with the case-sensitive language ID from my experimentation. We use "cobol", Bitlang uses "COBOL", so another extension that wants to avoid conflict would have to define a different one such as "Cobol" or "che4z.cobol". 

For now I close this one as won't fix as I do not see anything we can do from our end.

**Comment by venkatzhub** [comment]
@phaumer, we will look into what file.associations object definition on our side is.
