### ISSUE TITLE
To be able to exclude the search for certain COPYBOOKs or INCLUDEs

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#71]
## Description of the enhancement requested

For the Cobol language, Z Open Editor searches for a "SQLCA" member when it is referenced by an "EXEC SQL INCLUDE SQLCA" instruction.
This member does not exist because it is implicitly known to the Db2 pre-compiler or coprocessor.
This triggers unnecessary alerts, which are also misdiagnosed (Alert on the validity of the profile rather than on the member who is not found).

It should be possible to exclude certain searches by members of COPYBOOKs or INCLUDEs, either as in the case of "SQLCA" because they do not exist, or because they are not of interest for development.
A list of COPYBOOKs / INCLUDEs not to be searched should be able to be specified in the extension settings.

![ZOE-SQLCA](https://user-images.githubusercontent.com/63861965/87432827-cec01200-c5e8-11ea-8942-204d505ca008.png)

![ZOE-SQLCA notification](https://user-images.githubusercontent.com/63861965/87433077-2b233180-c5e9-11ea-8369-d7f3f08d9857.png)

`[2020-07-14 15:19:47.361 - WARN] ** The COBOL language server requested the include file "SQLCA", which was not found. Check your Zowe CLI profile and property groups settings or switch to the "DEBUG" log level for more information. **
`

[zopeneditor-20200714-151730.log](https://github.com/IBM/zopeneditor-about/files/4919181/zopeneditor-20200714-151730.log)

**Comment by AlexKotsc** [comment]
It seems to delay syntax checking and triggers a search after every keystroke.

**Comment by phaumer** [comment]
Fixed in Z Open Editor 1.1. We did not make it customizable, yet but ignore SQLCA and SQLDA. Please open a new issue with some examples to motivate making this entirely customizable.
