### ISSUE TITLE
Support FEPI (Front-End Programming Interface) syntax for EXEC CICS code

### ISSUE THREAD

**Issue by wolfstevent-penfed** [IBM/zopeneditor-about#75]
Error messages on all EXEC CICS code 
e.g. Unexpected input {0} found.fepi allocate pool    (ws-fepi-pool-name)                                                       convid  (ws-fepi-conv-id)                                                         target  (ws-fepi-target)                                                          timeout (ws-fepi-timeout)                                                         resp    (ws-cics-resp)                                                            resp2   (ws-cics-resp2) unexpected tokens ignored
## Development environment used

- Z Open Editor version:
- Editor Platform
  - [x ] Visual Studio Code
  - [ ] CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version: 1.0.3
- Operating System (on which VS Code runs such as Windows 10 2004, otherwise name and version of platform such as OpenShift v4.3): Windows 10 10.0.17763
- Java Version (when using VS Code or Theia, extecute `java -version` and paste the details here):
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) Client VM (build 25.251-b08, mixed mode)

- [ ] Related to RSE API?
  - RSE API Plugin version: n/a
  - Zowe CLI version: none
  - Node.js version: none
- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/knownissues.html) how to get them): yes/no

EXEC CICS code is tagged with squiggles and multiple error messages

Detailed steps for reproducing the problem:

1. Open a cobol program in VS Code with IBM Z Open Editor plug-in installed
2. Scroll to any EXEC CICS statement
3. Note the 5 or more error messages in the Problems tab

### Observed behavior
Squiggles on EXEC CODE
-

### Expected behavior
Syntax validation of EXEC CICS code.
-

**Comment by gplambert** [comment]
@wolfstevent-penfed - thank you for trying out our VS Code extension.  Are the yellow squiggle lines under variable names or the EXEC CICS commands?  If under the variable names, are they defined in a copybook?  If so, then it could be the syslib preference setting does not have the location of the copybook.  If it is a copybook, is it local or on a remote z host?

**Comment by wolfstevent-penfed** [comment]
Below is a screenshot of the error.  It may be related to this CICS call being for FEPI (Front-End Programming Interface) as other EXEC CICS calls are okay.

Are the yellow squiggle lines under variable names or the EXEC CICS commands?

The squiggle lines are under the entire command except for EXEC CICS.

If under the variable names, are they defined in a copybook?

The variable names are in working-storage, not a copybook.

If so, then it could be the syslib preference setting does not have the location of the copybook. If it is a copybook, is it local or on a remote z host?
N/A, not a copybook.

[cid:image001.png@01D679F6.8D9890B0]

A good EXEC CICS call:
[cid:image002.png@01D679F6.8D9890B0]

Steve Wolf
Programmer III/Hogan Support
O/C: 425-229-5288

**Comment by phaumer** [comment]
@wolfstevent-penfed I revised the title a bit so that we more easily know what we need to extend.

**Comment by wolfstevent-penfed** [comment]
Thanks @phaumer , I hadn't realized until I went back to the program code that only the FEPI calls were getting the dreaded squiggle.

**Comment by phaumer** [comment]
Thank you for submitting this request. We reviewed this item and decided to not plan adding this language support, we want to tolerate statements such these in the future.
