### ISSUE TITLE
Cleanup for sequence numbers (1-6) and id area (73+) columns

### ISSUE THREAD

**Issue by Morridt** [IBM/zopeneditor-about#8]
Is it possible to add options to ignore these areas, and/or (at the least) an option clear those areas?

**Comment by phaumer** [comment]
We can investigate if there are things we can do (such as clearing "macros"). Generally, the VS Code APIs are limiting the access we have to the underlying Monaco editor to enforce things such as events in specific columns.

**Comment by Morridt** [comment]
Thanks.  I have a python script that does it for me but would prefer to just be able to ignore.  I could see it being painful to code listening for events and handling.

**Comment by phaumer** [comment]
So, if we have a menu option to remove sequence numbers completely from the code, would that be valuable to you?

**Comment by Morridt** [comment]
Yes please, that would be good.  Options to remove sequence numbers (1-6), id (73+), or both.

**Comment by cds-ari** [comment]
In the interim, you can hold down ALT+SHIFT and drag the cursor to do a text block selection of the entire sequence number column. Then press DEL and it's gone!

**Comment by bearou** [comment]
As we are getting closer to launching VS Code as COBOL editor option; we would like to vote for this Enhancement too.

**Comment by AlexKotsc** [comment]
+1

**Comment by phaumer** [comment]
We added the ability to strip and renumber sequence numbers in version 1.2. 
https://ibm.github.io/zopeneditor-about/Docs/editor_codechanges.html#renumbering-and-unnumbering-sequence-numbers

@Morridt @cds-ari @bearou @AlexKotsc @FALLAI-Denis let us know what you think.

**Comment by FALLAI-Denis** [comment]
@phaumer 

Hi,
For COBOL, line / sequence numbers are columns 1 to 6... columns 73 to 80 are "ident" (kind of comment on the line).
Columns 1 to 6 can be "numbered" or "unnumbered", but not columns 73 to 80.

**Comment by Morridt** [comment]
Agreed..... "Unnumber Sequence Number" should be 1 to 6. 
I see the id area 73 to 80 being cleared instead.
Though the option to clear both the id area and sequence number is still required.

To pinch the "Denumber" option in Topaz Wotrkbench:
    O Cols-1-6
        o Clear numeric fields only
        o Clear all fields
    O Cols 73-80
        o Clear numeric fields only
        o Clear all fields

**Comment by phaumer** [comment]
@FALLAI-Denis @Morridt thanks for the feedback. We focused on customer cases with sequence numbers in 73 to 80, but we should take those other cases under consideration as well. I am reopening this item, but slightly rename it.

**Comment by FALLAI-Denis** [comment]
@phaumer 

hi,

If possible to do it, we would like that sequence number / id area renumber / unnumber menu action should controlled by a settings option. 
We use sequence number / id area to « tag » lines for some assistant coding tools (Code generator). Developers must not erase these tags.

Thanks

**Comment by phaumer** [comment]
We updated this capability in v1.2.5 as discussed here. Let us know what you think.
