### ISSUE TITLE
Copybooks are not always underlined and clickable

### ISSUE THREAD

**Issue by oakmount66** [IBM/zopeneditor-about#81]
From time to time when opening a new COBOL program, copybooks are not shown underlined and you cannot ctrl-click opening them. See sample

![image](https://user-images.githubusercontent.com/60236192/92485681-8c334400-f1eb-11ea-9a6f-6cd4ca17d45b.png)

The error will stay there until I reopen the program or just switch to another tab and back again.

/Lars

**Comment by gplambert** [comment]
@oakmount66 - Thank you for the issue.  Does this happen when it is the only program opened in an editor window or when you have multiple programs open?

**Comment by oakmount66** [comment]
Hi GP.
Thanks for getting back.
I've just made some more tests and it doesn't have anything to do with the number of programs open. But it has certainly something to do with the size of the program. With small programs the error are not seen. But with larger programs like  400+ lines I see it often. Not always but often.
I have not tested if it's the number of lines, the number of statements, the number of copybooks or just the time it takes to download the program and the copybooks that creates the error. But it has something to do with the size/delay.
/Lars.

**Comment by gplambert** [comment]
@oakmount66  What is your memory allocation setting?  The default is 512 but we recommend 1024 if editing large programs. In the Preferences --> Settings --> User Tab -->  Expand Extensions --> IBM Z Open Editor --> Scroll down to Server: Memory Allocation.

**Comment by phaumer** [comment]
I have seen this before, especially when debugging our code. I think it is a time out and/or async call issue. I assume that the LSP client only gives the server a certain amount of time to respond to a request and moves on if it does not respond in time to avoid that the editor's performance gets impacted by this. I am not sure how much we can tweak here. The workaround as you mentioned is a simple focus change that causes the editor to refresh then finding the remote files in the local cache. Some things we can play with in the future is options for specifying prefetch rules for members, caches that do not get cleaned when the editor stops etc. This one will be a lower priority for now.

**Comment by oakmount66** [comment]
Hi GP and Peter.
My memory allocation was already 1024.
I think than Peters explanation sound reasonable and we will live with this little obstacle. It's not a show stopper for us :-)
Best regards
Lars.

**Comment by phaumer** [comment]
Testing on Windows a lot recently and I see it happening there much more than on my Mac. We will definitely try to find a fix (as a medium priority as it is not a blocker and has a workaround).

**Comment by phaumer** [comment]
We have this one fixed for COBOL and PL/I. HLASM will be in a future release. Let us know if this works now in v2.0.0.
