### ISSUE TITLE
National chars are not translated when resolving copybooks

### ISSUE THREAD

**Issue by bearou** [IBM/zopeneditor-about#82]
When using `--ec 277` as parm when creating Zowe zOSMF profile, this translates beautifully the (Danish) national chars from EBCDIC to the true values in VS Code. And vice versa.

But... when resolving and peeking a copybook, it appears that the same translation is not done.

Attached image example of this behaviour.

## Development environment used

- Z Open Editor version: v1.0.4
- Editor Platform
  - [X ] Visual Studio Code
  - [ ] CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version: VS Code 1.48.2
- Operating System (on which VS Code runs such as Windows 10 2004, otherwise name and version of platform such as OpenShift v4.3): Windows 7
- Java Version (when using VS Code or Theia, extecute `java -version` and paste the details here): 1.8.0_261
- [ ] Related to RSE API? No
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/knownissues.html) how to get them):  no

## Problem Description

Open COBOL member in VS Code. Locate COPY statement in source. 
Either peek or open the copybook member. In neither case, the national characters are translated at all. 

 

### Observed behavior

No translation of national chars

### Expected behavior

Translation of national chars
![image2020-9-10_11-39-56](https://user-images.githubusercontent.com/48259804/92718508-33d28280-f362-11ea-96c9-3d1254ed7912.png)

**Comment by phaumer** [comment]
This one is dependent on Zowe work: https://github.com/zowe/vscode-extension-for-zowe/issues/671

**Comment by phaumer** [comment]
This was added now with v1.1.2: you can specify an `--encoding` parameter when you create your RSE API or z/OSMF profile and Z Open Editor will utilize it.

@bearou could you let us know if this meets you expectations?
