### ISSUE TITLE
Collect Metrics on the Number of Installs of Z Open Editor 

### ISSUE THREAD

**Issue by mpanch59** [IBM/zopeneditor-about#84]
I would like to know how to capture the number of installs metrics via an API to update and create reports for the number of installs/downloads of IBM Z Open Editor 

This is currently displayed on maketplace here 

https://marketplace.visualstudio.com/items?itemName=IBM.zopeneditor&ssr=false#qna

IBM Z Open Editor
IBM
|
**14,732 installs**
| (11) | Free

## Description of the enhancement requested

I would like to know how to capture the number of installs metrics via an API to update and create reports for the number of installs/downloads of IBM Z Open Editor

**Comment by phaumer** [comment]
@mpanch59 can you provide more details for this request, i.e. why you need to access this number? 

IBM does not control the VS Code Marketplace. It is a Microsoft product. Perhaps they have documentation or take enhancement request?
