### ISSUE TITLE
Cannot resolve include files with $ in the name

### ISSUE THREAD

**Issue by davidkjackson54** [IBM/zopeneditor-about#86]
Just installed VSCode and z Open Editor v1.0.4 along with Zowe Explorer 1.9.0 and when viewing a PDS containing ASM source, I am getting this popup message in the lower right. 

Can you advise as to how I might debug this ?  
The PDS contains 153 members some of which are over 10k in size.  I notice that teh final member is itself not present in the tree structure in VSCode. 

The popup message keeps appearing constantly every few seconds. with no keyboard activity.

![image](https://user-images.githubusercontent.com/46171060/94625209-0dbb4680-026d-11eb-8851-35e2b8f5c326.png)

**Comment by phaumer** [comment]
This error is typically shown when the editor tries to resolve your property groups and gets invalid content back. For example, we have seen people that use firewalls that return an html page for logging on when running REST requests against zosmf or rse api if they have not authenticated with the firewall first. 

It could be a problem with the configuration of your property groups. You can use the logger's output to troubleshoot the issue. See these pages:

- https://ibm.github.io/zopeneditor-about/Docs/knownissues.html#troubleshooting-using-log-files
- https://ibm.github.io/zopeneditor-about/Docs/setting_propertygroup.html#mvs-property-groups-using-zowe-cli

**Comment by davidkjackson54** [comment]
Hi Peter,
I have turned on DEBUG level of logging but nothing is being reported when the popup message is displayed. 
The only messages that are displayed relate to not being able to find a copybook member.  which does not seem to correlate to what the popup message is complaining about.  i.e. Invalid data set content returned from API call. Please check your connection details.
I am still also seeing the last member in the PDS to be missing from the table view. 

Separately, one issue that I have observed, is that in our products, we have copybooks that have a name such as SER$GLBL
I am finding when I run with DEBUG active that the name appears to be truncated at the $ symbol so I am getting this reported in debug
DEBUG] ** ZLanguagesResourceResolver.findIncludeFiles: Did not find "SER" with property group "mvs-members". If there are more, will look in the next property group. **

This is confirmed in the display as follows  - note it only puts the squiggles under the partial name..
![image](https://user-images.githubusercontent.com/46171060/94737806-4fa6c400-0323-11eb-86c1-6919129c68ca.png)

**Comment by phaumer** [comment]
We will investigate and try to reproduce (also the $ issue). In the current (already fixed in the upcoming release) it could happen that requesting a non-existing members such as SER could cause this error in some circumstances. If you are willing to share your log file with us (either attach or send via email to me directly) I could also have a look.

**Comment by davidkjackson54** [comment]
Peter I have the debug log but I don't see your email address anywhere..  Can you point me to where I can find that?

**Comment by kdbeall** [comment]
@davidkjackson54 I'm investigating this. Thank you for letting us know!

**Comment by davidkjackson54** [comment]
Peter now has the logs..

**Comment by Minoru-nk** [comment]
Hi, I'm having a similar error, but i use a copy with #, and is not recognizing.
Is there any way to set up to recognize? im not in debugg mode.
![error](https://user-images.githubusercontent.com/65982338/96268119-0b602880-0f9f-11eb-9e8e-a4e252872e62.PNG)
Thanks!

**Comment by FALLAI-Denis** [comment]
Zowe CLI / zOSMF does not support codepage encoding for list datasets / members (only for get / put dataset or membre). 

IBM must enhance zOSMF for list actions. 
Then Zowe CLI must use enhancement of zOSMF.

**Comment by phaumer** [comment]
We fixed this issue for HLASM to support `$` `#` and `@` with v1.1.1

**Comment by esubah1989** [comment]
> Hi Peter,
> I have turned on DEBUG level of logging but nothing is being reported when the popup message is displayed.
> The only messages that are displayed relate to not being able to find a copybook member. which does not seem to correlate to what the popup message is complaining about. i.e. **Invalid data set content returned from API call. Please check your connection details.**
> I am still also seeing the last member in the PDS to be missing from the table view.
> 
> Separately, one issue that I have observed, is that in our products, we have copybooks that have a name such as SER$GLBL
> I am finding when I run with DEBUG active that the name appears to be truncated at the $ symbol so I am getting this reported in debug
> DEBUG] ** ZLanguagesResourceResolver.findIncludeFiles: Did not find "SER" with property group "mvs-members". If there are more, will look in the next property group. **
> 
> This is confirmed in the display as follows - note it only puts the squiggles under the partial name..
> ![image](https://user-images.githubusercontent.com/46171060/94737806-4fa6c400-0323-11eb-86c1-6919129c68ca.png)

If you used any of these special characters (#,@,$) in your copybook name, you have to enclose the copybook name with quote in your source code in order to resolve your copybook. For example: `COPY 'SER$BLBL'`. Here is a link to the [document ](https://www.ibm.com/support/knowledgecenter/en/SS6SG3_6.2.0/lr/ref/rlcdscop.html)for more details.
