### ISSUE TITLE
EJECT statements before IDENTIFICATION DIVISION preventing syntax checking

### ISSUE THREAD

**Issue by Morridt** [IBM/zopeneditor-about#9]
_Originally posted by @Morridt in https://github.com/IBM/zopeneditor-about/issues/7#issuecomment-533350782_

Our code has program comments above the IDENTIFICATION DIVISION that also includes EJECT statements.  This prevents syntax checking.  

EJECT statements after IDENTIFICATION DIVISION work ok and have no affect on syntax checking.

      *--------------------------------------------------------------* 
      *--------------------------------------------------------------* 
           EJECT                                                       
       IDENTIFICATION DIVISION.
       PROGRAM-ID. PGM021.
       AUTHOR. MAINFRAMEWIZARD.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-SUB   PIC 9  VALUE ZEROS.
       PROCEDURE DIVISION.
       10000-MAIN-PARA.
             MOVE 5 TO WS-SUB.
             MVE WS-SUB TO WS-SUB
             STOP RUN.

**Comment by phaumer** [comment]
Just an update. We do have a fix for it. We are just waiting for a release window related to legal approvals required. But it will fixed in our next update.

**Comment by Morridt** [comment]
Thanks!

**Comment by phaumer** [comment]
This issue was fixed in version 0.4.1 now available on the VS Code Marketplace.

**Comment by Morridt** [comment]
Thanks Peter.... Confirmed all good from my side.
